### ISSUE TITLE
Not able to create robot 

### ISSUE THREAD

**Issue by Shrey1099** [robocorp/robotframework-lsp#1024]
Type: <b>Performance Issue</b>

To use robocorp in VS code we install 2 extensions(robocorp code and language server) but installing when i try to create robot the below error pops, i have tried reinstalling vs code and extensions still same results.

[Error code: 6
Error name: Error
Unable to activate Robocorp Code extension because python executable from RCC environment was not provided.
 -- Most common reason is that the environment couldn't be created due to network connectivity issues.
 -- Please fix the error and restart VSCode.
Error getting Python
[Error - 6:14:12 PM] Starting client failed
[object Object]
Error initializing Robocorp code.]

Extension version: 1.14.2
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.64GB (6.55GB free)|
|Process Argv|--crash-reporter-id 0a67d7cc-6597-4016-96f7-8c3650a55741|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   134	  3008	code main
    0	   151	   756	   gpu-process
    0	    87	  2968	shared-process
    0	   156	  4180	extensionHost [1]
    0	   131	 19684	     electron-nodejs ("C:\Users\shreyas.malavade\AppData\Local\Programs\Microsoft VS Code1\Code.exe" --ms-enable-electron-run-as-node c:\Users\shreyas.malavade\.vscode\extensions\ms-python.vscode-pylance-2023.12.1\dist\server.bundle.js --cancellationReceive=file:0899171b28246aaf3696a64b463ae7428c73a30928 --node-ipc --clientProcessId=4180)
    0	    22	 21360	     C:\Users\shreyas.malavade\AppData\Local\Programs\Python\Python312\python.exe -u c:\Users\shreyas.malavade\.vscode\extensions\robocorp.robotframework-lsp-1.11.0\src\robotframework_ls\__main__.py -v
    0	    23	    84	       C:\Users\shreyas.malavade\AppData\Local\Programs\Python\Python312\python.exe -u c:\Users\shreyas.malavade\.vscode\extensions\robocorp.robotframework-lsp-1.11.0\src\robotframework_ls\server_api\server__main__.py -v --index-workspace --collect-tests --remote-fs-observer-port=60337
    0	    21	 13044	       C:\Users\shreyas.malavade\AppData\Local\Programs\Python\Python312\python.exe -u c:\Users\shreyas.malavade\.vscode\extensions\robocorp.robotframework-lsp-1.11.0\src\robotframework_ls\vendored\robocorp_ls_core\remote_fs_observer__main__.py -v
    0	    11	 19700	       C:\Windows\system32\conhost.exe 0x4
    0	    93	  8524	window [2] (Issue Reporter)
    0	    89	 12012	fileWatcher [1]
    0	   165	 14480	window [1] (Demo - Visual Studio Code)
    0	    42	 17448	   utility-network-service
    0	    28	 17728	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Demo - Visual Studio Code)
|    Folder (Demo): 0 files
|      File types:
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by fabioz** [comment]
Thank you for the report. Can you provide the full contents of `OUTPUT > Robocorp Code` and paste here (as a comment in this issue) when that happens to be able to diagnose the issue?

-- Example image on what to copy:
![image](https://github.com/robocorp/robotframework-lsp/assets/117621/46cad807-e94b-4a15-906d-8f496a71aa52)

**Comment by fabioz** [comment]
Closing as no further info was given.
