### ISSUE TITLE
Does not recognize variables in the latest Robot framework 7.0 update. 

### ISSUE THREAD

**Issue by Apolayo27** [robocorp/robotframework-lsp#1028]
![image](https://github.com/robocorp/robotframework-lsp/assets/44474459/341d9331-961a-47c1-b0d0-4463c55aa383)

**Comment by goncalo-moura** [comment]
Formatting is not working as well with the newer version of Robot (7.0)

**Comment by fabioz** [comment]
See: https://github.com/robocorp/robotframework-lsp/issues/1051

**Comment by higor-haider** [comment]
When this fix will be released?
