### ISSUE TITLE
Config link in the vs code extension documentation is broken

### ISSUE THREAD

**Issue by villemikkola** [robocorp/robotframework-lsp#103]
The LSP VS Code extension's documentation has a broken link to the config file in the “Configuration” section.
<img width="450" alt="Screenshot 2020-06-25 at 13 44 28" src="https://user-images.githubusercontent.com/1714724/85705551-fe66b300-b6e9-11ea-98d6-6593f63795b4.png">

“See **Config** for details.” links [here](https://github.com/robocorp/robotframework-lsp/blob/master/docs/config.md) which seems to be an empty config file. I guess it should link [here](https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/config.md) as github page suggests that as well?

**Comment by fabioz** [comment]
Thanks for the heads up, I'll fix that.
