### ISSUE TITLE
Support for Zed IDE

### ISSUE THREAD

**Issue by JoseAJnr** [robocorp/robotframework-lsp#1042]
I know that Zed is still a new IDE, but I would love to be able to use the language server on it, like I use on VS Code/PyCharm.

**Comment by fabioz** [comment]
The language server itself is a Python library (https://pypi.org/project/robotframework-lsp/), so, you should be able to pip install it and then it can be initialized with `python -m robotframework_ls.__main__` along with any other needed arg, but there are no plans to specially support Zed (so, given that you can start the language server that way, it's up to Zed itself to come up with the instructions on how to integrate a given language server in it).
