### ISSUE TITLE
VS Code extension does not pickup @action -decorator with argument is_consequential=False

### ISSUE THREAD

**Issue by kariharju** [robocorp/robotframework-lsp#1046]
**Describe the bug**
Using `package.yaml` +  extension v1.17.0 and the template action
method with just `@action` -decoration is shown in the side-panel correctly, but if I add:
`@action(is_consequential=False)` the action is not shown

**To Reproduce**
1. Create action from template
2. Add @action(is_consequential=False) in place of @action
3. Try to run or debug via extension side-panel

**Screenshots**
![image](https://github.com/robocorp/robotframework-lsp/assets/56814402/a171fb03-19d3-4b99-9cba-1efd5711e4ca)

**Versions:**
 - OS: Windows 11
 - Robocorp Code: 1.17.0
 - Action Server: 0.0.24
 - package.yaml:
```yaml 
  - python=3.10.12
  - pip=23.2.1
  - robocorp-truststore=0.8.0
  pypi:
  - rpaframework=28.3.0
  - robocorp=1.6.2
  - robocorp-actions=0.0.7
```

**Comment by fabioz** [comment]
This is now fixed in Robocorp Code 1.18.0
