### ISSUE TITLE
When subitems of a task package are selected it's possible that the work-items aren't shown in the package tree.

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#1053]
To reproduce it's possible to:

1. Create workspace with action and task package
2. Select the action package
3. Select a subitem of the task package directly

At that point the work-items should appear, but they don't.

Note: there was a report where they wouldn't appear even if having just a task package in the workspace (but fixing one should fix the other).

**Comment by kariharju** [comment]
Also happens with just Task Packages:
1. Take template: https://github.com/robocorp/template-python-workitems
2. Open in VS Code -> Work items are visible
3. Run producer step -> Resources panel updates and work item controls disappear
