### ISSUE TITLE
Actions not discoverable when source code contains `'\n'` when printing

### ISSUE THREAD

**Issue by cmin764** [robocorp/robotframework-lsp#1065]
**Describe the bug**
Adding this `'\n'` character during printing makes the Action Package not discoverable by the extension:
<img width="880" alt="Screenshot_2024-04-30_at_1_22_58 PM" src="https://github.com/robocorp/robotframework-lsp/assets/709053/0d04b18e-66c5-4271-ae79-1a551deb6546">

But the same code works if you capture that in a variable:
<img width="996" alt="Screenshot 2024-04-30 at 2 46 46 PM" src="https://github.com/robocorp/robotframework-lsp/assets/709053/e64aed85-65d3-4a7e-99a4-741db74ce10b">

**To Reproduce**
1. Pull the action code from [here](https://github.com/Sema4AI/prebuilt-actions/tree/main/hubspot) and open it in VSCode.
2. Make the change as in the screens above and see if your HubSpot actions are still discoverable or not.

**Expected behavior**
I expect for this to work no matter how I format/refactor my action code.

**Screenshots**
_Placed above_

**Versions:**
 - OS: Mac M1 Sonoma
 - Robot Framework Language Server Version: 1.12.0
 - Robocorp Code: 1.21.0
 - Client Version: VSCode 1.88.1

**Comment by fabioz** [comment]
Oops, sorry, my mistake, you already have `'` there. Let me take a look into the code...
