### ISSUE TITLE
Code-completion for individual parameters for Keywords

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#107]
Right now the language server provides code-completion for Keywords and all parameters are shown at once along with the completion.

The idea going forward is that instead of doing that, only the mandatory parameters would be added, but then, code-completion for individual parameters would be available.

**Comment by mkorpela** [comment]
This is very important for Robot Framework library implementation point of view.
We are currently designing new keywords for our library and one really important part of this is the test development experience. Keyword with a parameter with a default value is designed to have a **sensible** default value.
So in most cases the test developer should not care about it.
And revealing the parameter with the default value by default when autocompleting is not what is wanted.

**Comment by mkorpela** [comment]
As a concrete example: We have been talking about `Click` keyword that clicks on an element.
`Click` could have 7 optional parameters:

1. button (left|middle|right)
2. clickCount
3. delayposition
4. modifiers
5. force
6. noWaitAfter
7. timeout

All having sensible defaults and most library users should not need to change any of those.

When autocompleted now it would be something like this:
`Click  selector  button=left  clickCount=1  delayposition=something  modifiers=None  force=False  noWaitAfter=False  timeout=5000ms`

But we would actually want:
`Click  |` << the last is me mimicking a cursor position
