### ISSUE TITLE
rcc.exe waits for migrated processes to end and take a lot of time to exit

### ISSUE THREAD

**Issue by rakaboy-s** [robocorp/robotframework-lsp#1072]
**Describe the bug**
I have a robot file which has more than 15 tests which takes about 20 minutes to finish. Once the test are completed and report and logs are generated and after that rcc.exe takes about 4-5 minutes to exit the robot and waits for the migrated process to finish.

Here are the logs:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@  From rcc point of view, "actual main robot run" was FAILURE, reason: "exit status 1". See details above.  @@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
**Warning: "rcc.exe" process 20244 (parent 13644) still has running migrated processes:
Warning: + migrated process still running:
Warning: | #11432  "csrss.exe" <leaf -> new parent PID: #11668>
Warning: | #11816  "winlogon.exe" <container -> new parent PID: #11668>
Warning: | |   #6852  "dwm.exe" <leaf under #11816>
Warning: | |   #8448  "fontdrvhost.exe" <leaf under #11816>
Warning: | |   #16016  "LogonUI.exe" <leaf under #11816>**
Note: Depending on OS, above processes may prevent robot to close properly.
Note: Few reasons why this might be happening are:
Note: - robot is not properly releasing all resources that it is using
Note: - robot is generating background processes that don't complete before robot tries to exit
Note: - there was failure inside robot, which caused robot to exit without proper cleanup
Note: - developer intentionally left processes running, which is not good for repeatable automation
So if you see this message, and robot still seems to be running, it is not!
You now have to take action and stop those processes that are preventing robot to complete.
Example cleanup command: taskkill /f /pid 6852 /pid 8448 /pid 11432 /pid 11816 /pid 16016
  |  "Build/Pre-run"  relative time allocation ratio:  1:0
  |  "Setup/Run"  relative time allocation ratio:  7:28034
Warning: More than one user is using same ROBOCORP_HOME location! Those users are: MAIN\452, MAIN\452LA!
Error: exit status 1 (robot run exit)
[rcc] exit status will be: 10!

**To Reproduce**
1. Create a robot file with more than 10 test case
2. Run the robot and observe the exit time for rcc.exe

**Expected behavior**
It should not take 4-5 mitues to exit. Few of the process it wait are from windows like Teams.

**Versions:**
 - OS: Windows 10
 - rpaframework==28.6.1    # https://rpaframework.org/releasenotes.html
 - rpaframework-recognition==5.2.4 # https://pypi.org/project/rpaframework-recognition/
 - allure-robotframework==2.13.5 # https://pypi.org/project/allure-robotframework/

**Comment by fabioz** [comment]
That's not an issue with RCC, it just waits for the program it has spawned/subprocesses to finish (and it can't exit before by design as it has no real idea on what's happening in the spawned process). 

I've seen cases where RobotFramework itself takes that time to generate the logs afterwards. 

I suggest you run your program through a python profiler to see exactly where time is being spent. If it's waiting for some other process to exit you have to kill that process afterwards too.
