### ISSUE TITLE
Environment variables defined in launch.json not being used in individual test case execution

### ISSUE THREAD

**Issue by Alex-Han-Sophos** [robocorp/robotframework-lsp#1074]
**Describe the bug**

Environment variables defined in `launch.json` are used when running the entire robot file, but not individual test cases.

(It feels like a bug, but please let me know if there is any mis-usage on my part. Thanks!)

**To Reproduce**

1. In `launch.json` we define an environment variable like:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "robotframework-lsp",
            "name": "Robot Framework: Launch .robot file",
            "request": "launch",
            "cwd": "^\"\\${workspaceFolder}\"",
            "target": "^\"\\${file}\"",
            "terminal": "integrated",
            "env": {
                "ROBOT_ENV": "variable found! :>"
            },
            "args": []
        }
    ]
}
```
2. Create robot file
```
*** Settings ***
Library     OperatingSystem


*** Test Cases ***
TEST
    ${v}=    Get Environment Variable    ROBOT_ENV    default=variable not found :<
    Should Contain    ${v}    variable found
```
3. I can hit F5 or ctrl-F5 to invoke the debugger to run/debug the file, and the test case in there passes as expected.
4. But if I either click on `Run` or `Debug` button right on top of the test case title, or the `Run Suite` or `Debug Suite` button right on top of the file, the environment variables are not passed and the test would fail.

**Screenshots**

The location of these buttons on the UI: 
![image](https://github.com/user-attachments/assets/460fa0f5-a753-4e89-97e4-fbb7276fc66e)

`Run` via ctrl-F5 vs `Run` test case button:
It looks like the env variables are defined or not defined in the dynamically generated scripts "run_env_*.bat" depending on whether I run suite or test case.
![image](https://github.com/user-attachments/assets/103f8fae-ecbf-4fda-a206-67cd7d07e59f)
![image](https://github.com/user-attachments/assets/40007b3b-8a3e-4c7d-b4a9-c76c538e4ad3)

**Versions:**
 - OS: Windows 11 (reproducible on Ubuntu as well)
 - Robot Framework Version: 7.0.1 (`pip list` shows me `robotframework  7.0.1`)
 - Robot Framework Language Server Version: v1.12.0
 - Client Version: VSCode 1.91.1

**Logs**
No log files found in `C:\Users\<username>\.robotframework-ls\*.log` or `C:\Users\<username>\*_critical.log`

**Comment by sokol1412** [comment]
Hey @Alex-Han-Sophos 

I believe I can help you out here.

If you want to provide robot variables/env variables when executing your test suite/test case via UI buttons, you need to add a separate launch entry in your launch.json file. It will be similiar to your current launch configuration, the only difference is that it needs to be named exactly: "Robot Framework: Launch Template"

You can read more about that in official docs: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-configure-the-launch-from-a-code-lensshortcut

Hope it helps! :)

**Comment by Alex-Han-Sophos** [comment]
@sokol1412 Thanks! Yes, it does help :) This "Robot Framework: Launch Template" config does allow me to define the environment variables for all the UI buttons.

Using this config _instead of_ "Robot Framework: Launch .robot file" can fully meet my use case's needs. However, I do notice that if I try to have both of them like this:
```
    "version": "0.2.0",
    "configurations": [
        {
            "type": "robotframework-lsp",
            "name": "Robot Framework: Launch .robot file",
            "request": "launch",
            "cwd": "^\"\\${workspaceFolder}\"",
            "target": "^\"\\${file}\"",
            "terminal": "integrated",
            "env": {
                "ROBOT_ENV": "variable found"
            },
            "args": []
        },
        {
            "type": "robotframework-lsp",
            "name": "Robot Framework: Launch template",
            "request": "launch",
            "terminal": "integrated",
            "env": {
                "ROBOT_ENV": "variable found"
            },
        }
    ]
}
```
then UI buttons still work (recognizing the env variable) but the F5/ctrl-F5 actions with the debugger does not work anymore, giving me
![image](https://github.com/user-attachments/assets/f875585c-737a-4825-9693-cadb6a0f652f)

Not sure if this is the expected way to combine `launch.json` configurations?

**Comment by Alex-Han-Sophos** [comment]
I guess I could potentially close this as a bug, since there is literally a documented method. But any tip on allowing the usage of both the debugger and the UI buttons would be great! Another rather minor nuisance of above list of two config items is that any time one wants to change the env variable value, it has to be repeated twice.

**Comment by sokol1412** [comment]
I think your issue must be related to cwd/target setting as it works fine for me. Please see my simplified setup below and try adjusting yours accordingly:

```
        // configuration for running via Run->Start Debugging/Run Without Debugging
	{
            "type": "robotframework-lsp",
            "name": "Robot Framework: Launch .robot file",
            "request": "launch",
            "terminal": "integrated",
            "cwd": "${workspaceFolder}/my_tests_repo",
            "target": "${file}",
            "env": {},
            "args": []
        },
        // configuration for running via launch from a code lens or shortcut on opened suite/case
        {
            "type": "robotframework-lsp",
            "name": "Robot Framework: Launch Template",
            "request": "launch",
            "terminal": "integrated",
            "cwd": "${workspaceFolder}/my_tests_repo",
            "target": "${file}",
            "env": {},
            "args": []
        },
```

**Comment by Alex-Han-Sophos** [comment]
Yup, that works! Thanks a lot, @sokol1412!

**Comment by Alex-Han-Sophos** [comment]
Closing. No source code fix needed. Solution from @sokol1412 above works great.
