### ISSUE TITLE
Please Deprecate Robot Framework Language Server in VSCode Marketplace

### ISSUE THREAD

**Issue by Snooz82** [robocorp/robotframework-lsp#1076]
Hey @fabioz ,

I hope you are well!

I have a important request:
Can you please deprecate the extension in the VSCode Marketplace?
New people are still coming to this extension and raise issues here.

We also had a talk with other community members and the mutual agreement is that this shall be deprecated.
Due to the existence of RoboCode there is also no one interested to take over the LSP project/source code.

You can deprecate it leaving a comment here:
https://github.com/microsoft/vscode-discussions/discussions/1

We would highly appreciate that. (or start maintaining it again and update it to RF 7 ;-) )

Kind regards
René
-Chairman of Robot Framework Foundation-

**Comment by kariharju** [comment]
@Snooz82 please redact the deprecation request to the marketplace asap.

We have a significant amount of enterprise level customers running on this extension, so this extension will not be deprecated without our SLA decision.

**Comment by Snooz82** [comment]
Done.

Hi @kariharju 

RoboCorp promised an open communication to the community.

In my opinion an open communication would be to lead new users to RobotCode with a disclaimer or so on the start page of the extension.
Or at least bring a message to users using Robot Framework 7.x that they should switch.

What are your plans to improve the information flow to the users?

regards
René

**Comment by Snooz82** [comment]
@kariharju 
any news?

**Comment by sahokas** [comment]
Hello @Snooz82,

Thanks for bringing this to our attention.

We have added a maintenance policy to the README ([link](https://github.com/robocorp/robotframework-lsp/tree/master/robotframework-ls#maintenance-policy)), which clarifies our position on the matter. We'll make sure this statement gets updated to VS Code Marketplace in a timely manner.

We believe that a diverse range of tools ultimately benefits the entire community, and thus will not endorse any specific extension.

Regards,
Sampo
