### ISSUE TITLE
Problem running hover evaluation on the Robot Framework Debug Adapter during debug mode

### ISSUE THREAD

**Issue by RalphS1S** [robocorp/robotframework-lsp#1082]
**Describe the bug**
The error is related to the internal implementation of the Robot Framework Debug Adapter in VSCode. The hover evaluation functionality attempts to evaluate an expression in the code but appears to incorrectly access an attribute of the UserKeywordRunner object.
When running the automation through Launch, the test does not complete and ends without generating a log when attempting to connect to the database.

**To Reproduce**
1. Start the automation using the Launch Template.
2. Observe the execution at the end.

**Expected behavior**
When executing the automation using the Launch Template, the test completes successfully and generates an accurate log.

**Screenshots**
![image](https://github.com/user-attachments/assets/95540111-9ee1-4fd1-baf2-45eea9ba12b5)
![image](https://github.com/user-attachments/assets/64d77722-d2ed-4a68-8225-b64350676d24)
![image](https://github.com/user-attachments/assets/404265db-6e50-4682-8b88-d21f9a9e2e66)

**Versions:**
 - OS: [Windows 11 Pro]
 - Robot Framework 7.1.1 (Python 3.12.7 on win32)
 - Robot Framework Language Server Version: [1.12.0]
 - Client Version: [VSCode 1.94.2]

**Logs**
robot: 2024-10-25 09:03:41 UTC pid: 9492 - MainThread - EXCEPTION - robotframework_debug_adapter.debugger_impl
Error on hover evaluation: Consultar agendamento cadastrado

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotframework_debug_adapter\debugger_impl.py", line 581, in _do_eval
    ctx.namespace.get_runner(self.expression).longname
AttributeError: 'UserKeywordRunner' object has no attribute 'longname'

**Comment by fabioz** [comment]
Closing as this is related to RF 7.

See: https://github.com/robocorp/robotframework-lsp/issues/1051 for details (PRs welcome).
