### ISSUE TITLE
Please specify required robotframework-seleniumlibrary version

### ISSUE THREAD

**Issue by doyou89** [robocorp/robotframework-lsp#109]
**Describe the bug**
cannot create lineno for classes of robotframework-seleniumlibrary 4.3.0.
robotframework-seleniumlibrary 4.4.0 need.

**Expected behavior**
robotframework-seleniumlibrary version requirements is specified in README.md

**Versions:**
 - Python : 3.7 & 3.8
 - Robot Framework Version : 3.2
 - Robot Framework Language Server Version : 0.3
 - Client Version : VSCode 1.46

**Comment by fabioz** [comment]
Agreed... I think that we should even verify that in runtime to check that it's valid, given that it's such a popular library.
