### ISSUE TITLE
Distribute without relying on installed python?

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#11]
In the future we could use pyoxidizer or pyinstaller to start-up the extension without any dependency.

Right now we depend on the user to configure the path to the python executable to use and we use that python executable to start the extension.

This isn't ideal as the extension itself has to support and run in that environment (so, for instance, we need to support Python 2.7). 

So, the option here would be creating an executable per OS that we'd like to support (using pyoxidizer or pyinstaller) which would start up the python process for us and would call our initial code and then we could put the remainder of the code in a .zip shared for all the platforms.

The downside is that the distribution would be a bigger download, but we wouldn't need to rely on anything else and it would be possible to support only the latest version of Python.

**Comment by bollwyvl** [comment]
Ease of install is swell... but to be a daily driver more capable than the status quo, finding and being able to jump to user-installed `Library`s sounds... hard... if you're not part of the `sys.prefix` where they live. 

I'll also humbly suggest the [constructor](https://github.com/conda/constructor)-driven [MiniRobot](https://github.com/robots-from-jupyter/robotlab/blob/master/constructor/MiniRobot/construct.yaml.in) as another solution to distributing even complex dependencies across a number of platforms.

**Comment by bollwyvl** [comment]
Oh, and please also distribute on `pip`!

**Comment by fabioz** [comment]
The idea is that there will be the language server and a separate process(es) (after https://github.com/robocorp/robotframework-lsp/issues/14 is done) where it'll load `robotframework` and it'll communicate with that shell to get `robotframework` specific information.

I created https://github.com/robocorp/robotframework-lsp/issues/17 to address `pip` distribution.

**Comment by bollwyvl** [comment]
Thanks for the `pip` issue!

Sure: some of the existing language servers are multi-process, usually done to increase performance with a pool, referring to the language _server_ and the language _service_. Seems like a fine idea here: heck, if it allows you to write modern python in a runtime you control while supporting legacy/enterprise stuff, it's definitely worth it!

**Comment by fabioz** [comment]
I'm closing this issue for now to shorten the the backlog.

Note: I'm marking things that may be done later with the `maybe later` tag so that it's searchable in the future (so, this is closed as there are no plans to tackle it in the short/mid term -- it can be reopened if someone provides a pull request or if higher priority items are no longer available).
