### ISSUE TITLE
Improve python packaging for dowsntreams

### ISSUE THREAD

**Issue by bollwyvl** [robocorp/robotframework-lsp#123]
Congratulations on `0.3.1`! The progress towards debugger is very exciting!

**Is your feature request related to a problem? Please describe.**

I would like to package `robotframework-lsp` for [conda-forge](https://github.com/conda-forge/staged-recipes), mostly as a prelude to inclusion in an yet-to-be-started [robotlab](https://github.com/robots-from-jupyter/robotlab) version, and for testing, using, and promoting inside [jupyterlab-lsp](https://github.com/krassowski/jupyterlab-lsp).

**Describe the solution you'd like**

I will work up a PR that gets it into a more packageable state, namely such that the pypi-published `sdist` contains:
- All the files licenses, including the full text of the Apache license, in-tree
- The readme, which is also read at `sdist` time, in-tree
- all the these files included in a MANIFEST.in
- the version dependencies on `robotframework` (and whatever else is needed) defined
- an `extras` section for the pin on `robotframework-seleniumlibrary`

I imagine this will be relatively lightweight, simply checking to see if the files in question are in-place or not during setup, and copying them from their canonical repo locations. symlinks would be lovely, but windows...

**Describe alternatives you've considered**

I've been able to patch stuff and pull extra sources to [make a local version work](https://github.com/bollwyvl/staged-recipes/blob/robotframework-lsp-031/recipes/robotframework-lsp/meta.yaml), but these patches get brittle to maintain over time.

Thanks!

**Comment by fabioz** [comment]
Seems a nice inclusion for me ;)

Please let me know if you need anything on my side.

**Comment by bollwyvl** [comment]
Thanks for the quick reply! #124 is open, and looking good locally, though I must confess I didn't run all your tests :blush:. That's what the robots are for, right? I'll of course be happy to take any review feedback, but certainly feel free to just make the changes... it's your baby!

If these land in the next release, I'll be able to get it up on conda-forge in a day or two thereafter... of course, not demanding a release, just for these little things!

These are super-boring chores, and I know you guys aren't _really_ looking to support random-joe-off-the-street installing from pypi when you have a nice integrated solution, so I really appreciate your dedication to this work... and open sourcing it in the first place!

**Comment by fabioz** [comment]
I've just merged it.

Thank you for the improvements and for setting things up in conda-forge.

As a note, the actual steps needed for a release should be in: https://github.com/robocorp/robotframework-lsp/blob/master/.github/workflows/release-robotframework-lsp.yml

In particular, one needs still needs to do: `python -m dev vendor-robocode-ls-core` before doing `python setup.py sdist bdist_wheel --universal` (which mostly does a `copytree` from the sources from `robocode-python-ls-core` to the proper place in `robotframework-ls`) -- is this a problem with the `conda-forge` integration?.

**Comment by bollwyvl** [comment]
Great!

Haven't looked over the history that actually landed, but if it's mostly
like the PR, all files should (sort of by definition) be in place in the
sdist to create a working install... Or another sdist. Anyhow, we just
build from the sdist,
which I had already tested as a conda recipe.

I'll let you know when I start up the process. If interested, I can invite
you to co-maintain... It's a very small responsibility (usually just
pressing a button) and it's always good to have an upstream maintainer.

**Comment by fabioz** [comment]
Humm, I'm not sure... I just did some pretty minor changes to always copy the files over (even if they're already there, just in the case they're stale), but I don't see any change to copy over the vendored files.

Feel free to invite me as a co-maintainer ;)

**Comment by bollwyvl** [comment]
Just gave this a spin locally with master, and everything looks on the up-and-up. Hooray! Once the next release drops we'll be able to move forward.

**Comment by bollwyvl** [comment]
[Recipe is on staging](https://github.com/conda-forge/staged-recipes/pull/12548)! @fabioz (and anybody else from this project who is interested!) please comment on that PR if you'd like to be added as a maintainer!

Follow-on: should we go ahead and get `rpaframework` up there?
