### ISSUE TITLE
Publish Robot Framework Language Server on https://open-vsx.org/

### ISSUE THREAD

**Issue by Snooz82** [robocorp/robotframework-lsp#132]
**Is your feature request related to a problem? Please describe.**
When using VSCodium since they change the Marketplace to open-vsx.org you do not fing the LSP anymore.
https://open-vsx.org/

**Describe the solution you'd like**
Publish the releases of vscode extension also there.

**Describe alternatives you've considered**
No real alternative... ;-)

**Comment by fabioz** [comment]
I've done a manual release for now (and it seems to have worked: https://open-vsx.org/extension/robocorp/robotframework-lsp).

I'll leave this open to automate when I do the next release (I've already created the `OPEN_VSX_TOKEN` secret, so, it should be a matter of calling `npx ovsx publish <vsix_filename.vsix> -p <OPEN_VSX_TOKEN>` during the release).

**Comment by fabioz** [comment]
Publishing from the ci now.
