### ISSUE TITLE
Importing a python library with capital letters fails

### ISSUE THREAD

**Issue by anton264** [robocorp/robotframework-lsp#143]
**Describe the bug**
Importing a python library with capital letters fails

**To Reproduce**
1. Create python file with keywords, name the file and the class with capital letters anywhere in the file
2. Import the file in RF with `Library     myLibrary.py`
3. Keyword completion will fail
4. Running tests still works so RF accepts this syntax.

**Expected behavior**
Keyword completion should work regardless of letters in python class/file. Python naming conventions state that: "Class names should follow the UpperCaseCamelCase convention" [https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html](source)

**Screenshots**

**Versions:**
 - OS: Linux/Fedora
 - Robot Framework Version 3.2
 - Python 3.8.3
 - Robot Framework Language Server Version 0.3.2
 - Client Version: VSCode 1.46

**Comment by fabioz** [comment]
Can you provide a sample `.robot` and a sample `.py` file with that use case? (Just to be sure that I'll actually tackle your actual problem when checking this issue).

**Comment by anton264** [comment]
![2020-09-15_07-10](https://user-images.githubusercontent.com/10194266/93168254-b40e3480-f722-11ea-80fe-5e67ffd22269.png)

Py:
`class myPythonKeywords(object):
    ROBOT_LIBRARY_VERSION = 1.0
    def __init__(self):
        pass

    def Uppercase_Keyword (self):
        return "Uppercase does not work"`

Working py:
`class otherpythonkeywords(object):
    ROBOT_LIBRARY_VERSION = 1.0
    def __init__(self):
        pass

    def Lowercase_Keyword (self):
        return "Lowercase works"`
Robot:
`*** Settings ***
Library    otherpythonkeywords.py
Library    myPythonKeywords.py

*** Test Cases ***
Test
    Lowercase Keyword
    Uppercase Keyword`
