### ISSUE TITLE
Show debug log in vscode when running tests.

### ISSUE THREAD

**Issue by anton264** [robocorp/robotframework-lsp#144]
**Is your feature request related to a problem? Please describe.**
Running tests in vscode is a great feature that I have long been waiting for. However it is hard to see exactly what the tests are doing since the debug console only outputs stdout from robot and not with the same detail as in the terminal.

**Describe the solution you'd like**
Showing the debug log from robot in the debug console would help the test developer to see exactly what the tests are currently doing and judge if they might be stuck somewhere.

**Describe alternatives you've considered**
An even better option would be a solution like the old RED plugin for eclipse where stdout and debug is shown side by side.

**Comment by fabioz** [comment]
The debug log is now shown in the debug console.

Also, the `ROBOT OUTPUT` view which should provide even more insight on what's actually happening, so, the visibility issue on what's happening should be taken care of even without the debug console ;)
