### ISSUE TITLE
Write robot log even when tests are interupted

### ISSUE THREAD

**Issue by anton264** [robocorp/robotframework-lsp#145]
**Is your feature request related to a problem? Please describe.**
If i'm running a suite with 15 tests and the first test fails on a common step that all tests will fail on it is no point for me to keep running the next 14 tests. When running in terminal i can just hit ctrl+c and robot will write the log from the first test that i can examine. If I interupt the suite when running from vscode the session will  be killed ungracefully and robot can not write its log which makes it harder for me to pinpoint the problem

**Describe the solution you'd like**
Interupting the tests in vscode should always write the standard robot log.

**Comment by fabioz** [comment]
In the last release (0.28.0) the default run is done in the internal vscode terminal (and you can also configure existing runs to use the internal vscode terminal), so, you can use `Ctrl+C` to have the robot log (the terminate button is still a forceful terminate, but as the terminal already provides the needed functionality, no additional effort should be needed).
