### ISSUE TITLE
Properly use get_resource_model or get_model

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#15]

**Comment by fabioz** [comment]
@pekkaklarck I was thinking a bit about this... do you think it'd make sense to have some api in `robotframework` itself to automatically identify which API (`get_resource_model` or `get_model`) should be used?

**Comment by pekkaklarck** [comment]
Could be done but I'm not certain would it help. If someone has written e.g. 

```robotframework
*** Settings ***
Test Setup      Example
```

and keeps writing more, it's not really possible to tell is it going to be a test case file or a resource file. If `*** Test Cases ***` is added later, it's a test case file and previous content is valid. If not, it's a resource file and ` Test Setup` is invalid.

**Comment by pekkaklarck** [comment]
I got a feeling IDEs should use heuristics like this:

- Open `*.robot` files expecting them to be test case files by default. Use `get_model`.
- If a `*.robot` file is imported from another file as a resource, open it as a resource file. Use `get_resource_model`>.
- Open `*.resource` files always as resource files. Use `get_resource_model`.

It seems to me that in none of the above cases an API to autodetect the file type would help. Do you have examples where it would be useful?

**Comment by fabioz** [comment]
Well, it's not uncommon for users starting to have an untitled (unsaved) file in memory... in this case the user may just ask to use robotframework language and we'll have to guess without any backing info (we only have the source code and we have to guess from that).

My plan was just checking for a `*** Test Cases ***` section (using some regexp) and then using `get_model` if it's available and `get_resource_model` if it's not, but from your description `get_model` is more restrictive (i.e.: if the user is writing a resource it'd say that `Test Setup` is invalid), so, I'm not sure what would be the best approach here... do you have some suggestion?

**Comment by pekkaklarck** [comment]
No, `get_resource_model` is more restrictive. It doesn't allow settings that are valid only in a test case file (e.g. `Test Setup`), and in the future it may also consider `*** Test Cases ***` sections invalid. At the moment that check is done later, but arguable the parser should detect all this kind of errors.

That's why I think it's better to use `get_model` when you don't know the type of a file. You can know it's a resource file if it's imported somewhere as a resource or if it has a `*.resource` extension.

**Comment by fabioz** [comment]
It seems I misread the restriction, sorry about that...

Ok, if `get_model`is a superset of `get_resource_model`, then for now I'll only use `get_model` as is currently (knowing that a model is imported from another model is not a trivial information to compute, so, it may take a while to get to that part).

I can probably already start handling `.resource` files and use `get_resource_model` in that particular use case though... still, if the only difference is from the valid sections available, maybe it'd make sense to just have `get_model` and have an additional function as `collect_resource_errors(ast)` which would traverse the ast and collect errors from invalid sections instead of doing that during the ast construction... what do you think?

**Comment by pekkaklarck** [comment]
Could you clarify that a bit?

**Comment by fabioz** [comment]
Well, the syntax `.robot` and `.resource` files seems to be the same (and from what I understand until now, the only difference is in the valid tokens for some sections).

So, that could be done as a second step by traversing the AST gotten from `get_model()` and generating errors accordingly for wrong sections instead of using `get_resource_model()`.

**Comment by pekkaklarck** [comment]
It could be done but it would require quite big changes to the parsing/lexing logic. Would the be big benefits for you compared to, for example, first using `get_model` and then parsing the same data again with `get_resource_model` if the file is a resource?

```python
model = get_model(data)
if not model.has_tests:
    model = get_resource_model(data)
```

**Comment by pekkaklarck** [comment]
Another thing to remember is that for user it would be fine to parse all files using `get_model` at least in the beginning. Not getting a notification that e.g. `Test Setup` isn't allowed in a resource file wouldn't be a big issue. Later files that are known to be resources (they are imported as resources or have `*.resource` extension) could be parsed (possibly re-parsed) with `get_resource_model`. I'm fairly certain we wouldn't need anything more complicated even in the longer run.

**Comment by fabioz** [comment]
Seems good to me ;)

**Comment by fabioz** [comment]
Note: I've removed from the milestone until we can identify that a file is imported from another file to be considered a resource.

**Comment by fabioz** [comment]
I'll close this and wait for a specific feature where we actually need this.
