### ISSUE TITLE
Distribute robotframework-lsp in pip

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#17]

**Comment by Snooz82** [comment]
Hi @fabioz,
i think now could be the time to upload it to PyPi.org.
i think you made the MvP and people could start using it.

thanks!

**Comment by fabioz** [comment]
Agreed. I'll do that for the next release.

**Comment by fabioz** [comment]
Done for 0.0.8 (already available through `pip install robotframework-lsp`).
