### ISSUE TITLE
Ctrl+Click for html file should open it in browser instead of opening it in an editor

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#170]
Apparently this is now possible with `registerTerminalLinkProvider` (https://code.visualstudio.com/updates/v1_49).

**Comment by fabioz** [comment]
References:

https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aintegrated-terminal-links
https://github.com/microsoft/vscode/issues/91290

**Comment by fabioz** [comment]
Reference for Debug Console: https://github.com/microsoft/vscode/issues/108853

**Comment by chemstar** [comment]
However it seems to work now out of the box.

**Comment by fabioz** [comment]
Yes, in the internal vscode terminal it seems to work out of the box, so, closing this issue (launching in the terminal is now the default, so, there's nothing else to be done).
