### ISSUE TITLE
Robocorp Code 0.2.0: env.json not picked up with the latest release (regression?)

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/robotframework-lsp#171]
Robocorp Code 0.2.0: `env.json` not picked up with the latest release (regression?)

**Comment by fabioz** [comment]
Is this wit the `Run Robot` or the regular `Robot Framework` launch?

**Comment by fabioz** [comment]
I seem to be able to reproduce it with the `Run Robot` but not with the `Robot Framework` launch (given that this is actually a new feature added in the last release this probably never worked).

It seems that rcc doesn't pick that up automatically, so, I'll change it to pass it in the command line.
