### ISSUE TITLE
Update command name: Robocorp: Log in Robocloud -> Robocorp: Log in Robocorp Cloud

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/robotframework-lsp#180]
Update the log in command name:

`Robocorp: Log in Robocloud` -> `Robocorp: Log in Robocorp Cloud`

**Comment by fabioz** [comment]
That's actually done in the latest version of the extension (0.4.0):

![image](https://user-images.githubusercontent.com/117621/98661718-9544ac80-2325-11eb-8222-7000996cf6ea.png)
