### ISSUE TITLE
Provide the `standard` robot template as the first option when creating a robot

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/robotframework-lsp#181]
Robocorp Code extension returns the new robot template names in alphabetical order (`extended`, `python`, `standard`).

The `standard` template (previously `minimal`) is the one that should be promoted as the default one (as the first option). This is the same template that Robocorp Lab uses when creating a new robot.

If possible, provide the `standard` template as the default option so that the user does not need to select anything unless they really want to (pressing `Enter` should be enough for accepting the default option).

**Comment by fabioz** [comment]
Note: I also added some additional description.

The current UI is:

![image](https://user-images.githubusercontent.com/117621/99147076-8e3ad880-265c-11eb-980f-c077f6cf9d4a.png)

(please let me know if something should be changed there)
