### ISSUE TITLE
Provide a button to show available robocorp commands

### ISSUE THREAD

**Issue by vermario** [robocorp/robotframework-lsp#182]
After installing the extension, there are no visible changes in the UI. Adding a button in the toolbar could improve the visibility of the feature, and help out users to understand what they can do with the extension.

I noticed that the [Remote containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension adds a button ( "Quick Access" status bar item) in the lower left corner that shows the available commands for that extension when you click it. I'm thinking that a similar button with the Robocorp icon there could be a good improvement to help users find the available commands.

Here's a gif of how the button works:

![vscode_command_button](https://user-images.githubusercontent.com/185412/98642933-ea3cee80-2336-11eb-9c81-87e83c019183.gif)

**Comment by fabioz** [comment]
I'm closing this for now as we're currently investigating what would be the best approach.
