### ISSUE TITLE
Add a 'Launch Robot task' command under the 'Create a launch json file' palette

### ISSUE THREAD

**Issue by uxpetr** [robocorp/robotframework-lsp#184]
Currently setting up a robot run configuration requires adding the configuration to the launch.json file. Adding a 'Launch Robot task' command shortcut to the 'Create a launch json file' palette would help to streamline the process and make it less error-prone.

<img width="616" alt="Default" src="https://user-images.githubusercontent.com/54584203/98673640-4ec07380-2360-11eb-81dc-f1d5ce53440d.png">

**Comment by fabioz** [comment]
I researched into this and it seems like this is a bug in VSCode itself when the `launch` section is still not present in the related launch.json or workspace json (the extension is adding a snippet for that already and as far as I understand it, the fact that it's not appearing there is a bug in VSCode).

I created a report for that at: https://github.com/microsoft/vscode/issues/110334

**Comment by fabioz** [comment]
It seems I had a misunderstanding on how it should work there.

This should be fixed in the repo now.
