### ISSUE TITLE
Improve integration with the python extension for autocomplete when coding robots in python

### ISSUE THREAD

**Issue by vermario** [robocorp/robotframework-lsp#185]
When developing python robots, the editor is not aware of the conda environment, so autocomplete features are not available.

Using the official Python extension requires the user to select the interpreter: this is currently made quite hard because all environments are identified by long ids, and the "current" one is not easily selectable.

![image](https://user-images.githubusercontent.com/185412/98675847-77963800-2363-11eb-8f4c-e783fc4e7c22.png)

This problem could be solved by automatically setting the environment when the conda environment is created/updated, if feasible.

**Comment by fabioz** [comment]
I created an action:

`Robocorp: Set python.pythonPath configuration (used by the Python extension) based on robot.yaml`

to help here.

Note that it's not doing anything automatically right now (as there are plans to create a custom tree view we can use it to make it more visible in the future).
