### ISSUE TITLE
"Log in Robocorp Cloud" credentials need to be used with --account flag

### ISSUE THREAD

**Issue by kariharju** [robocorp/robotframework-lsp#188]
**Describe the bug**
Currently VsCode is not giving and using a defined account name when using rcc credentials.
This means VsCode credentials are stored using the default name: "Default account".
When using the credentials if the account name is not given rcc will use the account set as default.
Problem comes when Robocorp Lab and Code co-exist in the same machine and Lab is unlinked.
NOTE: That this is due to lack of specs, so I should probably be the one to fix this :D

**To Reproduce**
1. Setup and Link Robocorp Lab
2. Setup and Link Robocorp Code
3. Unlink Robocorp Lab
4. Try to `Upload robot to Robocorp Cloud` from Code

The problem is visible in the config file `~/.robocorp/rcc.yaml` where the Lab account has been deleted and we see the "Default account" but the default: section does not point to that.

**Expected behavior**
The upload should still work because Code has made separate credentials.
...but it fails because without stating the `--account RobocorpCode` the Code is actually using the Lab account credentials which were cleared in Lab unlink.
There might also be some cache problem as in this case we still see some workspace listing even tough the Cloud connection is severed.

So Code should state the --account RobocorpCode when setting the credentials and when using them to avoid the mixup between other credentials on the same machine. This way Code is always using it's own account and does not care about the default account system (originally built for CLI).
Current implementation works if Code is alone as the first credential given to rcc is made the default account.

**Comment by fabioz** [comment]
I created https://github.com/robocorp/robotframework-lsp/issues/189 related to the caching issue.
