### ISSUE TITLE
Robotframework LS keeps a lot of files open when vendored watchdog is used

### ISSUE THREAD

**Issue by xylix** [robocorp/robotframework-lsp#190]
**Describe the bug**
Robotframework LS seems to be leaking file handles in some situations in macOS. This has happened to me previously, and now it reappeared on a different macOS install. After it starts leaking file handles this problem seems to persist until a restart. This might be a problem with macOS not freeing the old file handles, but I'm unsure of this.

This happens to me running the LS using CoC-nvim as the LSP client. I can also try to reproduce with other editors if that would be useful for debugging.

**To Reproduce**
Open any robot file, try to trigger any LS feature (for example tab completion. 

**Expected behavior**
LS works as usual

**Screenshots**
```
lsp: 2020-11-13 13:32:33 UTC pid: 49123 - MainThread - EXCEPTION - robocorp_ls_core.basic
Error calling: ['ps', '-p', '49126', '-o', 'stat'].

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/robotframework_ls/vendored/robocorp_ls_core/basic.py", line 128, in is_process_alive
    process = subprocess.Popen(
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 825, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1589, in _get_handles
    c2pread, c2pwrite = os.pipe()
OSError: [Errno 23] Too many open files in system

```

**Versions:**
 - OS: macOS catalina 10.15.7 (19H15)
 - Python 3.9
 - Robot Framework Version 3.2.2
 - Robot Framework Language Server Version 0.5.0
 - Client Version :
  - coc.nvim version: 0.0.79-cc975fd0ca
  - node version: v14.15.0
  - vim version: NVIM v0.5.0-nightly-193-g35325ddac

**Logs**

[robotframework_ls.lsp.49123.log](https://github.com/robocorp/robotframework-lsp/files/5546369/robotframework_ls.lsp.49123.log)

Sometimes when I reproduce this problem, some log files don't get correctly written (probably related to the file handle problem). I'll try to get the other log files but it might be a bit difficult.

**Comment by fabioz** [comment]
I tried it locally and couldn't really find any leak here (although I don't have a Mac, only Windows, so, I tried tracking the open resources here, but everything seems to be properly opened/closed and I couldn't find a leak)... 

Do you think you can provide a list of the open file descriptors on the related python processes when this happens?

From:
https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1

it seems that it's possible to see the pids with the most open files with:

`lsof -n +c 0 | sed -E 's/^[^ ]+[ ]+([^ ]+).*$/\1/' | uniq -c | sort | tail`

(although please try other things if that particular one doesn't work -- I haven't really tried it here)

And the post https://stackoverflow.com/questions/20974438/get-list-of-open-files-descriptors-in-os-x  seems to provide a way to see which files are open.

**Comment by xylix** [comment]
While reproducing and running this lsof command on watch, I got a result of 49000 file handles open, and then the `watch lsof` process crashes (presumably it needs file handles to run).


**49187 78566**

78566   ??  S      0:02.88 /usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python -u /usr/local/lib/python3.9/site-packages/robotframework_ls/server_api/server__main__.p

I also got the other logs while reproducing.

[robotframework_l.s_file_handle_bug_logs.zip](https://github.com/robocorp/robotframework-lsp/files/5546833/robotframework_l.s_file_handle_bug_logs.zip)

```

Also I figured out that this _only_ happens on python 3.9 on my machine. With python 3.8 the LSP works fine. This would also explain why some of my virtualenvs have had this problem and some not, because some project virtualenvs have different python versions.

**Comment by fabioz** [comment]
Is it possible for you to get a list of the open handles before it crashes? (potentially raising the max number of handles temporarily)

I think having that list would help quite a bit in diagnosing it.

**Comment by xylix** [comment]
Ohhh right. I now did just that, and I think that made this problem way clearer.

[lsof_robotframework_ls.log](https://github.com/robocorp/robotframework-lsp/files/5551933/lsof_robotframework_ls.log)

It seems the robotframework_ls process is looking through node_modules and other huge files in subfolders of the project I'm working on. The amount of files I have in folders Browser/wrapper and node_modules. If the LSP is opening these files and for some reason not closing them even though they are not python that would explain some of this issue. Altough the fact that this only happens on python 3.9 for me is still quite weird

```
 ~/C/robotframework-browser (node-browser-packaging)> find Browser/wrapper/ | wc -l
    5608
 ~/C/robotframework-browser (node-browser-packaging)> find node_modules/ | wc -l
   34218
 ~/C/robotframework-browser (node-browser-packaging)> find venv/ | wc -l
   10084
 ~/C/robotframework-browser (node-browser-packaging)>
```

**Comment by fabioz** [comment]
Do you by any chance have `watchdog` installed under the env in Python 3.9 and not in the env in Python 3.8?

The language server does indeed trace changes (recursively) under the folders in the PYTHONPATH/workspace folders so that it can auto-update the spec files.

In this case apparently you have the `node_modules` under the workspace, so `watchdog` listens for those changes... a version of `watchdog` is sent along with the project as a fallback, and this version doesn't have any compiled dependencies, so, it ends up resorting to doing a poll for the changes, but I think what's happening in this case is that you have watchdog installed (with its binary deps) in your env, so, it picks up that version instead and as it has the binary deps in place it uses file-system resources for the files tracked.

The library doesn't really provide an API to say that we only want to track files of a given extension (which is why it ends up consuming resources even for files we don't care about).

Give that the number of files being tracked is based on the number of files in the workspace, I suggest you just raise the limit on the max number of files for now (https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1).

The proper fix would probably be fixing watchdog to have an API which allows some folders/files to be excluded when recursively listening for changes.

**Comment by fabioz** [comment]
The related watchdog issue is: https://github.com/gorakhargosh/watchdog/issues/212

**Comment by xylix** [comment]
Hm interesting. If extension based filtering is not possible would it be possible to exclude subdirectories based on .gitignore info? I think that's what some LSP's already do. However I have no idea how that would work in different editors.

At least my global 3.9 environment which reproduces this problem does not have watchdog installed. 
```
 ~> pip3 list
Package            Version
------------------ -------
pip                20.2.4
robotframework     3.2.2
robotframework-lsp 0.5.0
setuptools         50.3.2
wheel              0.35.1
 ~>
```
The 3.8 venv that works correctly does have watchdog.

It seems like installing watchdog in the global pip3 fixed this problem on the global interpreter as well.

**Comment by fabioz** [comment]
Humm, so, it's the other way around, if you have it installed it works and if you don't (when it relies on the polling) it doesn't.

Seems nice -- i.e.: install native watchdog and have it work then ;)

**Comment by xylix** [comment]
Yeah that works as a workaround for my use.

I think these reserved file handles can also happen on other platforms, I've heard internal Robocorp user report that this problem has happened on windows as well, in Robocorp Lab.

Should we keep this issue open, or document the workaround somewhere or something? This could happen other users as well.

**Comment by fabioz** [comment]
Well, watchdog doesn't have an API for a simple fix (it has no API to ignore anything when listening for recursive changes). 

Still, I have to investigate more (having it consume all these resources in poll mode may be a watchdog bug).

Another option could be not relying on its recursive features and only track individual folders (which would give us the flexibility to decide which folders to track)... the only downside is the additional work to make that work (keeping that consistent isn't that straightforward), and I don't know whether we'd miss internal optimizations watchdog itself may have.

I agree that using .gitignore info to decide what not to track is something interesting.

So, let's leave this open for now.

**Comment by fabioz** [comment]
As a note, watchdog actually has a note saying:

```
Note that when using watchdog with kqueue, you need the number of file descriptors allowed to be opened by programs running on your system to be increased to more than the number of files that you will be monitoring. The easiest way to do that is to edit your ~/.profile file and add a line similar to:

ulimit -n 1024

This is an inherent problem with kqueue because it uses file descriptors to monitor files. That plus the enormous amount of bookkeeping that watchdog needs to do in order to monitor file descriptors just makes this a painful way to monitor files and directories. In essence, kqueue is not a very scalable way to monitor a deeply nested directory of files and directories with a large number of files.
```

Which seems to be the issue in this case.

**Comment by fabioz** [comment]
I was going to fix this by sending the needed Mac OS binaries along, but when doing that Mac OS builds started failing on the CI as it seems that the current watchdog version is actually broken there (so, the fix to use the version with the binaries may end up making other things fail as it is not properly tracking filechanges changes on some cases).

I created https://github.com/gorakhargosh/watchdog/issues/706 to track it there.

**Comment by fabioz** [comment]
It seems that the previous version of watchdog (0.10.3) works properly, so, I'm distributing that version with the binary dependencies now to fix this issue.

**Comment by xylix** [comment]
Okay great. Thanks!

**Comment by bitcoder** [comment]
Hi everyone, just to let you know that I've faced this same issue, when running robotframework in tcp mode (only on that case). I tried raising the ulimit but it didn't solve it. After installling watchdog 2.0.2 , the problem went away.

`pip3 install watchdog`

**Comment by fabioz** [comment]
Another option would be using polling instead of native file-watching.

i.e.: https://github.com/robocorp/robotframework-lsp/issues/238#issuecomment-789867965

```
By default the language server will still use watchdog, but now it's also possible to set an environment variable:

ROBOTFRAMEWORK_LS_WATCH_IMPL=fsnotify

to force the usage of polling.
```
