### ISSUE TITLE
VS Code:  Formatting does not do anything to .robot files

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/robotframework-lsp#217]
The code auto-formatting on file save stopped working for `.robot` files for me.

I am not sure what I did to break it, or if LSP is even responsible for the formatting, or if I have accidentally removed some formatter somewhere, or maybe removed some extension that was handling the formatting.

This happens for me in the latest VS Code (1.52.1, macOS) with the latest LSP (0.6.3) and Code (0.5.3) extensions.

I deleted the logs, restarted VS Code, and then modified a `.robot` file, finally saving the file. I have the "format on save" enabled in VS Code. Attached are all the logs I found.

[robotframework_ls.zip](https://github.com/robocorp/robotframework-lsp/files/5707430/robotframework_ls.zip)

**Comment by janipalsamaki** [comment]
Tried updating `conda.yaml`. Got this notice that I have not seen before (attached).

<img width="281" alt="vs-code-update-conda-yaml-formatter-notice" src="https://user-images.githubusercontent.com/1157184/102453916-d5dec680-4045-11eb-8f8b-dd6754c0511c.png">

**Comment by janipalsamaki** [comment]
Some maybe useful snippets from the logs:

```
lsp: 2020-12-17 08:57:57 UTC pid: 40432 - MainThread - DEBUG - robocorp_ls_core.jsonrpc.streams
Read: {"jsonrpc":"2.0","id":5,"method":"textDocument/formatting","params":{"textDocument":{"uri":"file:///Users/janipalsamaki/Projects/demo-robot/tasks.robot"},"options":{"tabSize":4,"insertSpaces":true}}}

lsp: 2020-12-17 08:57:57 UTC pid: 40432 - MainThread - DEBUG - robocorp_ls_core.jsonrpc.endpoint
Handling request from client {'jsonrpc': '2.0', 'id': 5, 'method': 'textDocument/formatting', 'params': {'textDocument': {'uri': 'file:///Users/janipalsamaki/Projects/demo-robot/tasks.robot'}, 'options': {'tabSize': 4, 'insertSpaces': True}}}

lsp: 2020-12-17 08:57:57 UTC pid: 40432 - MainThread - DEBUG - robocorp_ls_core.jsonrpc.streams
Writing: {'jsonrpc': '2.0', 'id': 15, 'method': 'codeFormat', 'params': {'text_document': {'uri': 'file:///Users/janipalsamaki/Projects/demo-robot/tasks.robot'}, 'options': {'tabSize': 4, 'insertSpaces': True}}}
```

Are `.robot` files supposed to be `textDocument` when triggering formatting?

**Comment by fabioz** [comment]
I can see that it properly asks for the formatting and then given an error because `RobotFramework` is not available in the environment -- i.e.: in `robotframework_ls.log.2.lsp.37405.api`:

```
lsp: 2020-12-17 08:32:21 UTC pid: 37405 - MainThread - DEBUG - robocorp_ls_core.jsonrpc.streams
Read: {"id": 3, "jsonrpc": "2.0", "method": "codeFormat", "params": {"options": {"insertSpaces": true, "tabSize": 4}, "text_document": {"uri": "file:///Users/janipalsamaki/Projects/playwright-robot/tasks.robot"}}}

lsp: 2020-12-17 08:32:21 UTC pid: 37405 - MainThread - DEBUG - robocorp_ls_core.jsonrpc.endpoint
Handling request from client {'id': 3, 'jsonrpc': '2.0', 'method': 'codeFormat', 'params': {'options': {'insertSpaces': True, 'tabSize': 4}, 'text_document': {'uri': 'file:///Users/janipalsamaki/Projects/playwright-robot/tasks.robot'}}}

lsp: 2020-12-17 08:32:21 UTC pid: 37405 - MainThread - DEBUG - robocorp_ls_core.jsonrpc.endpoint
Executing async request handler functools.partial(<bound method RobotFrameworkServerApi._threaded_code_format of <robotframework_ls.server_api.server.RobotFrameworkServerApi object at 0x7fab1449e670>>, {'uri': 'file:///Users/janipalsamaki/Projects/playwright-robot/tasks.robot'}, {'insertSpaces': True, 'tabSize': 4})

lsp: 2020-12-17 08:32:21 UTC pid: 37405 - ThreadPoolExecutor-1_0 - EXCEPTION - robotframework_ls.server_api.server
Unable to import 'robot'.

Traceback (most recent call last):
  File "/Users/janipalsamaki/.vscode/extensions/robocorp.robotframework-lsp-0.6.3/src/robotframework_ls/server_api/server.py", line 45, in m_version
    import robot  # noqa
ModuleNotFoundError: No module named 'robot'
```

So, it seems you don't have `RobotFramework` installed in the related Robot... (it's currently using the env from: `sys.prefix: /Users/janipalsamaki/.robocorp/live/e9c45d8509531b13`), so, can you check if your `conda.yaml` does have the proper dependency to include RobotFramework (and if you add it if it starts code-formatting properly).

**Comment by janipalsamaki** [comment]
Thank you for investigating! I do have `rpaframework` installed, and that should include Robot Framework. Strange. 🤔

I'll do some testing with `rpaframework` versions to see if this has something to do with those.

**Comment by fabioz** [comment]
I just fixed it. It was indeed using the language server interpreter in this case.
