### ISSUE TITLE
Launch the current test case from the editor

### ISSUE THREAD

**Issue by brianruss** [robocorp/robotframework-lsp#218]
When developing tests, it is useful to be able to launch just a single test case within a .robot test suite file. This is particularly true when the other test cases in the file take a long time to execute.

It would be ideal if there were a launch configuration that could be created that would launch the current (or currently selected) robot test case in the current file.

I have worked around this at times by adding the "-t My Test Case" env value in the launch configuration, but this has to be changed for each new Test Case.

**Comment by anton264** [comment]
This should work
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "robotframework-lsp",
            "name": "Robot: one test",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "target": "${file}",
            "terminal": "integrated",
            "args": [
                "-t",
                "${input:testname}"
            ]
        }
    ],
    "inputs": [
        {
            "type": "promptString",
            "id": "testname",
            "description": "Enter the name of the test you want to run"
        }
    ]
}

```

**Comment by mardukbp** [comment]
In version 0.18.0 this is already possible.
![image](https://user-images.githubusercontent.com/1140106/123674619-1b285000-d842-11eb-8e01-733a1f37e371.png)

**Comment by fabioz** [comment]
True, closing as this was already added.
