### ISSUE TITLE
OpenVSX take 2

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#219]
It seems OpenVSX underwent some changes and a new user is needed:

Failed at job: https://github.com/robocorp/robotframework-lsp/runs/1590425305?check_suite_focus=true

Guide for publishing with new user: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by sahokas** [comment]
Eclipse account set up & authorized on open-vsx.org and agreements signed for my user account.

Wonder if this is enough - @fabioz the publish step is using a token linked to your user account, right?

**Comment by fabioz** [comment]
I think so... anyways, it's using the `OPEN_VSX_TOKEN` defined at: https://github.com/robocorp/robotframework-lsp/settings/secrets/actions (so, if you can update it to the info you have now it should work).

**Comment by sahokas** [comment]
> I think so... anyways, it's using the `OPEN_VSX_TOKEN` defined at: https://github.com/robocorp/robotframework-lsp/settings/secrets/actions (so, if you can update it to the info you have now it should work).

Updated with a fresh token now

**Comment by fabioz** [comment]
Great, so, when a new release is done (which hopefully should happen tomorrow) the open vsx version should be properly updated.

I'm going to close this then -- if there's any issue when the release is done I'll reopen.
