### ISSUE TITLE
Python library as a directory - keywords not discovered

### ISSUE THREAD

**Issue by nsgundy** [robocorp/robotframework-lsp#228]
I have a custom python library that I implemented as a directory (see [Using physical path to library](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id592), 3rd option in the example given), like this:
```robot
*** Settings ***
Library  APILibrary/
```

None of the keywords contained are discovered. Works fine when I run robot.

Robot Framework LSP v0.6.4

**Comment by fabioz** [comment]
I wasn't even aware this was possible... I'll try to take a look at this soon (within the next 2-3 weeks).

Is it possible for you to attach to this issue a sample case where this is used?

**Comment by nsgundy** [comment]
I have created a [reproduction repo](https://github.com/nsgundy/robot_python_library_as_directory), hope it helps.
