### ISSUE TITLE
Upload Robot to Robocorp Cloud fails when creating a new robot

### ISSUE THREAD

**Issue by kariharju** [robocorp/robotframework-lsp#229]
**Describe the bug**
Create new robot on `Upload Robot to Robocorp Cloud` fails  (updating an existing one succeeds)

**To Reproduce**
1. `Upload Robot to Robocorp Cloud`
2. Select workspace
3. `Create new Robot`
4. Give name
--> Error as in first screen shot
Robot is also added and visible in Cloud but does not work.
Uploading the same robot on top of the one created seems to fix the issue so this is limited to the `Create new Robot`

**Expected behavior**
New robot created to cloud and usable.

**Screenshots**
Error in VsCode:
![image](https://user-images.githubusercontent.com/56814402/104036992-cb46c580-51dc-11eb-90fb-9aef465fb850.png)

..origin missing in Cloud:
![image](https://user-images.githubusercontent.com/56814402/104037365-50ca7580-51dd-11eb-9323-410492850ba4.png)

**Versions:**
 - OS: Windows 10
 - Robocorp Code: 0.6.2

**Comment by fabioz** [comment]
I'll investigate what changed here...

**Comment by fabioz** [comment]
It seems that the info from the robot id is now in `stderr` and not in `stdout` as it used to be.
