### ISSUE TITLE
Robocorp Code able to upload to cloud after unlink

### ISSUE THREAD

**Issue by kariharju** [robocorp/robotframework-lsp#230]
**Describe the bug**
After unlink the credentials are removed locally and on cloud via RCC, but somehow VsCode is still able to upload robot to cloud

**To Reproduce**
1. Link to cloud and upload robot
2. Unlink from cloud and upload robot cloud --> Upload succeeds
3. Close all VsCode instances
4. Restart and upload robot to cloud --> Upload succeeds

**Expected behavior**
All cloud actions should fail after unlink has been performed

**Versions:**
 - OS: Windows 10
 - VSCode 0.6.2

**Comment by fabioz** [comment]
Right now Robocorp Code is able to use any valid login (so, it can reuse the default login done on the command line or Robocorp lab).

So, this is more a feature than a bug...

It should be simple to not use logins from other places, but I'm not really sure what's best here.

**Comment by kariharju** [comment]
So yeah this comes from the debate over "app specific creds vs single-sign-on creds" and the fallback logic during that.
So either we block the extension from falling back to use the default (so in this case user also has Lab linked and that is causing this) OR we revert to extension to also just use the default like it used to.
Need to figure this out over weekend. @fabioz ping me if I don't give an answer during Monday ;)
