### ISSUE TITLE
Robocorp Code fails to launch on macOS

### ISSUE THREAD

**Issue by kariharju** [robocorp/robotframework-lsp#237]
**Describe the bug**
On MacOs after 0.7.0 update the extension fails on start:
"Unable to get python to launch language server"

**To Reproduce**
1. Open example robot and goto Robocorp Code sidebar

**Screenshots**
![image](https://user-images.githubusercontent.com/56814402/105502876-99e6f300-5cce-11eb-82b8-11776959b102.png)

**Versions:**
 - OS: MacOS (Big Sur)
 - Robocorp Code 0.7.0

**Comment by fabioz** [comment]
Can you provide the output of the tab: `Output > Robocorp Code`?

**Comment by fabioz** [comment]
Should be fixed in: https://github.com/robocorp/robotframework-lsp/commit/c56ebe2d74e292d9febd9c6863d13c276f551c85 (just pushed 0.7.1, it should be available in a few minutes).
