### ISSUE TITLE
Add support for using VSCode environment variables for configuration settings

### ISSUE THREAD

**Issue by rdagum** [robocorp/robotframework-lsp#239]
I tried using the following configuration to point to the python binary inside a virtual environment
"robot.language-server.python": "${workspaceFolder}\\.temp\\pvenv\\Scripts\\python.exe"

This would allow the repository to be cloned anywhere (by different users) and not worry about reconfiguring the location of python which is automatically created inside the .temp folder.

**Comment by fabioz** [comment]
> Support for unix style relative paths would also be very useful.

I thought this was supported already... can you give an example of what you mean?

**Comment by tuomoturunen-solita** [comment]
> > Support for unix style relative paths would also be very useful.
> 
> I thought this was supported already... can you give an example of what you mean?

I tried to add pyenv directory from my home directory like "~/.pyenv/latest/site-packages" to pythonpath and it didn't work until I used absolute path. Looks like it is the same thing with other VSCode settings. I'm relatively new with VSCode so I might be wrong.

**Comment by Ka55i0peia** [comment]
The feature becomes **very important/essential in near future**. See https://github.com/microsoft/vscode-python/wiki/AB-Experiments

**Comment by fabioz** [comment]
This was fixed in `0.17.0` (soon to be released).

See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-use-variables-in-settings for info on how to use it.
