### ISSUE TITLE
Please consider adding this extension to Open VSX

### ISSUE THREAD

**Issue by matusaurio** [robocorp/robotframework-lsp#250]
Please consider adding this extension to the project [Open VSX](https://open-vsx.org/) for those of us using VS Code compatible editors like [Codium](https://vscodium.com/).

You can find the instructions documented in the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Thank you

**Comment by fabioz** [comment]
It's already there: https://open-vsx.org/extension/robocorp/robotframework-lsp ;)
