### ISSUE TITLE
IF-ELSE blocks indentation is lost on format (RFW4 feature)

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/robotframework-lsp#260]
**Describe the bug**
The indentation in the new Robot Framework 4 syntax IF-ELSE is removed by the LSP. Code still works but looks a bit bad.

**Actual behavior**
```
*** Keywords ***
Teardown handler
    IF    "${TEST_STATUS}"=="FAIL"
    Report Incident
    END
```

**Expected behavior**

```
*** Keywords ***
Teardown handler
    IF    "${TEST_STATUS}"=="FAIL"
        Report Incident
    END
```

**Versions:**
 - OS:  Windows 10
 - Robot Framework Version 4.0rc1
 - Robot Framework Language Server Version 0.9.0
 - Client Version VS 1.54.1

**Comment by fabioz** [comment]
The code-formatter is actually provided by Robot Framework tidy tool (the language server just calls it).

So, please report this to: https://github.com/robotframework/robotframework
