### ISSUE TITLE
Support for variables in resource names

### ISSUE THREAD

**Issue by tranquvis** [robocorp/robotframework-lsp#261]
**Is your feature request related to a problem? Please describe.**
As you see in the following code, I reference a resource, based on a variable. This is supported by robot framework, but the language server seems to don't parse the referenced resource.

```robot
*** Settings ***
Resource  main_page.${PLATFORM_NAME}.resource
```

**Describe the solution you'd like**
I would like that variables in the resource names are evaluated, so that such resources are parsed too. Ideally, the variable definitions of previous imports are considered, but it would also be enough for me, if these variables can be configured via the VSCode config.

**Describe alternatives you've considered**
I couldn't think of any alternatives.

**Comment by Ka55i0peia** [comment]
@tranquvis 
> it would also be enough for me, if these variables can be configured via the VSCode config

They can be defined in `settings.json`, see [this page](https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/config.md#configuration-settings).

Indeed placeholder like `${workspaceFolder}` are not yet supported yet (https://github.com/robocorp/robotframework-lsp/issues/239)

**Comment by tranquvis** [comment]
I found out that this feature is already implemented. You have to psecify the variables in the vscode settings.
```json
"robot.variables": {
    "PLATFORM_NAME": "Android"
}
```
