### ISSUE TITLE
PyCharm project specifix settigs help text is not correct

### ISSUE THREAD

**Issue by aaltat** [robocorp/robotframework-lsp#268]
In the plugin project specific setting, the help text of `Python Env` is not totally correct. It says: 
```
Specifies the environment to be used when loading `robotframework` code and dependent libraries.
i.e.: {"MY_ENV_VAR": "some_value"}
Note: expected as JSON Object
```
But I do not fully get what the  "i.e.: {"MY_ENV_VAR": "some_value"} Note: expected as JSON" actually mean in this context? 

![image](https://user-images.githubusercontent.com/2665023/111882041-feb38680-89bb-11eb-9538-ab62a28f7490.png)

**Comment by fabioz** [comment]
Well, these are the environment variables passed to the process that imports robot framework... improvements to the text accepted ;)

**Comment by fabioz** [comment]
p.s.:`expected as JSON object` is meant to be that it should be specified in the same format as you'd specify a json object.

I changed this to: `Note: expected format: JSON Object` in https://github.com/robocorp/robotframework-lsp/commit/8b12add44a467a5585e6fa721878effb470770b6
