### ISSUE TITLE
Integrate new robotidy

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#273]
Note: requires https://github.com/MarketSquare/robotframework-tidy/issues/49 to be done first.

**Comment by KotlinIsland** [comment]
You should change the defaultto robotidy

**Comment by fabioz** [comment]
> You should change the default to robotidy

I agree. This is being tackled in https://github.com/robocorp/robotframework-lsp/issues/643 (note that it's already the default if you use Robot Framework 5, since it's the only formatter available for that version).
