### ISSUE TITLE
Request textDocument/semanticTokens/full failed.

### ISSUE THREAD

**Issue by lanjia1028** [robocorp/robotframework-lsp#274]
the same issue as rust-analyzer LSP  on 10 Jun 2020. 
https://github.com/rust-analyzer/rust-analyzer/issues/5998

issue log .
Getting language server Python executable.
Language server Python executable. Searching in PATH.
Starting RobotFramework Language Server with args: C:\python\python.exe,-u,c:\Users\admin\.vscode\extensions\robocorp.robotframework-lsp-0.10.0\src\robotframework_ls\__main__.py,-vv,--log-file=<D:\ttt\robotframework_ls.log>
Waiting for RobotFramework (python) Language Server to finish activating...
RobotFramework Language Server ready. Took: 3.0s
[Error - 上午11:57:25] Request textDocument/semanticTokens/full failed.
  Message: KeyError: 'result'
  Code: -32602 
[object Object]
[Error - 上午11:57:25] Request textDocument/semanticTokens/full failed.
  Message: KeyError: 'result'
  Code: -32602 
[object Object]
[Error - 上午11:57:26] Request textDocument/semanticTokens/full failed.
  Message: KeyError: 'result'
  Code: -32602 
[object Object]
[Error - 上午11:57:30] Request textDocument/semanticTokens/full failed.
  Message: KeyError: 'result'
  Code: -32602 
[object Object]

**Comment by fabioz** [comment]
Can you provide the log files from the language server? (I see you passed `--log-file=<D:\ttt\robotframework_ls.log>` in the args... it should probably be: `--log-file=D:\ttt\robotframework_ls.log` (i.e.: without the `<` and `>` chars).

**Comment by fabioz** [comment]
I found one issue which could be related... I'm not 100% since no logging was attached to this issue -- but I'm hopeful it'll fix it ;)

**Comment by lanjia1028** [comment]
yes , now it is fine , thanks for your support~  a regards from the greatWall.
