### ISSUE TITLE
Highlighting keyword only highlight one word instead of the whole keyword

### ISSUE THREAD

**Issue by mnojek** [robocorp/robotframework-lsp#279]
When using `Ctrl + left mouse click` on a keyword call, you can quickly go to its definition, which works fine. But when holding Ctrl key and hovering over the keyword, it only highlights the word that is hovered, not the whole keyword. It looks strange and I think it should highlight the whole keyword instead.

Here's the screenshot (my pointer is not visible, but you can imagine it on the `Page` word):
![image](https://user-images.githubusercontent.com/7412964/112455263-d6c87800-8d59-11eb-9809-9b8935de886c.png)

**Comment by fabioz** [comment]
Raising priority given upvotes.
