### ISSUE TITLE
Debugger ignore Breakpoints from SuiteSetup

### ISSUE THREAD

**Issue by chemstar** [robocorp/robotframework-lsp#281]
**Describe the bug**
Debugger ignore Breakpoints from SuiteSetup (dunder init.robot)

**To Reproduce**
1.Prepare dunder init.robot with SuiteSetup and some KWs included
2. Execute Debuger starting from dunder init.robot (launch.json: "target": "${fileDirname}",)

**Expected behavior**
Debugger should always stop on Breakpoints

**Screenshots**
none

**Versions:**
 - OS: Windows 10
 - Robot Framework Version 3.2
 - Robot Framework Language Server Version 0.11.o
 - Client Version VSCode 1.54.3

**Comment by fabioz** [comment]
This is fixed for `0.17.0`

**Comment by chemstar** [comment]
Fabio you are fantastic!
