### ISSUE TITLE
Robocorp Lab cannot find keywords from not-opened files

### ISSUE THREAD

**Issue by orlof** [robocorp/robotframework-lsp#285]
[robot.zip](https://github.com/robocorp/robotframework-lsp/files/6221381/robot.zip)

1. open robot in Lab
2. open tasks.robot, no keywords are found
3. open keywords/keywords.robot notebook, go back to tasks.robot and save it, `Example keyword` is found
4. open keywords/indirect.robot notebook, go back to tasks.robot and save it, `Example indirect keyword` is found

Happens in MacOS

**Comment by fabioz** [comment]
As a note: in VSCode it seems to work (so, it really seems related to Lab).

![image](https://user-images.githubusercontent.com/117621/112883615-e3740580-90a4-11eb-8c9a-335a285a30d0.png)

**Comment by fabioz** [comment]
Closing this issue as it's not really an issue in the language server but rather in the client (which doesn't provide the original URI to the language server).
