### ISSUE TITLE
Robocop reports not existing issue with missing trailing blank line

### ISSUE THREAD

**Issue by mnojek** [robocorp/robotframework-lsp#286]
From version 0.11.0 (also in 0.11.1) LSP reports a Robocop problem in PyCharm with code `Missing trailing blank line at the end of file` even if the blank line is present at the end of file. This is not a problem with Robocop because it handles it correctly. It can be a problem with passing the file content by LSP. In practice, the last empty line does not exist because it's only a `\n` in the previous line which creates it. 
![image](https://user-images.githubusercontent.com/7412964/112940267-32fe1400-912d-11eb-99db-abc0833633f5.png)
This problem disappears when there are 2 empty lines in the file.
![image](https://user-images.githubusercontent.com/7412964/112940388-5fb22b80-912d-11eb-8255-86dfb33aa0d4.png)

**Comment by fabioz** [comment]
I just checked it and it doesn't seem to be an issue on the language server.

I've just reported it as an issue in Robocop: https://github.com/MarketSquare/robotframework-robocop/issues/307
