### ISSUE TITLE
Change header title in robotframework-intellij README

### ISSUE THREAD

**Issue by mnojek** [robocorp/robotframework-lsp#293]
There is a duplicated header in robotframework-intellij README file '[Installing latest from Github Actions](https://github.com/robocorp/robotframework-lsp/tree/master/robotframework-intellij#installing-latest-from-github-actions)'. It probably needs to be changed to 'Installing from JetBrains Marketplace'.

**Comment by fabioz** [comment]
Thanks for the report. This was fixed at: https://github.com/robocorp/robotframework-lsp/commit/9c7c3d30a7455600c2e2211dfa065af903b1f877
