### ISSUE TITLE
Error creating libspec: RPA.JSON

### ISSUE THREAD

**Issue by adrian-evo** [robocorp/robotframework-lsp#294]
RPA.JSON library spec is not created within Visual Studio Code, thus any keyword, e.g. Load JSON From File, is not recognised.

![image](https://user-images.githubusercontent.com/19324942/113560718-1f125080-960c-11eb-8166-3a0dbaad6101.png)

Other RPA libraries, e.g. FTP are working.

Workaround:
If I copy JSON.py from site-packages to under local project directory, rename it to e.g. JSON2.py including the class, then the libspec is generated successfully.

**Versions:**
 - Windows 10
 - rpaframework 9.3.4
 - Robot Framework Language Server Version 0.12.0
 - VSCode 1.55.0

**Logs**
Getting language server Python executable.
Language server Python executable gotten from robocorp.getLanguageServerPython.
Plugins dir: c:\Users\x\.vscode\extensions\robocorp.robocorp-code-0.8.2\src\robocorp_code\plugins.
Starting RobotFramework Language Server with args: C:\Users\x\AppData\Local\robocorp\live\2aa1db4bb1a50e5e\python.exe,-u,c:\Users\x\.vscode\extensions\robocorp.robotframework-lsp-0.12.0\src\robotframework_ls\__main__.py
Waiting for RobotFramework (python) Language Server to finish activating...
RobotFramework Language Server ready. Took: 852.7s
lsp: 2021-04-05 12:26:57 UTC pid: 28572 - ThreadPoolExecutor-1_2 - EXCEPTION - robotframework_ls.impl.libspec_manager
Error creating libspec: RPA.JSON.
Return code: 252
Output:
Spec file 'RPA.JSON' does not exist.

Try --help for usage information.

Traceback (most recent call last):
  File "c:\Users\x\.vscode\extensions\robocorp.robotframework-lsp-0.12.0\src\robotframework_ls\impl\libspec_manager.py", line 888, in _cached_create_libspec
    cwd=cwd,
  File "c:\Users\x\.vscode\extensions\robocorp.robotframework-lsp-0.12.0\src\robotframework_ls\impl\libspec_manager.py", line 773, in _subprocess_check_output
    return subprocess.check_output(*args, **kwargs)
  File "C:\Users\x\AppData\Local\robocorp\live\db2471200db0dbb8\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\x\AppData\Local\robocorp\live\db2471200db0dbb8\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\x\\AppData\\Local\\robocorp\\live\\db2471200db0dbb8\\python.exe', '-m', 'robot.libdoc', '-P', 'c:\\Data\\Robots\\punch-task\\.', 'RPA.JSON', 'C:\\Users\\x\\.robotframework-ls\\specs\\v2\\0cd1f8a0_4.0\\user\\RPA.JSON.libspec']' returned non-zero exit status 252.
lsp: 2021-04-05 12:27:00 UTC pid: 15016 - ThreadPoolExecutor-1_11 - EXCEPTION - robotframework_ls.impl.libspec_manager
Error creating libspec: RPA.JSON.
Return code: 252
Output:
Spec file 'RPA.JSON' does not exist.

**Comment by fabioz** [comment]
I just investigated and this seems to be a bug in `Robot Framework` itself.

i.e.: I reported it at: https://github.com/robotframework/robotframework/issues/3919

as a workaround, you can rename the library as you did or you can manually change `robot/libdocpkg/builder.py` to comment out the place where it does:

```
    if extension == 'json':
        return JsonDocBuilder()
```

To know where that file resides you can call the command below in the command line:

`C:\Users\x\AppData\Local\robocorp\live\db2471200db0dbb8\python.exe -c "import robot.libdocpkg.builder as b;print(b.__file__)"`

**Comment by fabioz** [comment]
Closing as there's not much to be done in the language server side (a fix needs to be provided in Robot Framework itself -- until then, one of the workarounds mentioned above need to be used).

**Comment by fabioz** [comment]
Note: `Robot Framework 4.0.1` (which was just released) has a fix for this issue.

**Comment by mr2dark** [comment]
Extra note: `Robot Framework 4.0.1` introduces another issue which makes it unusable to an extent: https://forum.robocorp.com/t/fixing-problem-typeerror-subscripted-generics-cannot-be-used-with-class-and-instance-checks/636
