### ISSUE TITLE
Accessing a dict/list variable with &/@ is not recognized in autocompletion 

### ISSUE THREAD

**Issue by Chris-Schr** [robocorp/robotframework-lsp#301]
**Describe the bug**
When I create a dict &{variable} or a list @{variable} and want to access it with ${variable} it is not recognized in autocompletion.
I also does not find the variable when holding ctrl+click.

**To Reproduce**
example code:
*** Variables ***
&{test}  fdj=dfk  dfkj=dkf
 
*** Test Cases ***                                     
Test
    Log to Console   ${test}

**Expected behavior**
Autocompletion should work

**Versions:**
OS: Windows 10
Robot Framework Version: 3.2.1
Robot Framework Language Server Version: v0.12.0
Client Version: VSCode 1.54.3

**Comment by mardukbp** [comment]
I just submited a [pull request](#400) that implements completion for dictionary variable names and another [pull request](#401) that implements completion for dictionary items, even for nested dictionaries.
