### ISSUE TITLE
Some Strange things found

### ISSUE THREAD

**Issue by extr3mal** [robocorp/robotframework-lsp#308]
If code has an import with name , then all of keywords will be marked as incorrect
`Library           FakerLibrary    locale=en_US    WITH NAME    FakerUS`
![image](https://user-images.githubusercontent.com/4517549/114262337-34aac000-99e8-11eb-9f29-2296780d1601.png)
Robot has a keyword functionality that allows to embeed variables into keywords. If user wants to check some kind of a text on page using embeeded syntax, plugin highlights such keywords as wrong typed.
![image](https://user-images.githubusercontent.com/4517549/114262429-9408d000-99e8-11eb-85a5-dca36aed30e0.png)
Text that user search can be lowercase so it's a normal thing to add text in lower as variable into keyword

**Comment by fabioz** [comment]
The second issue (`Keyword name should be capitalized`) is actually related to the linter (`Robocop`) -- if you want the linter changed you can try to report something to: https://github.com/MarketSquare/robotframework-robocop/issues or you can probably disable/customize it (see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-configure-the-robocop-linter for details on how to do that).

For the first issue, I couldn't really reproduce it, so, I think it's a configuration error... Please take a look at the related FAQ: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved

If you still can't fix it with the FAQ, please add the related logging information (https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md) and reopen the issue.

![image](https://user-images.githubusercontent.com/117621/114393390-5767e080-9b70-11eb-92c1-5b41aac84691.png)
