### ISSUE TITLE
No parsing of *.resource files

### ISSUE THREAD

**Issue by Snooz82** [robocorp/robotframework-lsp#32]
Hi @fabioz ,

I tested the Version 0.0.5 and saw, that only .robot files are highlighted and parsed.
robot has by default support for *.robot files for test cases and *.resource files for keywords and variables. basically they are the same syntax. only resource files are not parsed and analyzed for test cases, when robot starts.

Regards
René

**Comment by fabioz** [comment]
Fixed in https://github.com/robocorp/robotframework-lsp/commit/745e6ea9aab3a19216b146285c0b969ad1a27ebd
