### ISSUE TITLE
Exceptions when using Code Completion

### ISSUE THREAD

**Issue by Snooz82** [robocorp/robotframework-lsp#33]
Hi @fabioz 

I tested v 0.0.5 

depending of the library loaded (if it is small enough) i was able to get a few completions.
But after two or three keywords i got nothing more. just "Loading ..."

Sometime i started with an empty file and BOOM!

The error is the following:
```
Traceback (most recent call last):
  File "/Users/rener/.vscode-oss/extensions/robocorptech.robotframework-lsp-0.0.5/src/robotframework_ls/jsonrpc/streams.py", line 56, in listen
    message_consumer(json.loads(request_str.decode("utf-8")))
  File "/Users/rener/.pyenv/versions/3.8.0/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/rener/.pyenv/versions/3.8.0/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/rener/.pyenv/versions/3.8.0/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 colum/Users/rener/robotframework_ls.2568.logn 65389 (char 65388)
2020-04-01 23:12:54,708 UTC pid: 2568 - Thread-18 - DEBUG - robotframework_ls.jsonrpc.streams
Writing: {'jsonrpc': '2.0', 'id': 29, 'method': 'lint', 'params': {'doc_uri': 'file:///Source/lsp-test/test.robot'}}
```

The Length of the jsonrpc seems to have something to do with the error.
64389 is pretty close to 64k (65536)
Sometimes the length is a bit longer like 65444 sometime a bit shorter...
But it is always around 64k
the max size of a TCP package is also 65536 Bytes. minus header and so on...

This happens on a mac. 

Cheers
[robotframework_ls.2568.log](https://github.com/robocorp/robotframework-lsp/files/4417733/robotframework_ls.2568.log)

**Comment by fabioz** [comment]
As it seems pretty critical, I did a fix for this and released 0.0.6 with it, can you check if it works for you?

-- note that I haven't been able to reproduce it myself, even adding lots of keywords for the code-completion and having a really big json, so, I'm not 100% sure that the fix will work.

**Comment by fabioz** [comment]
Should be fixed by: https://github.com/robocorp/robotframework-lsp/commit/745e6ea9aab3a19216b146285c0b969ad1a27ebd

Please add an updated log file if it still didn't work with the new version.

**Comment by Snooz82** [comment]
@fabioz 

This fix works!
Awesome!
