### ISSUE TITLE
YAML editing posting errors constantly (specific machine)

### ISSUE THREAD

**Issue by kariharju** [robocorp/robotframework-lsp#330]
**Describe the bug**
Every key press to any .yaml file causes error.

**To Reproduce**
1. Take any robot template and edit conda.yaml or robot.yaml
..does not repeat on all machines, so far only one Windows machine reproduces this 
..tried uninstalling and re-installing the extension, did not help.

Logs from issue report:
[#659-attachments_34a815a8477e637b.zip](https://github.com/robocorp/robotframework-lsp/files/6349206/659-attachments_34a815a8477e637b.zip)

**Versions:**
 - OS: Windows 10
 - Logs attached for the rest

**Comment by fabioz** [comment]
I think I know what's happening... I'll try to provide a fix for this along with https://github.com/robocorp/robotframework-lsp/issues/329 later today.
