### ISSUE TITLE
Identify unknown variables

### ISSUE THREAD

**Issue by kvo-harmoney** [robocorp/robotframework-lsp#334]
Using Pycharm/ lsp, it would be nice if 'unknown' variables can be identified.

Imagine following piece of code :

Do something
    [Arguments]    ${argVar1}    ${argVar2}
    Post And Assert RC     arg=/x/y/${argVar1}     data=${argVar21}

-->  ${argVar21} is not identified

It would be nice if the unknown variable could be identified.
Since some variables can be global/suite defined variables, it would be extra nice if some exclusion list could be set so that some unknown variables can be silently ignored from the validation mechanism.

**Comment by Rodaxfck** [comment]
@fabioz Looking forward this feature too... Executing an entire test suite and get a FAIL because of mistake on a variable name if so annoying :( The last thing to make robotframework-lsp perfect ♥ (VSCode user)

**Comment by fabioz** [comment]
As a note, this is now available in a pre-release (0.42.2).

See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/changelog.md for all that's changed in the pre-release.

For this particular feature given that RF makes it easy to create variables in multiple ways, I'm curious on testing to filter out possible false positives.
