### ISSUE TITLE
[Debugger] Implement mixed-mode debugging (RobotFramework and python at the same time)

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#337]
i.e.:
It should be possible to have breakpoints both for Python as well as for RobotFramework.

The stack shown should take into account both to be consistent and evaluate should also do the proper thing based on the context.

**Comment by fabioz** [comment]
As a note, right now the workaround is starting the debugger in RobotFramework mode and use a remote attach from the Python debugger (but this isn't the optimal workflow for users).

**Comment by chemstar** [comment]
Adressing same problem here [issuse 282](https://github.com/robocorp/robotframework-lsp/issues/282#issue-840786313)

**Comment by fabioz** [comment]
It seems I had missed that an issue was already opened. Closing this one in favor of: https://github.com/robocorp/robotframework-lsp/issues/282
