### ISSUE TITLE
robotframework version (NO_ROBOT) too old for linting.Please install a newer version and restart the language server.

### ISSUE THREAD

**Issue by Sri-user** [robocorp/robotframework-lsp#338]
**Describe the bug**
robotframework version (NO_ROBOT) too old for linting.Please install a newer version and restart the language server. This error is displayed on the first line for *** Settings ***

I am using pycharm and robocorp language server plugin. Tried with VScode and language server plugin. Still the same result

**Expected behavior**
Linting error should disappear

**Screenshots**
![image](https://user-images.githubusercontent.com/55939099/116352244-8178fe00-a812-11eb-9d8d-87cf634fb0e8.png)

**Versions:**
 - OS: [e.g. Windows 10]
 - Robot Framework Version [e.g. 4.0.1]
 - Robot Framework selenium Library [5.1.3]
 - Robot Framework Language Server Version [e.g. 0.14.0]
 - Client Version [e.g.: VSCode 1.55.2 or PyCharm 2021.1 (Community Edition)]

**Comment by nmazzon** [comment]
me too .. :( 

> 
> 
> **Describe the bug**
> robotframework version (NO_ROBOT) too old for linting.Please install a newer version and restart the language server. This error is displayed on the first line for *** Settings ***
> 
> I am using pycharm and robocorp language server plugin. Tried with VScode and language server plugin. Still the same result
> 
> **Expected behavior**
> Linting error should disappear
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/55939099/116352244-8178fe00-a812-11eb-9d8d-87cf634fb0e8.png)
> 
> **Versions:**
> 
>     * OS: [e.g. Windows 10]
> 
>     * Robot Framework Version [e.g. 4.0.1]
> 
>     * Robot Framework selenium Library [5.1.3]
> 
>     * Robot Framework Language Server Version [e.g. 0.14.0]
> 
>     * Client Version [e.g.: VSCode 1.55.2 or PyCharm 2021.1 (Community Edition)]

**Comment by fabioz** [comment]
This mean that the Python being used doesn't really have `Robot Framework` installed.

Please take a look at the related `FAQ`: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-solve-no_robot-too-old-for-linting

**Comment by Sri-user** [comment]
Yes that solved it. @nmazzon 

In pycharm, create a new project, and choose new virtual env, and choose a python installed in system, not installed through conda

Now after doing this, go to settings->select project->project interpreter-> Here click on + sign to install the robotframework-seleniumlibrary here

then add the extension, restart the ide 

For VS code,ctrl+alt+p_> search for python interpreter-> choose system installed python version

after selecting that, in the terminal, just run the pip install robotframework-seleniumlibrary

add the extension of robocorp

restart visual studio code

and its working now

![image](https://user-images.githubusercontent.com/55939099/116390731-fd3b7080-a83b-11eb-9e1a-83ad47260c6b.png)
