### ISSUE TITLE
LS not properly/fully validating library keywords

### ISSUE THREAD

**Issue by kvo-harmoney** [robocorp/robotframework-lsp#339]
**Describe the bug**
RequestLibrary 0.9.1 keywords are not fully/properly recognised by LS

**To Reproduce**
Install robotframework-requests and check attached/following piece of code

**Expected behavior**
In the above snippet, the Create Session keyword is properly validated/recognised by LS.
The GET On Session keyword is however not recognised.

The test is functionally running ok. So I guess the problem is on the LS validation mechanism ?

**Screenshots**
![Screen Shot 2021-04-28 at 18 10 40](https://user-images.githubusercontent.com/66485546/116436867-1c8ec980-a84d-11eb-83f0-5d82ea6ee2a1.png)

**Versions:**
 - OS: Mac OS High Sierra
 - Robot Framework Version 4.0.1
 - Robot Framework Language Server Version 0.14
 - PyCharm 2021.1.1]

**Comment by fabioz** [comment]
Please take a look at the FAQ: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved

p.s.: it does work for me -- see below -- so, I believe it's a configuration issue (hopefully the FAQ is enough to help you there... if it's not, please reopen and provide the related logs -- see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md for details on how to get those).

![image](https://user-images.githubusercontent.com/117621/116441954-539eb400-a828-11eb-9529-5a27e2a6c63a.png)
