### ISSUE TITLE
Robot Framework Visual Studio Code Language Server Protocol extension does not handle Python settings for workspace

### ISSUE THREAD

**Issue by martti-soderlund-fi-abb-com** [robocorp/robotframework-lsp#349]
**Robot Framework Visual Studio Code Language Server Protocol extension does not handle Python settings for workspace**

**To Reproduce**
1) Without configuration, the extension reports: "Unable to start robotframework-lsp because: python could not be found on the PATH. Do you want to select a python executable to start robotframework-lsp?"
2) Selecting an interpreter from neither user or workspace option saves the setting but the same dialog pops up on the next startup.
3) Saving to workspace settings.json does not work either, only user settings.

**Expected behavior**
The setting would be saved after the dialog and could be used in order of preference from the workspace, then user settings.

**Versions:**
 - OS Version Windows 10
 - Robot Framework Version 3.2.2, 4.0.1, 4.0.2
 - Robot Framework Language Server Version 0.16.0
 - Client Version VSCode 1.56.2
 - Python 3.7.7

**Logs**
No logs, the instructions on the logging don't seem to work (Or I did not find them..).

**Workaround**
On Windows, only saving the Python to user settings seems to work. This workaround is not the best for test automation development as typically then Virtualenv is used to support particular test configurations requiring different Python modules. Saving to workspace would be better.

**Comment by fabioz** [comment]
This was really a bug. It's fixed along with another issue in: https://github.com/robocorp/robotframework-lsp/commit/215693d2b1344a48506ad38368908a1fca73a53a

**Comment by fabioz** [comment]
(Fixed for 0.17.0)

**Comment by martti-soderlund-fi-abb-com** [comment]
Confirmed on the same platform, using Python 3.8. Thank you for the prompt correction!
