### ISSUE TITLE
Exception in plugin Robot Framework Language Server.

### ISSUE THREAD

**Issue by cookindutch** [robocorp/robotframework-lsp#351]
**Describe the bug**
When I load Pycharm I get an 'IDE Fatal Errors' message for the Robot Framework Language Server.

**To Reproduce**
1. Install the Robot Framework Language Server
2. Restart Pycham.

**Expected behavior**
I would expect the program to load without an exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/84199068/118307464-f8b3c080-b4a7-11eb-8542-dd1f3bcb9f3f.png)

**Versions:**
 - OS: Windows 10
 - Robot Framework Language Server Version 0.16.0
 - PyCharm 2021.1.1

**Comment by fabioz** [comment]
It seems this report is the same as https://github.com/robocorp/robotframework-lsp/issues/350, so, I'm closing it.

Please create a separate ticket showing the exception.
