### ISSUE TITLE
Exception in plugin

### ISSUE THREAD

**Issue by cookindutch** [robocorp/robotframework-lsp#352]
**Describe the bug**
Starting Pycharm generates an exception when I ![image](https://user-images.githubusercontent.com/84199068/118317937-ee002800-b4b5-11eb-9c5a-d3bcbe22db44.png)
**To Reproduce**
1. Install Robot Framework Language Server 0.16.0
2. Restart Pycharm

**Expected behavior**
Pycharm should load without an exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/84199068/118318013-07a16f80-b4b6-11eb-8cc1-e703861ce232.png)

**Versions:**
 - OS: e.g. Windows 10
 - Robot Framework Language Server Version 0.16.0
 - PyCharm 2020.1.2]

**Comment by fabioz** [comment]
@cookindutch Can you attach the actual text of the error to this issue? The important part (which would be the line numbers) are not shown...

**Comment by fabioz** [comment]
I think I fixed it (without the actual lines in the report and the fact that I couldn't really reproduce it here, that's just a guess, so, if you can include the actual report afterwards I can double-check it).
