### ISSUE TITLE
Highlighting Gherkin keywords on Intellij LS

### ISSUE THREAD

**Issue by bahung1221** [robocorp/robotframework-lsp#353]
**Is your feature request related to a problem? Please describe.**

Currently, RobotFramework LS on Intellij highlighting Gherkin keywords like `Given`, `When`, `Then` just like other keywords.

I just think it will be better and increase the readability if these keywords have a different color compared to other keywords.

<img width="1026" alt="Screen Shot 2021-05-15 at 22 21 08" src="https://user-images.githubusercontent.com/27690861/118368188-f6e31d80-b5cb-11eb-8519-007fdfb7083f.png">

Thanks a lot 🍻

**Comment by weltings** [comment]
Hi, I would like to implement Gherkin/BDD highlighting on VS Code. But I am new to robotframework-lsp.

Can someone help me get started?

I tried to define a syntactic token in robotframework.tmLanguage.json:

>         "keyword_call": {
>             "end": "^(?!\\s*\\.\\.\\.)",
>             "begin": "^(?!(?: {2,}| ?\\t ?)+(?:(?=[$\\[@&%]|\\.)))(?: {2,}| ?\\t ?)+(?:Given|When|Then|And|But)?\\s?(.*?)(?= {2,}| ?\\t ?| ?$)",
>             "beginCaptures": {
>                 "1": {
>                     "name": "bddprefix.keyword.call.robot"
>                 },
>                 "2": {
>                     "name": "meta.support.function.robot"
>                 }                
>             },

But it gets overwritten by the semantic token "keywordNameCall". Now I'm trying to define a new semantic token, but I cannot find the code parts that I need to adjust.

I'm guessing I need to change at least the following:
1. Add entry to TOKEN_TYPES in semantic_tokens.py
2. Add entry to robotframework_ls.impl.robot_constants in robot_constants.py
3. Add entry to RF_TOKEN_TYPE_TO_TOKEN_TYPE_INDEX in semantic_tokens.py
4. Add entry to semanticTokenScopes in package.json

But maybe I also need to adjust the logic that assigns the semantic tokens and returns them to the IDE when the IDE calls the language server?

Microsoft mentions that a Language Server Protocol implementation can register a semantic token provider:
https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide

> const provider: vscode.DocumentSemanticTokensProvider = {
>   provideDocumentSemanticTokens(
>     document: vscode.TextDocument
>   ): vscode.ProviderResult<vscode.SemanticTokens> {
>     // analyze the document and return semantic tokens

However I cannot find any function in the whole project where Robot Framework LSP registeres its semantic token provider.

Can anyone tell me if I am on the right track?

**Comment by fabioz** [comment]
Done in: https://github.com/robocorp/robotframework-lsp/commit/e165c0326b7bc539007414157ad3e52ce508490a
