### ISSUE TITLE
Run Tests Suite doesn't use __init__.robot file

### ISSUE THREAD

**Issue by Veronit** [robocorp/robotframework-lsp#355]
**Describe the bug**
_Run Suite_ doesn't use for example Suite Setup set in __init__.robot file. 
Same happend with _Run_ link in individual test cases

**To Reproduce**
1. Set up Suite Setup in __init__.robot file
2. Write some test
3. Run Test/Tests
-> Suite Setup in __init__.robot file wasn't used when running test

**Expected behavior**
Suite Setup in __init__.robot is executed similar to when running tests from command prompt

**Screenshots**
![image](https://user-images.githubusercontent.com/8404548/118471603-9a3d4b00-b710-11eb-9802-e88f3a3ff0a1.png)

**Versions:**
 - Windows 10
 - Robot Framework Version: 3.2.2
 - Robot Framework Language Server Version: 0.16.0
 - Client Version: VSCode 1.56.0

**Logs and files**
Attached is an example test and init.robot file. Also attached is the log.html from an execution

[attachment_files.zip](https://github.com/robocorp/robotframework-lsp/files/6493124/attachment_files.zip)

**Comment by chemstar** [comment]
Could ne same issue as described in https://github.com/robocorp/robotframework-lsp/issues/281

**Comment by fabioz** [comment]
I just took a look at this and it seems to be working correctly (this is how `Robot Framework` itself works) -- it's not the same thing as https://github.com/robocorp/robotframework-lsp/issues/281.

i.e.:

By running `python -m robot lsp_test.robot`, the `__init__.robot` isn't really loaded nor executed (it's only loaded if the folder itself is run in something as `python -m robot .`, which isn't currently possible by using those shortcuts, it'll always run either all the tests in the module or a selected test).

So, if the `__init__.robot` should actually be executed in this case, `Robot Framework` itself should be changed/fixed to support that.

**Comment by Veronit** [comment]
OK. That seems to be the case... I thought that __init__.robot should be executed in every situation. I have been using Ecipse as an IDE for severeal years and it's RED- plugin (https://github.com/nokia/RED) works that way.

So when developing tests I can run an individual test and it executes __init__.robot. It makes writing and testing tests so much easier. Could this be LSP be modified to work the same way? Or maybe add a setting to select whether to execute __init__.robot or not.

**Comment by fabioz** [comment]
It seems there's a way to make that run (by creating a suite to execute adding the needed directory along with the test).

I'll change the language server to do that in the shortcuts.

**Comment by Veronit** [comment]
Awesome!! Thank you so much!

**Comment by fabioz** [comment]
Done for `0.17.0`.
