### ISSUE TITLE
Keywords from Browser jsextension are not resolved

### ISSUE THREAD

**Issue by adrian-evo** [robocorp/robotframework-lsp#357]
E.g. if I have a module.js extension file for Browser library, as explained in Browser keywords documentation, the keywords included in this file are not resolved.

`Library    RPA.Browser.Playwright  jsextension=module.js
`

Is there a way to get those keywords resolved?

**Comment by fabioz** [comment]
Please take a look at the related FAQ: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved

If you're still not able to make it work after following it, please attach the related logging information and reopen this issue.
