### ISSUE TITLE
Provide mode to leave subprocesses running after a debug/run

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#358]
From @emanlove: In a web automation debug session, I will regular leave the window open to examine the state of the browser. I'll note it also happens with Run and not just Debug. The other concern is that any external process could be executing its own shut down code independent of the robot process and should be left to complete as designed.

**Comment by fabioz** [comment]
Closing as it's very likely that this will never be implemented given its priority vs other issues  -- note that the recommended approach for exploratory testing right now is using the Interactive console (where you can run a test and interactively issue new commands given the current state of the browser).

p.s.: I'm still open to pull requests though.

**Comment by fabioz** [comment]
As a note, the issue is that the run from the language server kills all the processes when the robot framework run finishes.

p.s.: for Robocorp Code users, the `Robot` run which uses `RCC` doesn't really have this behavior (since the lifecycle considered is that `rcc` ran and the process and all subprocesses exited, whereas for the language server, the lifecycle considered is that after Robot Framework ran, the run is finished and dangling processes are shut-down).

I'm +0 on the approach (since I tend to use/recommend the interactive console for such exploratory testing), but if others see it as useful, it's possible to raise the priority of the issue (please upvote if this is your case).

**Comment by fabioz** [comment]
Reopening since there was another comment about this (but still waiting for upvotes to raise its priority...).

**Comment by Langlais115** [comment]
Hi Fabioz,

We rase the issue on RoboCorp Forum to live the browser open after the bot run. [Here](https://forum.robocorp.com/t/browser-automatically-close-when-using-selenium/1135)
### **Script use for testing**
```
*** Settings ***
Documentation     Template robot main suite.
Library                  RPA.Browser.Selenium    auto_close=${FALSE}

*** Tasks ***
Launch Browser
    Open Available Browser    https://robotsparebinindustries.com/
    Input Text    id:username   maria
    Input Text    id:password    thoushallnotpass
    Submit Form
```
    - rpaframework==12.5.1


### **Issue description:**
The browser auto-close at the end of the run when started with VC Code Run icon


### **Test done**
**Test 1**
When starting this script with **rcc** command, **RobocorpLab** or the **VS Code** "_command pallet_"
The browser stays open as expected.


**Test 2**
When starting this script with **VS Code** **Run icon** the browser auto-close at the end of the run.
Which is NOT what we are expecting.

**Comment by saurabhkingp** [comment]
This is still not fixed and it is annoying that after my whole script execution it closes automatically and to see what happened in the browser I need to use sleep on every script at end of execution.
Please fix this for VS Code

**Comment by bobafett6494** [comment]
I am still facing the same issue when running from VS Code icon that the browser auto-closes despite the imported arg auto_close=${FALSE} in Library. I am using VS Code 1.69.1 on Windows.

**Comment by fabioz** [comment]
This is still not in a final release.

I've just done a new pre-release with it though: `0.48.4`, so, anyone that wants to check this feature can use the pre-release until this makes it into a final release (the plan is doing a new release next week).

**Comment by fabioz** [comment]
Note: it's possible to enable the previous behavior by setting an environment variable such as: `RFLS_KILL_ZOMBIE_PROCESSES=1`.
