### ISSUE TITLE
(VSCode) robot.pythonpath option not added at libspec generation to PYTHONPATH

### ISSUE THREAD

**Issue by katjie** [robocorp/robotframework-lsp#359]
**Describe the bug**
The closest I could find to this bug was https://github.com/robocorp/robotframework-lsp/issues/320 but the exact problem was not the same.

My project structure is:
![image](https://user-images.githubusercontent.com/19191177/119127939-4646a500-ba35-11eb-940f-620c3c642691.png)

Inside .vscode/settings.json, I have:
`"robot.pythonpath": ["${workspaceFolder}\\libraries"]`

And inside MyResource.resource I have:
```
*** Settings ***
Library  MyLibrary

*** Keywords ***
Robo Keyword
    Fake Keyword
```

In this example, Fake Keyword is defined in libraries/MyLibrary.py. Fake Keyword is underlined with red squiggly lines, telling me that the keyword is undefined. If I open the Robot Framework Output window on VSCode, it tells me:

```
lsp: 2021-05-21 13:05:05 UTC pid: 22540 - ThreadPoolExecutor-1_1 - EXCEPTION - robotframework_ls.impl.libspec_manager
Error creating libspec: MyLibrary.
Return code: 252
Output:
Importing library 'MyLibrary' failed: ModuleNotFoundError: No module named 'MyLibrary'

Traceback (most recent call last):
  None

PYTHONPATH:
  c:\tools\svn\dl\robotframework
  C:\Users\cbb\AppData\Local\Programs\Python\Python37-32\python37.zip
  C:\Users\cbb\AppData\Local\Programs\Python\Python37-32\DLLs
  C:\Users\cbb\AppData\Local\Programs\Python\Python37-32\lib
  C:\Users\cbb\AppData\Local\Programs\Python\Python37-32
  C:\Users\cbb\AppData\Roaming\Python\Python37\site-packages
  C:\Users\cbb\AppData\Local\Programs\Python\Python37-32\lib\site-packages

Try --help for usage information.

Traceback (most recent call last):
  File "c:\Users\cbb\.vscode\extensions\robocorp.robotframework-lsp-0.16.0\src\robotframework_ls\impl\libspec_manager.py", line 894, in _cached_create_libspec
    cwd=cwd,
  File "c:\Users\cbb\.vscode\extensions\robocorp.robotframework-lsp-0.16.0\src\robotframework_ls\impl\libspec_manager.py", line 774, in _subprocess_check_output
    return subprocess.check_output(*args, **kwargs)
  File "C:\Users\cbb\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\cbb\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\cbb\\AppData\\Local\\Programs\\Python\\Python37-32\\python.exe', '-m', 'robot.libdoc', 'MyLibrary', 'C:\\Users\\cbb\\.robotframework-ls\\specs\\v2\\a30be635_4.0\\user\\MyLibrary.libspec']' returned non-zero exit status 252.
```

I can see from this that there is no "libraries" folder in the PYTHONPATH. From the subprocess.CalledProcessError it looks as though no --pythonpath option is passed to libdoc, which is why I suspect that the robot.pythonpath option I defined in settings.json is not taken into account during the libspec generation. If I run from my terminal
`python -m robot.libdoc --pythonpath libraries MyLibrary MyLibrary.libspec`

Then using that libspec solves the problem. However, I am not sure if it should be expected that I generate this libspec myself every time I create a new library inside the libraries folder.

**To Reproduce**
I've attached a zip folder with the files that can reproduce the problem:
[robotframework-lsp.zip](https://github.com/robocorp/robotframework-lsp/files/6522169/robotframework-lsp.zip)

1. Open folder in VSCode
2. Try to open MyResource.resource and wait for lsp to load, this will show Fake Keyword as undefined

**Expected behavior**
I expect the pythonpath configured in the settings.json to be taken into account during the generation of the libspec, so that the keyword definition can be resolved.

**Versions:**
 - OS: Windows 10
 - Robot Framework Version 4.0.2
 - Robot Framework Language Server Version 0.10.0 (extension of VSCode)
 - VSCode 1.56.2

**Logs**
[robotframework_ls.lsp.23484.log](https://github.com/robocorp/robotframework-lsp/files/6522208/robotframework_ls.lsp.23484.log)

**Comment by fabioz** [comment]
The issue is that `${workspaceFolder}` isn't currently supported, you need to use full paths there.

Keep an eye open for: https://github.com/robocorp/robotframework-lsp/issues/239, which is the issue where this is being tracked (I plan to work on that soonish...).

**Comment by katjie** [comment]
@fabioz Oh thanks, I had not seen that issue. That explains it! PS after you wrote, I tried it out, and just having `libraries` instead of `${workspaceFolder}\\libraries` works, so until then I have a work around.

Thanks again :-)
