### ISSUE TITLE
Robot framework LS can enter a bad state where BuiltIn keywords are no longer recognised if a builtin.py library is available

### ISSUE THREAD

**Issue by Serhiy1** [robocorp/robotframework-lsp#364]
**Describe the bug**
After opening multiple robot files one after the other (23 robot suites in my environment), the robot language server enters a bad state where the BuiltIn keywords are no longer recognised. 

This problem seems to persist even after: 
- Reloading the visual studio code instance 
- Reinstalling the language server plugin 
- Rebooting the host machine

The only fix seems to be deleting the `.robotframework-ls/specs/v2/{uid}/user` folder and rebooting visual studio.

**To Reproduce**

I don't think I can share the test suites to reproduce this, as it's work related. But each suite averages out to 180 lines in length. 

**Screenshots**
Example of the syntax highlighting issues 
![image](https://user-images.githubusercontent.com/28574129/119513826-7612e700-bd6c-11eb-9698-0463e9a30640.png)

**Versions:**
 - OS: windows 10 and Linux
 - Robot Framework Version: 4.0.2 and 3.2 
 - Robot Framework Language Server Version: 0.17.0
 - Client Version: Visual studio code

**Comment by fabioz** [comment]
Note: I removed the logs from the description since they can contain parts of your code (and you mentioned it shouldn't be shared).

Anyways, I took a quick look at the logs and apparently you have a library: `f:\\desktop\\avid\\testing\\robot\\tests\\libs\\assetsV2\\builtin.py`

I think that what's happening is that your internal library is shadowing the default builtin library... is there a particular reason you call it `builtin.py` or could it be renamed?

**Comment by fabioz** [comment]
p.s.: I don't think it's related to the number of files opened, rather it's probably due to the shadowing of the standard builtin library (so, I'm renaming the ticket to reflect that).

**Comment by Serhiy1** [comment]
Interesting, I think you're right that shadowing `builtin.py` is the cause of the issue. But the defective behaviour definitely revolved around the amount of files I opened.

If I directly open the robot suite that uses the shadowing `builtin.py` file, everything is parses correctly, even pressing F12 on the import even brings me to the correct file.  If I open the stated number of other suites, then I suddenly get this issue.  

Renaming the shadowing `builtin.py` to `_builtin.py`, and then reloading the window seems to cause this problem to go away.

Hopefully this is useful information.

Thanks for your help.
