### ISSUE TITLE
LSP doesn't recognize resource file with variable in path, but does for library

### ISSUE THREAD

**Issue by eduardfarkas** [robocorp/robotframework-lsp#366]
**Describe the bug**
LSP doesn't recognize resource file with variable in path, but does for library.
In my case, i set global variable in __init__.robot some path and then use it in test suites. 

Tests run just fine, but keywords are not recognized, only those from python library.

(tested in IntelliJ IDEA and VSC)

**To Reproduce**
1) Set global variable with path to some directory with keywords.
2) use it in test suite

**Expected behavior**
Recognize keywords in such defined files

**Screenshots**
__init__.robot
- https://gyazo.com/dd39cac0904ca87b77a9e7ed954f32f6
 
test suite file:
- https://gyazo.com/249c34a375a9888eb0547ac4b6dfce9e

**Versions:**
 - OS: w10
 - Robot Framework Version 4.0.2
 - Robot Framework Language Server Version 0.17.0
 - Client Version VSC 1.56.2

**Comment by fabioz** [comment]
This is expected... to be able to resolve those, you need to specify the `LIBRARIES` and `RESOURCES` you use as `robot.variables` (the language server can't really make sense of runtime information).

See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-specify-a-variable-needed-to-resolve-some-library-or-resource-import for details.
