### ISSUE TITLE
devdata/env.json doesn't seem to be picked up when debugging `python` robots

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#367]

**Comment by mikahanninen** [comment]
This is the code that fails in VSCode when run with Robocorp Code **debug**  mode. 

````robot
"""Template robot with Python."""
from RPA.Robocloud.Secrets import Secrets


def minimal_task():
    secrets = Secrets().get_secret("email")
    print(secrets)


if __name__ == "__main__":
    minimal_task()
```

**Comment by fabioz** [comment]
Can you also provide the robot.yaml that's being used?

**Comment by fabioz** [comment]
Actually, can you zip the whole robot so that I can take a look?  (i.e.: that code is working for me)

**Comment by mikahanninen** [comment]
[slack-secrets.zip](https://github.com/robocorp/robotframework-lsp/files/6548845/slack-secrets.zip)

**Comment by fabioz** [comment]
Ok, thanks, I see the difference now (I was trying to reproduce with a Robot that ran `Robot Framework`, whereas this is a robot that runs `python`).
