### ISSUE TITLE
OUTPUT window constantly displays "[ ERROR ] option -u not recognized"

### ISSUE THREAD

**Issue by jg8481** [robocorp/robotframework-lsp#37]
Detailed description of the bug or suggestion
----------------------------------------------
While I am typing and making changes to my .robot file. I am repeatedly seeing "[ ERROR ] option -u not recognized" in the OUTPUT window. I have this installed on MacOS Mojave (10.14.6), Python Version is 3.7.5, and Robot Framework version is Robot Framework 3.2rc1.

Extension logs (attach as a file)
----------------------------------------------
[robotframework_ls.log](https://github.com/robocorp/robotframework-lsp/files/4435681/robotframework_ls.log)

Minimal example (if possible)
----------------------------------------------
Here is a screenshot of the problem.

![image](https://user-images.githubusercontent.com/14353158/78518764-64990500-778f-11ea-94d2-bbe80f73d4c1.png)

I'm also seeing additional errors when I try the code formatting shortcut (on Mac Shift + Option + F). Here is a screenshot.
![image](https://user-images.githubusercontent.com/14353158/78519736-454fa700-7792-11ea-8b4c-8b644ac9b2fd.png)

**Comment by janipalsamaki** [comment]
If set, the `Robot > Python: Executable` should point to a Python executable, not `robot` executable.Note that this option is not mandatory. It defaults to `Robot > Language-server: Python`.

**Comment by jg8481** [comment]
Ok after I received assistance from a colleague of mine. The following fixed my issue.

Originally I had the following in my settings.json file.

`{
    "robot.python.executable": "/Users/jgorospe/Library/Python/3.7/bin/robot",
    "[robotframework]": {},
    "robot.language-server.args": ["-vv", "--log-file=~/robotframework_ls.log"],
    "robot.language-server.python": "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/bin/python3.7"
}`

I changed it to the following.

`{
    "robot.python.executable": "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/bin/python3.7",
    "[robotframework]": {},
    "robot.language-server.args": ["-vv", "--log-file=~/robotframework_ls.log"],
    "robot.language-server.python": "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/bin/python3.7"
}`

After making this change, the error went away and the code completion started working.
