### ISSUE TITLE
Use project python interpreter in PyCharm by default

### ISSUE THREAD

**Issue by Noordsestern** [robocorp/robotframework-lsp#370]
**Is your feature request related to a problem? Please describe.**
When I create a new project in PyCharm, I have to set the python environment (system PATH, venv, conda, docker etc.). Afterwards, I must set explicitly the python executable in LSP settings which is double work.

**Describe the solution you'd like**
I would like LSP plugin to use the project's python interpreter by default.

**Comment by RenFraser** [comment]
I'd also find this pretty helpful. Currently, there seems to be no way to set it, which makes it hard if you have separate requirements to that of the main project.

**Comment by m8nky** [comment]
In addition, my development environment incl. robotframework is deployed to docker. Would be very helpful to have a full integration with the actual development environment.
Except you have some info, how to configure the current robotframework settings to access the docker image, maybe I miss something.

**Comment by fabioz** [comment]
Closing as duplicate of: https://github.com/robocorp/robotframework-lsp/issues/427
