### ISSUE TITLE
Consider library arguments when creating libspec (Keywords may be available only given some arguments)

### ISSUE THREAD

**Issue by IlfirinPL** [robocorp/robotframework-lsp#373]
**Describe the bug**
When import FakerLibrary with additional argument in this case " locale=PL" additional Keywords should be visible ex. "Pesel"

**To Reproduce**
1.  Import "Library           FakerLibrary    locale=PL"
2.  Search for keywords "Pesel"

Example Code
[Bug.txt](https://github.com/robocorp/robotframework-lsp/files/6554559/Bug.txt)

**Expected behavior**
Additional Keywords should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/1460956/119838933-164f4400-bf04-11eb-99af-b29074b99e53.png)

![image](https://user-images.githubusercontent.com/1460956/119839094-32eb7c00-bf04-11eb-9650-d24f05dc2645.png)

**Versions:**
 - OS: [ Windows 10]
 - Robot Framework Version  4.0.2
 - Robot Framework Language Server Version .17.0
 - Client Version  VSCode 1.56.2

**Logs**
![image](https://user-images.githubusercontent.com/1460956/119839573-8f4e9b80-bf04-11eb-81da-0816cd3c5204.png)

**Comment by fabioz** [comment]
Ha, indeed, having different keywords based on different arguments is quite tricky (I must say wasn't aware this would be something expected).

I'll have to investigate how to support that...

In the meanwhile you can manually generate a .libspec using those arguments (or manually editing it to add what's needed) -- see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved for details.
