### ISSUE TITLE
Skip BuiltIn keyword undefined

### ISSUE THREAD

**Issue by adrian-evo** [robocorp/robotframework-lsp#376]
I started using 'Skip' and 'Skip If' new keywords from Robot Framework version 4.0.3 and they are reported by LS as undefined. Is this as expected or maybe not implemented yet? Thanks.

**Comment by fabioz** [comment]
I'm not sure, I can't really reproduce this issue (it does work for me).

Can you provide the logging for your run to be able to diagnose why this is happening? See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md for details on how to get the logs.

**Comment by adrian-evo** [comment]
It seems the log contains too much information so I cannot send it. However, when I create a totally new file within VS Code with no project opened, and set the language to RF it works, and also on Robocorp type of project. But on my existing pure RF project created previously and opened in VS Code it is not working. I guess it is related to my environment so I will investigate further.

**Comment by fabioz** [comment]
One thing to investigate could be closing VSCode and manually removing the contents of:

`%USERPROFILE%/.robotframework-ls`

and then restarting (this would effectively remove all the caches from the language server)

Also, check that you don't have any library named `builtin.py` from yourself (i.e.: https://github.com/robocorp/robotframework-lsp/issues/364).

**Comment by fabioz** [comment]
Also, you can take a look at the logs yourself and check that you're actually using the python executable / Robot Framework that you expect...

**Comment by adrian-evo** [comment]
It seems the issue was that the project folder contained a folder named libspecs (I think generated automatically by RED Editor) and this folder contained BuiltIn.libspec generated from previous RF that does not have the new keywords. After removing this libspecs folder it is working now. Hopefully this info is useful and the issue can be closed.

**Comment by fabioz** [comment]
Ok... it does make sense (any manually-created libspec in the workspace takes precedence over libspecs created automatically).
