### ISSUE TITLE
Cannot jump to definition of files that are imported as variables 

### ISSUE THREAD

**Issue by Serhiy1** [robocorp/robotframework-lsp#381]
**Describe the bug**
In the robot framework, python files can be imported using the `variables` keyword: https://baishanlu.gitbooks.io/robot-framework-cn-en-user-manual/content/python_27_regular_expressions/27resource_and_variable_files.html

The robot framework language server appears to not recognise this. 

![image](https://user-images.githubusercontent.com/28574129/120213736-79eeaf80-c22b-11eb-9b7e-07a51b5f3133.png)

Changing the keyword from `variables` to `Resource` gives the expected behaviour.

![image](https://user-images.githubusercontent.com/28574129/120213896-adc9d500-c22b-11eb-8d0a-be2021078b71.png)

**To Reproduce**
[robot_example.zip](https://github.com/robocorp/robotframework-lsp/files/6571163/robot_example.zip)

1. open the example folder in VS code. 
2. Try pressing f12 on `test_variables.py`
3. Try Pressing f12 on `test_resources.py`

**Expected behaviour**
The behaviour between the two should be identical 

**Versions:**
 - OS: windows 10 and linux
 - Robot Framework Version: latest
 - Robot Framework Language Server Version: latest
 - Client Version: Vs code

**Comment by eduardfarkas** [comment]
This applies also on yaml files.
![image](https://user-images.githubusercontent.com/35013013/120281808-b537bf80-c2b9-11eb-9847-13224a10a03d.png)
