### ISSUE TITLE
Code completion of keywords are shown as classes not as methods

### ISSUE THREAD

**Issue by Snooz82** [robocorp/robotframework-lsp#39]
Hi @fabioz 

at the moment the keywords are shown with a "class"-symbol in VSCode and also in PyCharm.
i would expect that it is shown as method/function.

Maybe we should discuss this typing with Pekka.

some ideas:

Keywords -> functions or methods (we could make a difference between "User-Keywords" from Resources and "Library-Keywords" from python/Java Libraries.
I think libraries (python/java) could be methods because they are often related to classes/objects. And User Keywords could be functions, because they are definitely not part of a class.

Variables -> Variables

[Return] -> is a language command like ``break``, ``return`` or ``raise``

*** Settings ***  -> could maybe completed as "class" even if it is not a class...

@pekkaklarck what do you think?

regards
René

**Comment by fabioz** [comment]
Those changes seem to make sense for m (and changing the type should be straightforward).

**Comment by pekkaklarck** [comment]
- Keywords should definitely be methods/functions. 
- Not sure what's best for sections. What are the options?
- I think all settings should use same type, even `[Return]`. I hope in the future we could add separate `RETURN` control element like `FOR` and ` IF/ELSE` to replace it.

**Comment by Snooz82** [comment]
```
export namespace CompletionItemKind {
	export const Text = 1;
	export const Method = 2;
	export const Function = 3;
	export const Constructor = 4;
	export const Field = 5;
	export const Variable = 6;
	export const Class = 7;
	export const Interface = 8;
	export const Module = 9;
	export const Property = 10;
	export const Unit = 11;
	export const Value = 12;
	export const Enum = 13;
	export const Keyword = 14;
	export const Snippet = 15;
	export const Color = 16;
	export const File = 17;
	export const Reference = 18;
	export const Folder = 19;
	export const EnumMember = 20;
	export const Constant = 21;
	export const Struct = 22;
	export const Event = 23;
	export const Operator = 24;
	export const TypeParameter = 25;
}
```

These are the available CompletionItemKinds.

I would propose:
Library Keywords = 2 (Method)
User Keyword = 3 (Function)
${Variables} = 6 (Variable)
[Settings] = ?
*** Sections *** = ? Maybe 7 (Class)

**Comment by pekkaklarck** [comment]
I mostly agree what @Snooz82 wrote about class usage but would change/add these:

- All variables, including built-ins like '${EMPTY}` as `Variable`.
