### ISSUE TITLE
Robot Framework Language server - 0.18.0

### ISSUE THREAD

**Issue by judahshaik** [robocorp/robotframework-lsp#390]
Hi ,
I am getting the same error with the "Robot Framework Language server - 0.18.0" .robot files are recognised with this plugin but no auto-suggestions not recognising keywords.

I have uninstalled all Intellibot related plugins.

RF Language server

![RF Language server](https://user-images.githubusercontent.com/85666435/121644442-9e128200-cab0-11eb-87ed-4ab3ff0a026a.JPG)

**Comment by fabioz** [comment]
Thanks for the report... it seems like there's some issue initializing the language server itself.

Can you check if you have any non-empty `.log` files in: `%userprofile%/.robotframework-ls` (you can just paste that in the explorer and it should show you the folder) and if you do, can you attach them to this issue?

**Comment by judahshaik** [comment]
Yes, there are multiple files with .log extension which are empty and it is 0kb in size.
 
.intellij-rf-ls-2021-06-10 16_10.log
.intellij-rf-ls-2021-06-11 11_38.log
.intellij-rf-ls-2021-06-11 11_44.log
.intellij-rf-ls-2021-06-11 11_50.log
.intellij-rf-ls-2021-06-11 11_58.log
.intellij-rf-ls-2021-06-11 16_54.log
.intellij-rf-ls-2021-06-11 18_10.log

also there is a .cache folder which is empty too.

[.robotframework-ls.zip](https://github.com/robocorp/robotframework-lsp/files/6638474/default.robotframework-ls.zip)


I've tried uninstall and install the same plugin, but still these files are empty.

what to do now :(

**Comment by fabioz** [comment]
Ok, let's start by getting the logs from the extension then: 

Please follow the instructions at:
https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md

To get the actually generate log info (those -- empty files -- would have things printed to `stderr`, but as nothing is being printed, let's collect the actual logs to know what's happening).

**Comment by fabioz** [comment]
Closing as there was no additional feedback.
