### ISSUE TITLE
Tag `EXPORTS` is not matched when running suite 

### ISSUE THREAD

**Issue by eduardfarkas** [robocorp/robotframework-lsp#392]
**Describe the bug**
I have a test suite where i force tag `EXPORTS`, when running tests from console, no tests are matched

**To Reproduce**
1. force tag `EXPORTS` on some suite
2. run suite

**Expected behavior**
run all tests in suite

**Screenshots**
![image](https://user-images.githubusercontent.com/35013013/123401261-e6e53300-d5a6-11eb-97f7-46cfff6530b6.png)

![image](https://user-images.githubusercontent.com/35013013/123401116-c1f0c000-d5a6-11eb-84e5-a4793a710ab2.png)

**Versions:**
 - OS: w10
 - Robot Framework Version 4.0.2
 - Robot Framework Language Server Version 0.18.0
 - Client Version VSC

**Comment by fabioz** [comment]
@eduardfarkas if you're running `robot` directly from the console, I don't really get how this is related to the language server, so, I'm closing the issue as this seems to be a general `Robot Framework` issue (and thus, should be reported to `Robot Framework` itself).
