### ISSUE TITLE
In VSCode, buttons "run" and "debug" should allow configuring the output folder

### ISSUE THREAD

**Issue by zampa00** [robocorp/robotframework-lsp#393]
**Is your feature request related to a problem? Please describe.**
When using the run and debug buttons inside VSCode 
![Screenshot 2021-06-25 at 17 34 41](https://user-images.githubusercontent.com/7748740/123449162-b075db00-d5db-11eb-8375-8458fcebfa72.png)
the output files are generated in the project root folder, and I can't figure out how to specify a different folder.
Moreover, I do have a valid launch.json configured with my desired output folder, and it works correctly if I launch it via the "Run and debug" tab in VSCode.

**Describe the solution you'd like**
I'd like these buttons to work as the "Run and debug" tab

**Comment by fabioz** [comment]
You can configure the launch configuration as you want.

See the FAQ for information on how to do that: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-configure-the-launch-from-a-code-lensshortcut
