### ISSUE TITLE
Cannot debug tests when using a virtual python environment

### ISSUE THREAD

**Issue by dcrblack** [robocorp/robotframework-lsp#395]
**Describe the bug**
When trying to use the debugger to debug tests in vscode, it fails with the following error:
```
Error. Expected: ./.venv/bin/python to exist.
```

This is also the case if you set `robot.language-server.python` to a python virtual environment

**To Reproduce**
1. Create a virtual environment to use `python -m venv .venv`
2. Source the environment `source .venv/bin/activate
3. Set either `robot.language-server.python` or `robot.python.executable` to the path to the python virtual environment
4. Attempt to run/debug the tests through vscode
5. See the `Error. Expected: ./.venv/bin/python to exist.` error.

**Expected behavior**
A virtual python environment should work with the language server to allow tests to be ran/debugged through vscode.

**Screenshots**
![76106CB7-94A8-426B-A273-BBBDC0AF3FD7_4_5005_c](https://user-images.githubusercontent.com/22531177/124149478-88c5bd80-da88-11eb-8481-ea43ddb3526f.jpeg)

**Versions:**
 - OS: macOS Big Sur 11.4
 - Robot Framework Version 4.0.3
 - Robot Framework Language Server Version 0.18
 - Client Version VSCode 1.57.1

**Logs**
[robotframework_ls.remote_fs_observer.56210.log](https://github.com/robocorp/robotframework-lsp/files/6749272/robotframework_ls.remote_fs_observer.56210.log)

**Comment by fabioz** [comment]
Are you specifying `robot.language-server.python` / `robot.python.executable` as a full path? (relative paths aren't accepted)

**Comment by dcrblack** [comment]
> Are you specifying `robot.language-server.python` / `robot.python.executable` as a full path? (relative paths aren't accepted)

I wasn't, which was the problem (It works now when providing an absolute path).
It would be better to provide a relative path or make use of vscode variables like `${workspaceFolder}` so I can check in `settings.json` when reasonable defaults.
Unfortunately, this isn't supported in vscode at the moment https://github.com/microsoft/vscode/issues/2809#.

**Comment by fabioz** [comment]
You can use `${workspaceFolder}` already.

i.e.: variables are properly expanded: https://github.com/robocorp/robotframework-lsp/blob/7bf168b54dc3a3491b26731dfa7f5338ba79f637/robotframework-ls/vscode-client/src/expandVars.ts#L13

Still, you can't use a relative path.

**Comment by fabioz** [comment]
Also see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-use-variables-in-settings
