### ISSUE TITLE
Enable general variable substitution in robot language server configuration

### ISSUE THREAD

**Issue by ian-h-chamberlain** [robocorp/robotframework-lsp#399]
**Is your feature request related to a problem? Please describe.**
The [configuration documentation](https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-use-variables-in-settings) for the language server indicates that _some_ VScode variables are allowed in configuration, but not many, and these appear to be non-standard (`${workspace}` is not recognized in any other extension I have ever used, and `${workspaceRoot}` has been deprecated for some time since VSCode introduced multi-root workspaces). 

**Describe the solution you'd like**
Expand the variable substitution to match the VScode "standard" [set of variables](https://code.visualstudio.com/docs/editor/variables-reference), or at least a larger subset of them.

There is an open issue https://github.com/microsoft/vscode/issues/46471 for exposing an API in vscode itself to handle these variables, but unfortunately it hasn't seen much movement as far as I can tell.

Someone has created [a library](https://www.npmjs.com/package/vscode-variables) which appears to support many of the major variable types, so perhaps that is a simpler option to implement this quickly.

**Describe alternatives you've considered**
For now this is not an issue for me personally, because I use a single-root workspace, but in some use cases I think it could be problematic for multi-root workspaces or other types of variables. However, it would be nice to be consistent with the ecosystem as a whole

**Comment by ottoaho** [comment]
I use an environment variable in my settings for selecting the python interpreter:
`"python.pythonPath": "${env:VSCODE_PYTHON_VENV}\\Scripts\\python.exe"`

Ideally, I could configure `robot.language-server.python` similarly, which currently doesn't work, presumably due to this issue.
![image](https://user-images.githubusercontent.com/10016830/127470118-60f161cd-7f71-4373-b95d-fa36a796cbdc.png)

**Comment by fabioz** [comment]
For the language server it needs `${env.` (instead of `${env:`). I've just did a change to allow accepting `${env:`, but that'll only be available in the next release (so, in the meanwhile, please use `${env.` (instead of `${env:`).

**Comment by fabioz** [comment]
@ian-h-chamberlain I've closed the issue after adding support to `${workspaceFolder}` and accepting `${env:}` besides `${env.}`.

Note that `${workspaceFolder}` is mostly the same as the deprecated `${workspaceRoot}` and on multi-folder workspaces for all purposes it's the path of the first workspace folder imported in the workspace (this is the same approach for VSCode and is also the same approach given in the library you linked).

If you need additional support for some variable, please explain your specific use-case (in general, most variables seem to be related on the open editor/selection/etc, which doesn't seem to make much sense on the places where the variables are currently used).

Note: I'm still open to add support for more variables, but this would require a specific use-case (also note that the library is a javascript library running on the context of VSCode, whereas the language server is a python library... while initially I could add support for something only in VSCode, alternatives need to be available for other clients too).
