### ISSUE TITLE
Support Intellij 2021.2

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#406]

**Comment by fabioz** [comment]
See: https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html?from=jetbrains.org#intellij-platform-based-products-of-recent-ide-versions for intellij version numbers.

**Comment by Hristovski** [comment]
This is resolved, right?

**Comment by fabioz** [comment]
Yeap, this was fixed in: https://github.com/robocorp/robotframework-lsp/commit/c145df54e68a81c2e7c0091afef0e8a8ffb7cd79

Thanks for the reminder.
