### ISSUE TITLE
[Question] How to configure `run` output directory

### ISSUE THREAD

**Issue by 4nif** [robocorp/robotframework-lsp#409]
**Describe the bug**
How to configure output of the run button from the plugin in vscode?
Using terminal I can use `robot -d log/my_log`

**Screenshots**
![image](https://user-images.githubusercontent.com/31293565/127740981-136b8acd-b877-4472-808b-75c449839f8e.png)

**Comment by tuyenlq** [comment]
I have same question 
 how to configure output, variablefile env run test on dev, qc.

**Comment by fabioz** [comment]
Please take a look at: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-configure-the-launch-from-a-code-lensshortcut

**Comment by 4nif** [comment]
@fabioz I have add `launch.json` and still not working when i click Run

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "robotframework-lsp",
            "name": "Robot Framework: Launch template",
            "request": "launch",
            "terminal": "integrated",
            "args": ["-d report", "-loglevel TRACE"]
        }
    ]
}
```

Is something wrong with my config?

**Comment by fabioz** [comment]
> When I have virtual env, clicking `Run` does not execute robot from virtual environment, and always getting an error undefined keyword

It seems your issue is that you haven't configured the language server itself to use the proper python environment you want... can you create a new issue with more information with more details as it seems unrelated to this?
i.e.: Where's your virtual environment located, how are you configuring the language server?

**Comment by 4nif** [comment]
Thanks, @fabioz it works now after configuring language server to use python environment

I have a question related to `launch.json` for the robot option that reference to the directory I need to remove space e.g 
if I add like this `"args": ["-d report", "-loglevel TRACING"]` when I click run it will create a new report directory with space and use `-loglevel TRACING for file name` in the debug console I see something like this

```
Output:  c:\robocorp-testing\ report\output.xml
Log:     c:\robocorp-testing\ report\oglevel TRACING.html
Report:  c:\robocorp-testing\ report\report.html
```

It works as expected if args format is like this `"args": ["-dreport", "-loglevel TRACING"]` without space after `-d`

**Comment by fabioz** [comment]
The issue is that each parameter must be at a separate string.

i.e.: it should be `["-d", "report", "-loglevel", "TRACING"]`, otherwise something as `"-d report"` would be considered a single argument instead of 2 arguments.

**Comment by 4nif** [comment]
Thanks @fabioz working fine now after split to separate string 👍
