### ISSUE TITLE
Running suites/test with built in function should respect run configuration

### ISSUE THREAD

**Issue by anton264** [robocorp/robotframework-lsp#410]
**Is your feature request related to a problem? Please describe.**
Running tests locally involves running with different configurations to target different environments. In the debug tab this can easily be set by defining them in the launch.json file. When clicking "Run" or "Debug" in the editor next to the test name or top of the file this configuration is not used which makes the function limited

**Describe the solution you'd like**
When clicking "run" or "debug" the config chosen in the "Run and debug" tab in vscode should be used.

![image](https://user-images.githubusercontent.com/10194266/128028112-1f2ac1db-a36f-4b22-a45f-cb89c7e77ad4.png)
![image](https://user-images.githubusercontent.com/10194266/128028370-c15963cc-f222-45b1-a427-6eb9fe2d8453.png)

**Comment by fabioz** [comment]
It's already possible to configure the run done by the `run/debug` from the code lens.

See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-configure-the-launch-from-a-code-lensshortcut for details.

**Comment by anton264** [comment]
Thank you for pointing that out. I do however feel that the functionality is a bit limited. I often want to be able to switch between dev, staging and prod environments. I guess I could make a custom input for that but it would be nice if we could just use the config selector in vsCode @fabioz

**Comment by fabioz** [comment]
Well, unfortunately what you are suggesting is not possible (VSCode has no API to know about the currently selected item in the launch config).

So, the options are really only using the code-lens and customizing the template or running a selected launch (in which case you have to specify the test specifically for the launch).

**Comment by fabioz** [comment]
Maybe one thing that could be feasible would be replacing variables to act as the test name/test path based on the currently active editor (in which case you could specify those variables in the launch and then you could create a launch which runs based on the current test/task, which would be computed based on where your cursor is).

So, you could have something as `${robotTestName}` and use it in a regular launch (where it'd be decided based on your cursor position).

If you think something like that would be interesting, please create a new issue for it.

**Comment by fabioz** [comment]
As a note, you could use the `${selectedText}` right now in a test to simulate something like that (with the downside being that you have to select the text and not just place the cursor in a test name).

**Comment by anton264** [comment]
I think using inputs is the most sensible for now, it will always ask which one but you can use a default

`{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "robotframework-lsp",
            "name": "Robot Framework: Launch template",
            "request": "launch",
            "terminal": "integrated",
            "args": ["--argumentfile", "/path/to/arguments/${input:Environment}.txt"]
        }
    ],
    "inputs": [
        {
            "type": "pickString",
            "id": "Environment",
            "description": "Which environment do you want to test?",
            "options": [
                "local",
                "dev",
                "staging",
                "production"
            ],
            "default": "dev"
        }
        
    ]
}`
