### ISSUE TITLE
variable Syntax highlighting does not work with embedded arguments

### ISSUE THREAD

**Issue by Serhiy1** [robocorp/robotframework-lsp#415]
**Describe the bug**
Robot framework supports embedded arguments into keywords. Defining the keywords produces the correct syntax highlighting. But usage does not  

**To Reproduce**
This is based off the example in the Robot framework docs
```robot
*** Settings ***
Documentation    Syntax highlighting example
Library    Process


*** Test Cases ***
Example
    [Documentation]    Syntax highlighting example

    ${cmd}=    Set Variable    ls
    ${opt}=    Set Variable    -lh

    I Execute ${cmd}
    I Execute ${cmd} With ${opt}


*** Keywords ***
I Execute ${cmd}
    [Documentation]    Syntax highlighting example
    Run Process    ${cmd}    shell=True

I Execute ${cmd} With ${opts}
    [Documentation]    Syntax highlighting example
    Run Process    ${cmd} ${opts}    shell=True
```
Ironically, the GitHub syntax highlighting correctly highlights the variables but LSP in VSCode does not

![image](https://user-images.githubusercontent.com/28574129/129046814-00d501e2-dc9e-4b6a-b790-ea9e666d66ab.png)

**Expected behaviour**
The variables should be highlighted inside the keywords during usage in the test cases. Like GitHub is doing

```robot
*** Test Cases ***
Example
    ${cmd}=    Set Variable    ls
    ${opt}=    Set Variable    -lh

    I Execute ${cmd}
    I Execute ${cmd} With ${opt}
```

**Comment by fabioz** [comment]
This was done in: https://github.com/robocorp/robotframework-lsp/commit/0eeeca5ee36d6c6dc5247c48e3ff817ae381cd9a (released in version: `0.42.0`).
