### ISSUE TITLE
[Intellij] Dialog to select Python executable is not accepting `~` and variables

### ISSUE THREAD

**Issue by DetachHead** [robocorp/robotframework-lsp#418]
**Describe the bug**
two issues:
1. the "Language Server Python" field says that the default behavior is to search for python on the PATH, but it doesn't allow you to leave the field blank
   ![image](https://user-images.githubusercontent.com/57028336/129146137-44ad890b-3ae2-4af3-9452-972842adc9ce.png)

2. even when you specify a path to the pythonnexecutable, it thinks it doesn't exist
    ![image](https://user-images.githubusercontent.com/57028336/129147824-c4a03bb1-6ba0-4cf0-bc68-3df779c58653.png)

**Versions:**
 - OS: macos 11.4
 - Robot Framework Version 4.1
 - Robot Framework Language Server Version 0.20.0
 - Client Version intelliJ IDEA ultimate 2021.2

**Comment by fabioz** [comment]
The issue here is that it is not making the substitution for `~`.

If you use the full path on the filesystem it should work. I'll update the title accordingly.

**Comment by fabioz** [comment]
As a note, if python was found in the `PATH`, that dialog wouldn't even be shown (so, it's only showing that dialog because it couldn't be found).

**Comment by DetachHead** [comment]
in that case it should use the python interpreter set in the project. would that be possible?

![image](https://user-images.githubusercontent.com/57028336/129204482-2920d245-9f19-4337-b0f8-83a91d975215.png)

otherwise, like in #416 it's not feasible to commit the project config because it's tied to a python interpreter defined on my machine

**Comment by fabioz** [comment]
Unfortunately that's not currently possible (the plugin isn't aware of the PyCharm plugin, and thus cannot read its config -- it only depends on Intellij).

Also, you're correct, you should not commit to the project (unless all your co-workers share the same structure you have).
