### ISSUE TITLE
Can't go to definition for keywords while "Resource" contain built-in variables like ${EXECDIR}

### ISSUE THREAD

**Issue by sunbrown** [robocorp/robotframework-lsp#425]
**Screenshots**
![Snipaste_2021-08-24_14-42-16](https://user-images.githubusercontent.com/11946452/130570121-c15b2e93-c27a-4fe4-b467-44571309fac4.png)

**Versions:**
OS: [ Windows 10]
Robot Framework Version [ 3.2.1]
Robot Framework Language Server Version [0.21.0]
Client Version [PyCharm 2021.1.2]

**Comment by fabioz** [comment]
This is actually a duplicate of https://github.com/robocorp/robotframework-lsp/issues/263 (see that issue for a workaround).

**Comment by sunbrown** [comment]
Nice! Thanks!
