### ISSUE TITLE
[intellij] run buttons in the gutter

### ISSUE THREAD

**Issue by DetachHead** [robocorp/robotframework-lsp#428]
**Is your feature request related to a problem? Please describe.**
it would be nice if the lsp added gutter run icons like so:
![image](https://user-images.githubusercontent.com/57028336/130706982-b7e3c28a-f390-4e03-8333-51fdcfa15374.png)

like how vscode has run and debug buttons:
![image](https://user-images.githubusercontent.com/57028336/130707126-7938d0b3-5348-497f-82d5-7e8966781e97.png)

**Comment by fabioz** [comment]
This should be handled as a part of:
https://github.com/robocorp/robotframework-lsp/issues/428

See: https://github.com/robocorp/robotframework-lsp/issues/391#issuecomment-905371419 for the current workaround to deal with this limitation.
