### ISSUE TITLE
formatter should fix formatting errors identified by robocop

### ISSUE THREAD

**Issue by DetachHead** [robocorp/robotframework-lsp#431]
**Is your feature request related to a problem? Please describe.**
robocop is cool and all, but it's annoying because it complains about a bunch of stuff that a formatter should be able to fix:

![image](https://user-images.githubusercontent.com/57028336/131055452-8c0138fa-a6a3-4218-a353-0ff25aeea09a.png)

**Describe the solution you'd like**
the formatter should fix robocopy formatting/capitalization issues and any other issues it finds that can be automatically fixed

**Describe alternatives you've considered**
https://github.com/MarketSquare/robotframework-robocop/issues/424

**Comment by fabioz** [comment]
The language server doesn't really implement the formatting, that's left for 3rd-party libraries.

There are already plans to integrate a new code-formatter (https://github.com/robocorp/robotframework-lsp/issues/273) which may handle this better though.
