### ISSUE TITLE
Error computing code lens

### ISSUE THREAD

**Issue by fdaguin** [robocorp/robotframework-lsp#438]
**Describe the bug**
Code Lens throws an error when a comment is defined between a RF section and a keyword/task/test definition.

For exemple, Code Lens is working in this situation...

```robotframework
*** Test Cases ***
Foo
    BuiltIn.Log To Console    bar
```

..but not here:

```robotframework
*** Test Cases ***
# robocop: disable=0505
Foo
    BuiltIn.Log To Console    bar
```

**To Reproduce**
1. Create a test where a comment is defined between a RF section and a keyword/task/test definition. A concrete example here:

   ```robotframework
   *** Test Cases ***
   # robocop: disable=0505
   Foo
       BuiltIn.Log To Console    bar
   ```

2. Code Lens doesn't show and an error is thrown (see screenshots and logs)
3. Remove the comment and Code Lens is appearing instantly

**Expected behavior**
Code Lens doesn't throw an error.

**Screenshots**
With no comment:
![image](https://user-images.githubusercontent.com/72013963/131486312-470b7a6a-a563-41c3-a83b-3899bc9f3b38.png)

With a comment:
![image](https://user-images.githubusercontent.com/72013963/131486379-e57705de-4cb4-4ce3-85d5-875afa420fd9.png)

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 4.1
 - Robot Framework Language Server Version: 0.21.0
 - Client Version: VSCode 1.59.1

**Logs**
I renamed `log.log.1.others.lsp.12764.api` to `log.log.1.others.lsp.12764.api.log` and `log.log.lint.lsp.6112.api` to `log.log.lint.lsp.6112.api.log`.

[log.lsp.4876.log](https://github.com/robocorp/robotframework-lsp/files/7083251/log.lsp.4876.log)
[log.remote_fs_observer.17148.log](https://github.com/robocorp/robotframework-lsp/files/7083252/log.remote_fs_observer.17148.log)
[log.log.lint.lsp.6112.api.log](https://github.com/robocorp/robotframework-lsp/files/7083259/log.log.lint.lsp.6112.api.log)
[log.log.1.others.lsp.12764.api.log](https://github.com/robocorp/robotframework-lsp/files/7083260/log.log.1.others.lsp.12764.api.log)

**Comment by fabioz** [comment]
Thank you for the report... it should be fixed now ;)

**Comment by fdaguin** [comment]
Thanks a lot @fabioz !
