### ISSUE TITLE
Getting Started Link in README.md returns 404

### ISSUE THREAD

**Issue by falk7** [robocorp/robotframework-lsp#443]
**Describe the bug**
The Getting Started Link in [README.md](https://github.com/robocorp/robotframework-lsp/blob/robotframework-lsp-0.22.0/robotframework-ls/README.md) of RoboFramework LS points to a not existing endpoint:

https://hub.robocorp.com/development/best-practices/language-server-protocol-for-robot-framework/

..resulting in an 404 Error

**To Reproduce**
1. Open README.md (link above)
2. Click Getting Started Link

**Expected behavior**
Getting started link leads to a getting started page

**Screenshots**
n/A

**Versions:**
n/A

**Logs**
n/A

**Comment by fabioz** [comment]
Thanks for the report. Just fixed the link.
