### ISSUE TITLE
[Debugger] Next does not resume the execution

### ISSUE THREAD

**Issue by JohanMabille** [robocorp/robotframework-lsp#448]
**Describe the bug**

When using the debugger in a JupyterLab (via the `xeus-robot` kernel), sending the `next`command to the debugger when the code is stopped on the last statement of a cell does not resume the execution. Instead, it seems the to behave as if the code was on any other statement.

**To Reproduce**

1. Start Jupyterlab, open a xeus-robot notebook (you can run [xeus-robot binder](https://mybinder.org/v2/gh/jupyter-xeus/xeus-robot/stable?urlpath=/lab/tree/notebooks/xrobot.ipynb for instance)
2. Set a breakpoint on the last statement of a Test Cases cell
3. Execute the cell. Then hit next when the code has stopped on the breakpoint. 

**Expected behavior**
The execution resumes, similar to debugpy and xeus-python.

It looks like an issue in the way the internal frames are generated / handled by the debugger.

**Comment by fabioz** [comment]
From what I've seen here doing a step next at the end of a test will resume (and then it'll stop at the start of the next test or setup/teardown), which seems to be correct for me (I tested it in vscode and the provided binder).

Given that, I'm closing this issue. Please reopen if you still have an issue and can provide more information/logs.
