### ISSUE TITLE
Keywords not imported correctly when resource path contains ${CURDIR}

### ISSUE THREAD

**Issue by wwuoti** [robocorp/robotframework-lsp#449]
When specifying a resource with a path containing `CURDIR`, the path to the resource is not resolved.

Consider the following example:

[curdir_import_test.zip](https://github.com/robocorp/robotframework-lsp/files/7202018/curdir_import_test.zip)

```
curdir_import_test
|--resource_folder
|   |--resource1.robot
|--test_importing_from_curdir.robot
```

resource1.robot:
```robotframework
*** Keywords ***
Keyword In Resource File
    Log To Console    Test keyword in resource file

```

But when the resource is imported in `test-importing_form_curdir.robot`
![image](https://user-images.githubusercontent.com/63700786/134148357-ae908a39-e1f4-443e-a4fb-4cf23fa0de60.png)

Removing `${CURDIR}` from the file path fixes this issue:

![image](https://user-images.githubusercontent.com/63700786/134148717-46bfc54f-f750-4374-bd9b-e8eadb5cee42.png)

**Comment by fabioz** [comment]
Well, `${CURDIR}` is something that depends on the working directory when running tests, so, I'd advise you not to use it if possible.

If you really need to use `${CURDIR}` though, then you need to specify its value to the language server.

See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-specify-a-variable-needed-to-resolve-some-library-or-resource-import for how to do that.

**Comment by fabioz** [comment]
Actually, reopening, I had misunderstood CURDIR... it maps the current directory of the .robot or .resource, thus, the language server should support it.

As a note, I don't really see any reason to use CURDIR at that context (since you can just make the path relative), but the language server should support it anyways.

**Comment by ORicardoSouza** [comment]
@wwuoti  
seems to be ok, just merge?

**Comment by horsewithnoname1985** [comment]
I had a similar issue and resolved it by specifying a custom variable in my project's `settings.json` (here on Windows):
```json
{
  "robot.variables": {
		  "RESOURCES":"C:\\my_project\\Resources",
	  }
}
```
Reference: [Configuration setting](https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/config.md#configuration-settings)

Then using it like this:

```robot
*** Settings ***
Resource      ${RESOURCES}/my_resource.robot
```

Naturally for Robot Framework, I needed to define the same variable (e.g. in a variable file) and pass it as parameter (using either `--variable` or `--variablefile`) to my robot test runs.
