### ISSUE TITLE
Crash on extension launch

### ISSUE THREAD

**Issue by Sovhan** [robocorp/robotframework-lsp#450]
**Describe the bug**
When opening a robot file and hereby launching the robocorp.robotframework-lsp extension in VSCode, no support is provided for robot framework language because of a crash.

**To Reproduce**
1. Open a .robot file with a test case depending on local libraries
2. observe  logs as such:
lsp: 2021-09-21 12:00:28 UTC pid: 361525 - Thread-1 - INFO - robocorp_ls_core.remote_fs_observer_impl
Remote FS observer stderr:   File ".vscode/extensions/robocorp.robotframework-lsp-0.23.0/src/robotframework_ls/vendored/robocorp_ls_core/libs/fsnotify_lib/fsnotify/__init__.py", line 238, in <lambda>
lsp: 2021-09-21 12:00:28 UTC pid: 361525 - Thread-1 - INFO - robocorp_ls_core.remote_fs_observer_impl
Remote FS observer stderr:     not self.accepted_file_extensions or path_name.endswith(self.accepted_file_extensions)
lsp: 2021-09-21 12:00:28 UTC pid: 361525 - Thread-1 - INFO - robocorp_ls_core.remote_fs_observer_impl
Remote FS observer stderr: TypeError: endswith first arg must be str or a tuple of str, not list

and in said lambda, follow accepted_file_extensions member to see its content, which is () and does not seem to be modified?

**Expected behavior**
Load the extension without crashing with the same behaviour as precedent versions.

**Versions:**
 - OS: Linux pop-os 5.11.0-7633-generic base Ubuntu 20.04 GNU/Linux
 - Robot Framework Version: 4.1.1 (Python 3.8.10 on linux)
 - Robot Framework Language Server Version: 0.23
 - Client Version: VSCode 1.60.1

**Logs**
See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md for details on how to collect the logs.
[robot_logs.1.others.lsp.361710.api.log](https://github.com/robocorp/robotframework-lsp/files/7202328/robot_logs.1.others.lsp.361710.api.log)
[robot_logs.2.lsp.368418.api.log](https://github.com/robocorp/robotframework-lsp/files/7202329/robot_logs.2.lsp.368418.api.log)
[robot_logs.lint.lsp.361610.api.log](https://github.com/robocorp/robotframework-lsp/files/7202330/robot_logs.lint.lsp.361610.api.log)
[robot_logs.lsp.361525.log](https://github.com/robocorp/robotframework-lsp/files/7202331/robot_logs.lsp.361525.log)
[robot_logs.remote_fs_observer.361565.log](https://github.com/robocorp/robotframework-lsp/files/7202332/robot_logs.remote_fs_observer.361565.log)

**Comment by fabioz** [comment]
I'm sorry about that, I've just pushed a new update with a fix for that (`0.23.1`) as this was really a critical issue.
