### ISSUE TITLE
auto selection or identification of robotframework-zoomba keywords 

### ISSUE THREAD

**Issue by jogiuser** [robocorp/robotframework-lsp#452]
Robot Framework Language Server  pycharm plugin is only identifying the  SeleniumLibrary keywords . However its not supporting keywords from robotframework-zoomba. robotframework-zoomba got very usefull keywords , hence it will great if pycharm plugin can support the same. 

thanks

**Comment by fabioz** [comment]
In general the language server should be able to recognize keywords from libraries out of the box.

Can you give more details? After installing robotframework-zoomba, which keywords are not being recognized? Can you provide the logging when that happens (following the steps at: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md)?
