### ISSUE TITLE
Suppport navigating to Python definitions

### ISSUE THREAD

**Issue by lynhbn** [robocorp/robotframework-lsp#455]
**Is your feature request related to a problem? Please describe.**
Currently I see that it's unable to browse to the keyword definition written in python

For example:
```
@keyword('click and wait')
def click_and_wait(locator)
```
cannot be associated with `click and wait` keyword

**Describe the solution you'd like**
Support to link them together

**Comment by fabioz** [comment]
This should work out of the box provided that the libspec can be generated for the library.

See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved for details on how to fix that.

If you still can't get it to work, please create a new report following the steps at: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md
