### ISSUE TITLE
Path variables are not recognized when used as resource file

### ISSUE THREAD

**Issue by nikiost** [robocorp/robotframework-lsp#465]
Hi,
I am facing the issue where my path variables are not recognized when I use it in import as resource file.
For example:
*** Settings ***
Resource    ${some_var}/some_path/file.robot

Are you going to implement this feature in future dev?
Thank you in advance)

**Comment by fabioz** [comment]
This is already supported (but you need to set those variables for the language server).

See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-specify-a-variable-needed-to-resolve-some-library-or-resource-import for details.
