### ISSUE TITLE
VSCode: Args provided in launch.json are not added since last version

### ISSUE THREAD

**Issue by ct-chook** [robocorp/robotframework-lsp#488]
**Describe the bug**
In 0.25 and earlier, arguments added in "args" of the Visual Studio Code launch.json file were appended to the list arguments used to run code lens tests. However this functionality broke in 0.26.0

**To Reproduce**
1. Create a .vscode/launch.json file using the boilerplate configuration
2. Inside the key "args", provide an array with at least one string
3. Run a robot test using the code lens

**Expected behavior**
Arguments in launch.json are appended to the list of arguments, instead they are ignored and only the "-t testcaseName" argument is used by Visual Studio Code.

The culprit appears to be the new code. `debugConfiguration.args.concat(value);` does not change the array of debugConfiguration, the code should be something like `debugConfiguration.args = debugConfiguration.args.concat(value);`
```
    if (launchTemplate) {
        for (var key of Object.keys(launchTemplate)) {
            if (key !== "type" && key !== "name" && key !== "request") {
                let value = launchTemplate[key];
                if (value !== undefined) {
                    if (key === "args") {
                        debugConfiguration.args.concat(value);
                    } else {
                        debugConfiguration[key] = value;
                    }
                }
            }
        }
    }
```
https://github.com/robocorp/robotframework-lsp/blob/5f23b7374139e83d0aa1ebd30675e762d7a0db86/robotframework-ls/vscode-client/src/run.ts#L199

**Versions:**
 - OS: Windows 8
 - Robot Framework Version 4.1.2
 - Robot Framework Language Server Version 0.26.0
 - Client Version VSCode 1.61.2

**Comment by fabioz** [comment]
Sorry about that, I've fixed this and pushed a new update containing the fix (0.27.0).
