### ISSUE TITLE
[PyCharm] robotCodeFormatter expects JSONArray, but code checks for string

### ISSUE THREAD

**Issue by mptok** [robocorp/robotframework-lsp#490]
**Description**
In Pycharm robotCodeFormatter expects JSONArray, but code checks for string. Check "To Reproduce" for more.

**To Reproduce**
1. Go to: File > Settings > Languages & Frameworks > Robot Framework (Global) . Or go to: File > Settings > Languages & Frameworks > Robot Framework (Project)
2. Scroll down to "Code Formatter".
It says: "Allows the configuration of the code-formatter engine to be used. One of: **robotidy**, **builtinTidy**.
Note: expected format: **JSON Array**"
3. Input "robotidy" as a plain string or input ["robotidy"] as JSON Array.
It does not accept them.
4.  Go to: "robotframework-lsp-master\robotframework-intellij\src\main\java\robocorp\robot\intellij\RobotProjectPreferencesPage.java"  Or go to:  "robotframework-lsp-master\robotframework-intellij\src\main\java\robocorp\robot\intellij\RobotPreferencesPage.java"
5. Search for validateRobotCodeFormatter.
It looks like it wants to convert plain string to JsonArray and then check if it is equal to "robotidy" or "builtinTidy". 

**Expected behavior**
It should expect string, don't convert it, then check if it is "robotidy" or "builtinTidy".  Or it should expect JSON Array, get strings from the array, then check if it is "robotidy" or "builtinTidy".

**Screenshots**
I am not a Java dev, but that part of the code just looks suspicious to me.
Error in the settings and snap of the code.
![image](https://user-images.githubusercontent.com/73593201/139966307-e385362c-cc62-4668-a299-f687682c1fae.png)

**Versions:** 
 - OS: Windows 10
 - Robot Framework Version 4.1.2
 - Robot Framework Language Server Version 0.27.0
 - Client Version PyCharm 2021.2.3 Community

**Logs**
Nope

**Comment by fabioz** [comment]
I'm sorry about that... this was fixed in the package.json, but the files that depend on it in Intellij weren't regenerated.

I've just fixed this (until a new official build goes out with this fix, you can get a binary from: https://github.com/robocorp/robotframework-lsp/actions/runs/1414776714 -- see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-install-a-build-from-github-on-intellij for details on how to install it).

**Comment by mptok** [comment]
Thanks for fast resposne. I will check fixed binary
