### ISSUE TITLE
Recognize that ELSE or ELSE IF conditions have Keyword target when using Run Keyword IF keyword

### ISSUE THREAD

**Issue by v8sharma** [robocorp/robotframework-lsp#495]
i.e.: With something as:

```
*** Keywords ***
Some Keyword
    Run Keyword IF    ${Cond1}    Keyword 1    ELSE IF    ${Cond2}    Keyword 2    ELSE    Keyword 3
```
The **Keyword 2** and **Keyword 3** should be properly recognized as keywords -- for code-completion, code-analysis, find definition, etc.

**Comment by v8sharma** [comment]
Nested keywords also don't seem to be recognized e.g.
`Run Keyword If    ${Cond1}    Run Keyword and Continue on Failure    Keyword 1`

Here **Keyword 1** is not recognized.

**Comment by MrBIN89** [comment]
Faced with the same issue
![изображение](https://user-images.githubusercontent.com/47885244/156871787-fd19bc74-a6cd-4c85-8ae6-29cf45fc3651.png)
VSCode 1.65.0
Robot Framework Language Server v0.41.0
robotframework 4.1.3
