### ISSUE TITLE
Run in VSCode with quick icons: Run | Debug getting Login failed error with ODBC Driver 17 for SQL Server

### ISSUE THREAD

**Issue by sylar3749** [robocorp/robotframework-lsp#501]
**Describe the bug**
Run in [Debug Process] with quick icons: **Run | Debug** getting error: 28000(Login failed) with ODBC Driver 17 for SQL Server

**To Reproduce**
1. Open a robot file with Test Case
2. The keywords in the Test Case will use **Connect To Database Using Custom Params** as: **Connect To Database Using Custom Params    pyodbc    ${DBHost_ConnectionString}** where ${DBHost_ConnectionString} like 'DRIVER=**{ODBC Driver 17 for SQL Server}**;SERVER=${server},1433;DATABASE=${db};UID=${dbUsername};PWD=${dbPassword}'
3. Click the Run | Debug quick icon(I've given proper info in the setting.json file for robot.variables)

**Expected behavior**
Should connect to database successfully

**Screenshots**
Maybe due to IT policies, I'm not able to upload the img here.
So I'll paste the error log for the step:
InterfaceError: ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'someusername'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'someusername'. (18456)")

**Note**
When I run the same test with launch.json configs, work as expected.

**Versions:**
 - OS: [e.g. Windows 10]
 - Robot Framework Version: 4.1
 - Robot Framework Language Server Version: 0.28.0
 - Client Version: VSCode: 1.62.1(user set up)

**Comment by fabioz** [comment]
Do you have some customization in your `launch.json` variables by any chance? 

i.e.: if you do, you also need to customize the code-lens launch in the `launch.json` (see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-configure-the-launch-from-a-code-lensshortcut).

Also, the message says that the login failed, so, you should check whether you are passing the proper values on both cases (i.e.: it should be a matter of making sure you pass the same variables on both cases -- if one is not working, it's up to you to check which value is different and customize that properly...).

**Comment by sylar3749** [comment]
My launch.json is like below:
{
                "type": "robotframework-lsp",
                "name": "Run and Debug Tests Sample",
                "request": "launch",
                "cwd": "${workspaceFolder}",
                "target": "${workspaceFolder}/project/test_scripts/${additional file or folder path}",
                "terminal": "none",
                "env": {},
                "args": [
                    "-Vproject/${variable file path}",
                    "-tTest*Case*Name"
                ]
            }

**Comment by sylar3749** [comment]
Some additional note:
  - When clicking the Run | Debug quick actions inside a robot file
       - Before version 0.28.0, the script will be run in Debug Console, which is same to run with a launch.json config;
       - In version 0.28.0, will create a [Debug Process] in terminal, and run the robot file with a command, which will get this Login failed error with ODBC Driver 17 for SQL Server
  - I've currently rolled back to 0.27.0, everything works as expected for me.

**Comment by sylar3749** [comment]
New founding...

I realize that there is a '^' symbol in my password variable for the odbc driver, and the '^' symbol is always missing when parsing the variable(See issue: [#567](https://github.com/robocorp/robotframework-lsp/issues/567)), so will never log in successfully.
