### ISSUE TITLE
Interactive console: `Run in interactive console` for keyword is misleading / can't redefine keyword

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#502]
It seems that having a `Run in interactive console` which just defines a keyword (and doesn't run it) is a bit misleading.

Maybe we could change the label to something as `Set/Load/Define in interactive console`.

Also, running it the 2nd time should redefine it instead of giving an error.

**Comment by janipalsamaki** [comment]
> Also, running it the 2nd time should redefine it instead of giving an error.

Just to add a bit of context: The reasoning is that I might want to edit a single keyword multiple times and then re-run it after each edit. Currently this is not supported.

**Comment by jaukia** [comment]
Great ideas. What if the "Run" would do both Load+Run, would that make sense @janipalsamaki @fabioz, cc @kariharju?

**Comment by janipalsamaki** [comment]
> What if the "Run" would do both Load+Run, would that make sense

For some keywords, but this should probably be an option and not the default. The user might not always want to run it immediately. Also, some keywords require arguments, etc., so there are some scenarios to take into account.
