### ISSUE TITLE
resources don't work

### ISSUE THREAD

**Issue by DetachHead** [robocorp/robotframework-lsp#506]
**To Reproduce**
asdf.resource:
```robot
*** Keywords ***
some keyword
    log    1
```
foo.robot
```robot
*** Settings ***
Resource    Sandpit/asdf.resource

*** Test Cases ***
foo
    some keyword
```
**Expected behavior**
keyword defined in resource file is found

**Screenshots**
![image](https://user-images.githubusercontent.com/57028336/141237493-cdddefd4-976f-4dd8-966c-938fbe88cd4a.png)

**Versions:**
 - OS:. Windows 10
 - Robot Framework Version: 4.1.1
 - Robot Framework Language Server Version: 0.28.0
 - Client Version: vscode 1.62.1

**Comment by fabioz** [comment]
It seems that your `PYTHONPATH` isn't properly defined.

In this case, you probably want to set in your settings something as:

```
"robot.pythonpath": ["${workspaceFolder}"]
```

Or alternatively use a relative import.

i.e.:
```
*** Settings ***
Resource    asdf.resource
```

**Comment by DetachHead** [comment]
ah got it, thanks!
