### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by JoneSabino** [robocorp/robotframework-lsp#51]
![image](https://user-images.githubusercontent.com/21135355/80085375-8388ec80-852e-11ea-9078-8ee2efac3c74.png)

The Library names and keywords implementation could differ on colors from the statements.

**Comment by JoneSabino** [comment]
Realized that colors are not related with LSP

**Comment by Snooz82** [comment]
Hi @JoneSabino 

You are correct. The colors are related to the theme you are using, but the types of elements are related to this project. 

i chose types that has acceptable colors in the default available themes.
Some supported types had no color in a theme, which leads to the situation that the type was correct, but the color was of the "default" item kind, which is string. So i chose for example the type of keywords is "support.function" which is in python functions like print().
Test Cases are entity.name.function which are typically used for function declarations.

So its mostly up to the theme to color it correctly.
But we may change types in the future.

**Comment by JoneSabino** [comment]
Thanks for the feedback!
