### ISSUE TITLE
Allow configuration for visibility of codelens decorations

### ISSUE THREAD

**Issue by dreamercz** [robocorp/robotframework-lsp#511]
Hello, I use the extension for VSCode and I really like it but I'd welcome a way to configure the visibility of codelens decorations over test cases.

![image](https://user-images.githubusercontent.com/11353706/142591466-05f06060-02c6-4390-98b7-e41c99bf731e.png)

**Describe the solution you'd like**

Add a configuration option to allow enabling/disabling the decorations. Something like the following could work:
```
robot.editor.codelensDecoration.enabled: <bool>
```
**Describe alternatives you've considered**

I think there might be a way to do this by overriding the editor' CSS, but that seems like a wrong way of going at it.

**Comment by fabioz** [comment]
There is a request to allow setting those individually (https://github.com/robocorp/robotframework-lsp/issues/375).

VSCode already provides the functionality to disable those (see: https://stackoverflow.com/questions/34356510/how-to-disable-codelens-in-vs-code) or potentially just customize it to have different font settings (https://stackoverflow.com/a/64759591/110451).
