### ISSUE TITLE
Robocop Linting errors only highlight 1st column

### ISSUE THREAD

**Issue by USER-5** [robocorp/robotframework-lsp#512]
**Describe the bug**
Robocop warnings only highlight the first column of the affected row in VS Code.

**To Reproduce**
1. Open a file with an error which will be flagged by the linter in VS Code
2. The yellow squiggly / underline is only on the 1st column of the affected line, and is a very small target to hover over

**Expected behavior**
the yellow squiggly should start and stop at the relevant columns, the same way as keyword errors do.
From what I’m aware, robocop reports the start and end column of the linting error, which is why I think this is a bug…

**Screenshots**

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 4.1.2
 - Robot Framework Language Server Version: 0.29
 - Client Version: VSCode 1.62.3

**Logs**
not applicable?

**Comment by fabioz** [comment]
This is something than needs to be done at `Robocop`, not in the language server.

Please follow/vote on: https://github.com/MarketSquare/robotframework-robocop/issues/290, which is the issue that's tracking this in the `Robocop` side.
