### ISSUE TITLE
Intellij 213 (2021.3) not supported

### ISSUE THREAD

**Issue by DirkRichter** [robocorp/robotframework-lsp#517]
Plugin 'Robot Framework Language Server' (version '0.29.0') is not compatible with the current version of the PyCharm IDE. Plugin requires build 212.* or older but the current PyCharm build is PY-213.5744.248.

**To Reproduce**
Open PyCharm 2021.3

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: all
 - Robot Framework Language Server Version: 0.29.0
 - Client Version: PyCharm 2021.3

**Comment by fabioz** [comment]
Thanks for the report. I plan to tackle this next week.

**Comment by fabioz** [comment]
I've just released `0.32.0` with this fix.

Note: the Intellij Marketplace can take some time to update, but it can be already installed manually from: https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server/versions/stable/148788
