### ISSUE TITLE
Tab Completion not working on VSCode

### ISSUE THREAD

**Issue by JoneSabino** [robocorp/robotframework-lsp#52]
Tab completion is not working on VSCode, even with the setting `"editor.tabCompletion": "on"` 

The suggestion shows up normally, but I need to press RETURN to auto complete not TAB, as usual.

**Comment by Snooz82** [comment]
I will see if it can be fixed. I assume it has to do with the option Tab4Spaces.

**Comment by fabioz** [comment]
@Snooz82 thanks for taking a look at it.

**Comment by Snooz82** [comment]
This should be fixed by PR

**Comment by fabioz** [comment]
Note: this is fixed for 0.1.1.
