### ISSUE TITLE
Part 2 #522 Keywords defined in static custom libraries in Python classes are marked "RED" as "Undefined Keyword"

### ISSUE THREAD

**Issue by UnexpectedGrit-3853** [robocorp/robotframework-lsp#524]
**Describe the bug**
The bug described in #522 provides some background, but I will try to explain what I'm seeing using a real-world context.
The drawback here is complexity of a real-world example now enters the stage, however, it may be useful to identify what is going on.
I will include a ".zip" file for you to use in hopes you'll be able to see what I'm seeing.
I will also include new screen-shots showing what I'm seeing.
I will include all the logs I was able to find.

NOTE: Any module with a class has now been renamed to match the name of the class.

For example: "lib_ble.py" once contained "class SaberAsyncBLE" which was considered to be the source of the problem and was considered incorrect and the bug was "Closed."

As a result, you'll find a change: module "lib_ble.py" is now named "LibBLE.py" and contains a NEW class defined as  "class LibBLE". The module is now named "LibBLE.py" - matching the class name inside it.  I have reflected this change throughout the code contained in the ".zip" file I've attached.

Modules that contain just function definitions (NO class definitions inside), now appear as "module_<some-name>.py"

Something I saw in your link posted in #522 : http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#creating-test-library-class-or-module 

was the following:   " If the module name and class name are different, libraries must be taken into use using both module and class names, such as mymodule.MyLibrary or parent.submodule.MyLib" .   Does the current RobotFramework LS algorithm support this rule?  If not, no worries.  I can work around it using your previous suggestions.  I was just wondering.

Anyway, here's how to go about reproducing what I'm seeing using the ".zip" I've included.

**To Reproduce**
1. Open IntelliJ project "saberiio"
2. Open file tab named "LibBLE.py"
3. Notice in the upper right hand corner, a "Green" check mark and gutter is clear!
4. Open file tab named "saberiio.resource"
5. Notice in the upper right hand corner, a "Green" check mark and gutter is clear!
6. Again Open file tab named "LibBLE.py"

7. Goto line# 12 and remove the comment on the line so you see code like this:
      from ble_comms_master.src.CharacteristicSocket import CharacteristicSocket

8. Goto line# 107 and remove the comments on lines 107 through 109 so you see code like this:
        if uuid not in self.dev.bound:
            channel = CharacteristicSocket(uuid)
            await self.dev.bind(channel)

9. Close project
10. Reopen Project saberiio
11. Notice in the upper right hand corner, a "Green" check mark and gutter is clear!
12. Open file tab named  "saberiio.resource"
13. Notice PyCharm's gutter now shows 13 errors. Each underlined in RED is a keyword found in "LibBLE.py" and is declared as an "Undefined keyword"

At this point, I do not understand why I see 13 "Undefined keyword" errors.  The keyword definitions appear correct to me.  Do you agree?

**Expected behavior**
New custom Keyword defined by a static custom library containing a Python class and used in a Robot Framework *.resource file is properly found and resolved without error.

**Screenshots**
![LibBLE-line12](https://user-images.githubusercontent.com/86731247/146059824-c6235152-7b7f-48d8-96f7-1171ba3901b4.jpg)
![LibBLE-line107-through-109](https://user-images.githubusercontent.com/86731247/146059827-7aedd7ff-6f0d-416c-b8e0-f249993ca947.jpg)
![LibBLE-starting-version](https://user-images.githubusercontent.com/86731247/146059831-d28f6b13-f313-461a-a9b1-a85da477eb47.jpg)
![saberiio-green-defined-keywords](https://user-images.githubusercontent.com/86731247/146059834-e38e55fa-8e75-41af-ac13-ca55cacecd6a.jpg)
![saberiio-red-undefined-keywords](https://user-images.githubusercontent.com/86731247/146059835-952e3b4d-71bf-4c6d-99eb-43ffffddf8f0.jpg)

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 4.1.2
 - Robot Framework Language Server Version: 0.32.0
 - Client Version: PyCharm 2021.2.3 (Professional Edition)

**Logs**
Add the logs obtained when reproducing the issue.
See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md for details on how to collect the logs.
[.robotframework-ls.zip](https://github.com/robocorp/robotframework-lsp/files/7713898/default.robotframework-ls.zip)
[pkell-appdata-local-jetbrains-pycharm2021dot2-log.zip](https://github.com/robocorp/robotframework-lsp/files/7713899/pkell-appdata-local-jetbrains-pycharm2021dot2-log.zip)
[saberiio.zip](https://github.com/robocorp/robotframework-lsp/files/7713900/saberiio.zip)

**Comment by UnexpectedGrit-3853** [comment]
NOTE: I just discovered that if I change the file extension from ".resource" to ".robot" (e.g. "saberiio.resource" --> "saberiio.robot") all errors disappear!!  Perhaps this is useful information to have during trouble-shooting.

**Comment by fabioz** [comment]
This should be fixed in the latest versions (there was a caching issue which caused this).
