### ISSUE TITLE
Start Robot Framework testcase by using in-code link gives error: Replacing variables from setting 'Variables' failed

### ISSUE THREAD

**Issue by bennyvw** [robocorp/robotframework-lsp#526]
**Describe the bug**
A Robot Framework testcase can be started in several ways. One of them is using the Run link that shows up just above the testcase definition. 
In that case the default (topmost) configuration from launch.json should be used. 
As per VSCode v 1.63.1 this way of starting a testcase does not work any more.

The error message is: Replacing variables from setting 'Variables' failed: Variable '${ENV}' not found.

**To Reproduce**
1. Open a Robot Framework file containing at least one testcase.
2. Click the 'Run' (or Debug) link just above the TC definition line.

**Expected behavior**
The testcase should be executed using the topmost configuration in launch.json.

**Screenshots**
![5d390485-2277-4bb1-90fc-cd2a0c52c429](https://user-images.githubusercontent.com/32094302/146219496-782668ad-46d4-4efb-a2fb-04da5e519136.jpg)

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 3.2
 - Robot Framework Language Server Version: 0.33
 - Client Version: VSCode 1.63.1

**Comment by fabioz** [comment]
As a note, it's not the first one that's used, rather the one named `Robot Framework: Launch template` (see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-configure-the-launch-from-a-code-lensshortcut)

Can you provide the contents of your launch.json? -- this seems like some misconfiguration in the launch config...

**Comment by alebr001** [comment]
Teammember of benny here. 

    "configurations": [
        {
            "type": "robotframework-lsp",
            "name": "Robot Framework: Launch template",
            "request": "launch",
            "terminal": "none",
            "args": [
            "--variable", "ENV:TST2", 
            "-d","results/${relativeFileDirname}/${fileBasenameNoExtension}/",
            "-b","${workspaceFolder}/debug.log"
             ]
        }, 
        .....

**Comment by alebr001** [comment]
Btw, i just tried downgrading to 0.32.0 and the problem is gone. When upgrading back to 0.33.0 the bug is introduced again

**Comment by fabioz** [comment]
By any chance do you have any setting `launch` setting on the `settings.json`?

One difference is that the newer version can load the settings from `launch.json` or from the `launch` defined in `settings.json` (either user settings or workspace settings).

**Comment by alebr001** [comment]
No setting launch in the settings.json


settings.json in .vscode:
{
    // "python.testing.cwd": "./dev/src/unit_test",
    "python.testing.unittestArgs": [
        "--rootdir",
        "./dev/src/unit_test",
        "-v",
        "-s",
        "./dev/src/unit_test",
        "-p",
        "*_ut.py"
        ],
    "python.testing.pytestEnabled": true,
    "python.testing.unittestEnabled": false,
    "python.terminal.executeInFileDir": true
}

settings.json in user appdata: 
{
    "window.zoomLevel": -1,
    "update.mode": "manual",
    "extensions.autoUpdate": false,
}


code workspace:
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"logViewer.watch": [
			{
				"title": "RF debug",
				"pattern": "**/debug.log"
			}
		],
		"logViewer.windows.allowBackslashAsPathSeparator": false,
		// "logViewer.showStatusBarItemOnChange": true,
		"robot.variables": {
			"SOURCEDIR": "${workspaceFolder}/dev/src"
		},
		"robot.completions.keywords.format": "Title Case",
		"robot.pythonpath": [
			"${workspaceFolder}/dev/src/lib",
			"${workspaceFolder}/dev/tools",
			"${workspaceFolder}/dev/src/sutObjects",
		],
		"robot.lint.robocop.enabled": false,
		"git.autofetch": true,
		"git.confirmSync": false,
		"git.ignoreRebaseWarning": true,
		"csv-preview.separator": ";",
		// "debug.allowBreakpointsEverywhere": true
	}
}

**Comment by fabioz** [comment]
I did some additional changes in the loading of templates which may fix your use-case.

Can you try to use the `.vsix` created in: https://github.com/robocorp/robotframework-lsp/actions/runs/1587355223 locally and let me know if it does work for you?

-- if it doesn't work, please pass me the output of the `OUTPUT > Robot Framework` tab when you do the run (as I've added some logging to know what may be happening).

**Comment by bennyvw** [comment]
Hi fabioz, 
Your version did not solve the problem. Still got the same error. The contents of the OUTPUT > Robot Framework tab goes here:

Getting language server Python executable.
Waiting for RobotFramework (python) Language Server to finish activating...
Language server Python executable. Searching in PATH.
Starting RobotFramework Language Server with args: C:\Program Files\Python39\python.exe,-u,c:\Users\bwijngaarden\.vscode\extensions\robocorp.robotframework-lsp-0.33.1\src\robotframework_ls\__main__.py
RobotFramework Language Server ready. Took: 3.0s

**Comment by fabioz** [comment]
Ok, I investigated a bit more and I think I found the issue.

Can you try again? (this time with the .vsix in https://github.com/robocorp/robotframework-lsp/actions/runs/1587791217)

**Comment by bennyvw** [comment]
@fabioz This version works fine again!
