### ISSUE TITLE
PyCharm plugin 0.33.0: environment variable not taken into account

### ISSUE THREAD

**Issue by apallier** [robocorp/robotframework-lsp#529]
**Describe the bug**
Since PyCharm plugin 0.33.0, the environment variables are not taken into account.
Works with  PyCharm plugin 0.32.0

**To Reproduce**
1. Pycharm: Edit a "run/debug" configuration with this environment variable
`HELLO=bonjour`
2. Execute the following test:

```robotframework
*** Test cases ***
Test Env Var
    Log    %{HELLO}
```

This error occurs (Robot console):
```
Test Env Var                                                          | FAIL |
Environment variable '%{HELLO}' not found. Did you mean:
    %{SHELL}
------------------------------------------------------------------------------
Test.Test                                                             | FAIL |
1 critical test, 0 passed, 1 failed
``` 

**Expected behavior**
No error. The string `bonjour` should be logged

**Versions:**
 - OS: Debian Buster
 - Robot Framework Version: 4.1
 - Robot Framework Language Server Version: 0.33.0
 - Client Version: PyCharm 2021.3

**Comment by fabioz** [comment]
Fixed in https://github.com/robocorp/robotframework-lsp/commit/035ea033e26d450a5c9f532d6bc0e1ab02563d7d
