### ISSUE TITLE
Environment variables defined in devdata/env.json that have spaces in them not working when running from code lens

### ISSUE THREAD

**Issue by kariharju** [robocorp/robotframework-lsp#532]
**Describe the bug**
Environment variable like: "DEVICE": "Desktop Chrome" defined in devdata/env.json
Robot executes correctly with `Robocorp: Run Robot`, but when running via code lens (debug and run) the environment variable value is just `Desktop`.

**To Reproduce**
1. "DEVICE": "Desktop Chrome" defined in devdata/env.json
2. Robot that just echoes the variable value
3. Running robot via code lens (debug or run) 

**Expected behavior**
The variable value should be "Desktop Chrome" not "Desktop"

**Versions:**
 - OS: darwin 21.1.0
 - Robocorp Code Version: 0.22.0
 - Robot Framework Language Server Version:0.34.0
 - Client Version: VSCode 1.63

**Comment by fabioz** [comment]
@kariharju 

This seems to be working for me with `Robocorp Code 0.23.0` / `Robot Framework Language Server 0.35.0` which were released a few hours ago (testing in windows though).

Can you check if it works for you with those? (the related code has changed while fixing https://github.com/robocorp/robotframework-lsp/issues/528, so, it's possible that this is actually fixed now...).

![image](https://user-images.githubusercontent.com/117621/147124755-26d906e3-8379-443b-bc07-46b004d0be2e.png)
