### ISSUE TITLE
font color of teststeps

### ISSUE THREAD

**Issue by alebr001** [robocorp/robotframework-lsp#533]
**Is your feature request related to a problem?**
I find it hard to read our robot files, this is because on a newline we need to put in resource.keyword or library.keyword, because keyword names are sometimes used in different resource files (e.g. click search). 

**Describe the solution you'd like**
I would like to set different font colors for library and keyword. 

**Describe alternatives you've considered**
Make a toggle to auto hide the library, auto upper case the library or make it possible to allign the testcases through indentation.

**Comment by fabioz** [comment]
Hy @alebr001 can you provide a screenshot showing which are the elements which you want with different colors (I'm not sure I understood exactly what you want to color, so a screenshot pointing the actual elements would make it much easier to understand).

**Comment by alebr001** [comment]
![Naamloos](https://user-images.githubusercontent.com/30652838/147265877-976b1e57-54b0-41c1-81a5-5ab035f5b748.jpg)

I would like BK_GUI_E_MainKeywords to have a different color from Login to browser

**Comment by alebr001** [comment]
![image](https://user-images.githubusercontent.com/30652838/147266631-83ae3217-f7f5-496e-b1a6-7258080ac9e2.png)


Maybe this is a clearer image. Because the keywords are not alligned it can become harder to read in larger testcases.

**Comment by mdks2010** [comment]
Is it possible to highlight the running line of code line by line during the running and debugging process, and stop when an exception is encountered and the line turns red?

**Comment by fabioz** [comment]
This is now fixed for 0.38.

**Comment by fabioz** [comment]
> Is it possible to highlight the running line of code line by line during the running and debugging process, and stop when an exception is encountered and the line turns red?

I believe that what you want is: https://github.com/robocorp/robotframework-lsp/issues/284 (still not implemented).

**Comment by alebr001** [comment]
Great work! Thank you very much. This is a very nice feature for us. Not a problem at all for us but with the setup and teardown the implementation does not seem to work:

![image](https://user-images.githubusercontent.com/30652838/151366756-2c5c4af8-db5a-49ef-b721-f3fd6565ba26.png)

**Comment by fabioz** [comment]
Reopening to handle the missing case.
