### ISSUE TITLE
Changing from 1 library to another... too much changed

### ISSUE THREAD

**Issue by valentijnpeters** [robocorp/robotframework-lsp#540]
**SeleniumLibrary**
_Input_ Text      //inputfield      thetext

changing to:

**Browser (library)**
_Fill_ Text       locator    text     **//inputfield    thetext**

so it helps too much, it should check first if there's allready some values there.

**Comment by valentijnpeters** [comment]
this issue is a bit hard to explain, but changing form library, changing from keyword, should check if there was already values after the keyword, then first leave that values alone, so the result is 
fill text   //inputfield  thetext 
and not more...

**Comment by valentijnpeters** [comment]
what I have noticed is that lots of testers/scripters hate it that it doesn't work properly but no one actually takes to time to raise an issues for it. so here it is.

**Comment by valentijnpeters** [comment]
(also Robocorp latest and RobotFramework Language server latest don't work well together!!)

**Comment by fabioz** [comment]
Closing as as I didn't really understand the issue and no further input was given.

Feel free to provide more information to reopen the issue.
