### ISSUE TITLE
Support .resource file extension

### ISSUE THREAD

**Issue by wvanmourik** [robocorp/robotframework-lsp#541]
According to the robotframework user guide, files with the extension .resource are supported and even recommended.
https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#supported-file-formats

Currently, syntax highlighting does not work in files with the .resource extension.
(files with .robot syntax do have highlighting)

Used version: 0.36.0
Editor: IntelliJ IDEA

**Comment by fabioz** [comment]
The plugin actually does support it.

I'm not sure why this happens... The extension does support `.resource` out of the box (and does register for it: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-intellij/src/main/resources/META-INF/plugin.xml#L27).

On a clean install when I install the plugin it does seem to recognize that both `.robot` as well as `.resource` are handled and does make the association automatically, however, this is already the 2nd time I saw someone complain that the association is not working.

Can you check in the `Settings > Editor > File Types` if both `*.resource` and `*.robot` are assigned to `Robot Framework`?

Do you have (or had) some other `Robot Framework` plugin installed?

**Comment by wvanmourik** [comment]
The assocation was not there so I manually added it: *.resource.
IDEA stopped me;  This wildcard is already registered by 'Text' filetype

I don't remember having adding that but that is possible/likely. I now switched it (back) to Robot Framework.
And yes, syntax highlighting now works! Thanks.

**Comment by fabioz** [comment]
Maybe some other extension had added that or somehow IDEA helpfully added it for you...

Anyways, great that it's working now ;)
