### ISSUE TITLE
Code analysis: notify if library is invalid

### ISSUE THREAD

**Issue by valentijnpeters** [robocorp/robotframework-lsp#542]
**Describe the bug**
[in the quest of testing the test tools to make a bit better world]
If you install a new library, but something is wrong with it...
Then it still shows up coloured green in Visual studio code as if nothing is wrong with it.
Since a year I use VSC IDE but with Eclipse IDE, this part was better

**To Reproduce**
1. install OpenApiDriver libary for example but make some config mistakes

**Expected behavior**
the library text shows red instead of green.
only and only if they keywords work and everything is okay, then the library shows on top in color green text.

**Comment by fabioz** [comment]
I'm not sure I follow. Can you show a screenshot and provide the actual code for the use case?

**Comment by fabioz** [comment]
Humm, rereading it, do you mean that code analysis should notify that a library name isn't valid?

**Comment by valentijnpeters** [comment]
yes, when a library has keywords, but they can't be used because something is wrong... I'd like to visually see that in VSC. (for example the Library name turns red color instead of green)! 
Thanks for the issue improvements! Very much appreciated.

**Comment by valentijnpeters** [comment]
![controle_in_Eclipse](https://user-images.githubusercontent.com/49692812/150160113-15599f48-344c-47eb-a7cd-c8b111acb24f.jpg)

zo ziet dat in Eclipse er uit! in VisualSC is dat niet. dat mis ik. (Het zit denk ik in de MarketplaceModule=RED van Eclipse)
