### ISSUE TITLE
About Robot Framework 5.0 support

### ISSUE THREAD

**Issue by tranhoangnguyen193** [robocorp/robotframework-lsp#543]
Hi friends,

Are there any issues if I use robotframework-lsp extension for Robot Framework 5.0 ?

**Comment by fabioz** [comment]
I believe it should work (there aren't tests for features added into RF 5 right now, but all the tests are also ran with the RF `master` branch, so, it should be safe -- as a note, if you are using some new feature for RF 5 and it doesn't work, please create an issue regarding it).
