### ISSUE TITLE
Starting an interactive console session on a .resource file breaks auto-completion

### ISSUE THREAD

**Issue by Serhiy1** [robocorp/robotframework-lsp#545]
**Describe the bug**
If you press "load in interactive console" on a file with an .resource extension auto-complete will not work. Even for standard library keywords such as `set variable`

**To Reproduce**
1. create an empty .resource file and type in ***settings*** so the  "load in interactive console" prompt appears
2. press the prompt and type in "${foo}= Set var"
3. Try to bring up the auto-completion menu by pressing ctrl + space
4. Nothing appears
4. For comparison do the same with a file with the .robot file ending
5. Autocomplete options will appear 

**Expected behavior**
.resource and .robot files should have the same auto-complete behaviour

**Screenshots**
.resource
![image](https://user-images.githubusercontent.com/28574129/150650801-65b0a948-29da-485e-990d-c689d9d62278.png)

.robot
![image](https://user-images.githubusercontent.com/28574129/150650820-468aec13-e287-4605-ad1d-431274cddb5c.png)

**Versions:**
 - OS: WSL linux ubuntu 20 LTS
 - Robot Framework Version: 4.0.3
 - Robot Framework Language Server Version: 0.37.0
 - Client Version: vs code latest

**Comment by fabioz** [comment]
Thanks for the report (just fixed).
