### ISSUE TITLE
PyCharm run configuration is missing env vars defined in plugin settings

### ISSUE THREAD

**Issue by NikitaOstr** [robocorp/robotframework-lsp#548]
**Describe the bug**
Resource and libraries in my project are used with variables, like '${VAR}/folder/file.robot'. To make it working those variables are defined in json format in proper settings of the plugin. No issue with browsing the code or keyword linking/definition.
After configuring 'run configuration' with target, arguments and working directory - run failed with error 'Replacing variables from setting 'Resource' failed: Variable '${VAR}' not found.'

**To Reproduce**
1. Use variable in path for resource/library file, defined in proper plugin setting (seetings -> languages & frameworks -> robot framework -> variables)
2. Configure 'run configuration' with target, argument and working directory
3. Run this just created configuration

**Expected behavior**
The variables will be resolved as they are done within project window

**Versions:**
 - OS:Windows 10
 - Robot Framework Version: 4.1.3
 - Robot Framework Language Server Version: 0.37
 - Client Version: PyCharm 2021.3.1

**Comment by fabioz** [comment]
Thank you for the report (fixed for 0.38).
