### ISSUE TITLE
Code Completion for path based library imports

### ISSUE THREAD

**Issue by Snooz82** [robocorp/robotframework-lsp#55]
Hi Fabio,

When you load a python library that is not installed via pip with the relative or absolute path into a robot file, is is not used in completion.

Assume:
```
Folder
  Test.robot
  MyLib.py
```
  

```
*** Settings ***
Library    MyLib.py     # relative to current file
Library    /home/temp/MyLib2.py    # absolute path C:/temp/MyLib.py should work as well.
```

When using abs path, lsp creates a MyLib.libspec in the same folder, but no completion happens.

**Comment by fabioz** [comment]
I'll investigate.
