### ISSUE TITLE
Robot issue upon attempting on Visual Studio to ROBOCORP Create Robot

### ISSUE THREAD

**Issue by rikardndreu** [robocorp/robotframework-lsp#552]
**Describe the bug**
When attempting to create a template on visual studio code I get an exception that Robocorp not found.

**To Reproduce**
1. Open VS Code
2. Ctrl+Shift+P
3. Select "Robocorp: Create Robot"
4. However, I got this exception: "command 'robocorp create robot' resulted in an error (command 'robocorp.create robot' not found)"

**Expected behavior**
I expected a template selection for the robot creation.

**Screenshots**
Here is a screenshots
![image](https://user-images.githubusercontent.com/80853437/151214117-ae274d50-a805-4e95-ad7c-efaba3c530d6.png)

**Versions:**
OS: Windows 10
Robot Framework Version: 3.2.2
Robot Framework Language Server Version: v0.34.0
Client Version: VSCode 1.58.2

**Comment by fabioz** [comment]
Please update the extensions to the latest version
i.e.: 
- Robocorp Code to `0.26.0`  
- Robot Framework Language Server to `0.38.0`

If you still have an issue after updating, please provide the output in the tab: `OUTPUT > Robocorp Code`.

**Comment by rikardndreu** [comment]
I appreciate your input but these are available extensions versions on VSCODE. Is there a workaround?

**Comment by fabioz** [comment]
This is odd... are you on an old version of VSCode itself by any chance?

You can see the version in `Help > About` (ideally it should be 1.63.2)...

i.e.:

![image](https://user-images.githubusercontent.com/117621/151220195-c82a992b-977b-409d-a024-bbecb77e0d65.png)

You can also see the latest versions in:
- https://marketplace.visualstudio.com/items?itemName=robocorp.robocorp-code
- https://marketplace.visualstudio.com/items?itemName=robocorp.robotframework-lsp

**Comment by rikardndreu** [comment]
Thank you for your insights. The VSCODE update solved the issue.
