### ISSUE TITLE
(VSCode) Inline "Run" button does not work on test cases with special characters

### ISSUE THREAD

**Issue by nizwiz** [robocorp/robotframework-lsp#553]
**Describe the bug**
Since v 0.38, in VSCode, pressing the inline "Run" button on test cases with special characters in the test case name (e.g. 'ü') causes the following error message in the Terminal

`[ ERROR ] Suite 'Test' contains no tests after model modifiers.`

Using the top-level "Run Suite" works, though.

NB: The issue does not seem to be present in v 0.37.

**To Reproduce**
Open the following file in VSCode and click the inline Run button as shown in the image below.
[test.robot.zip](https://github.com/robocorp/robotframework-lsp/files/7949814/test.robot.zip)

**Expected behavior**
Test case is executed.

**Screenshots**
![image](https://user-images.githubusercontent.com/19755352/151343483-fabc7665-2c24-40a1-b4b8-dcbe16186967.png)

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 4.1.3 / Python 3.8.10-amd64
 - Robot Framework Language Server Version: 0.38
 - Client Version: VSCode-win32-x64-1.63.2

**Logs**
[robotframework_ls.log.zip](https://github.com/robocorp/robotframework-lsp/files/7949853/robotframework_ls.log.zip)

**Comment by fabioz** [comment]
This should now be fixed.

@nizwiz Please get the .vsix at https://github.com/robocorp/robotframework-lsp/actions/runs/1756054468 and let me know if it runs for you (if it does I'll do a new release as I think that's a critical issue).

ps.: see: https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix if you need details on how to install from a .vsix.

**Comment by nizwiz** [comment]
> @nizwiz Please get the .vsix at https://github.com/robocorp/robotframework-lsp/actions/runs/1756054468 and let me know if it runs for you (if it does I'll do a new release as I think that's a critical issue).

Yep, I can confirm the issue is fixed with the new vsix. Thank you very much for the quick response!
