### ISSUE TITLE
Error collecting Robocop errors: Could not get mutex

### ISSUE THREAD

**Issue by olimexsmart** [robocorp/robotframework-lsp#555]
**Describe the bug**
After some time this error shows up:

![robotError](https://user-images.githubusercontent.com/17432947/151387906-92b03229-9cb4-448c-b25d-fd4ed78ea05c.png)

**To Reproduce**
Just opening the VSCode folder

**Comment by fabioz** [comment]
Is it possible for you to send the logs for this?

i.e.: See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md for details.

**Comment by GLMeece** [comment]
I have this same issue, except the error message is slightly different:
> `Error collecting Robocop errors: [Errno 13] Permission denied: 'robocop.log'`

Since this is closed, I don't know if I'll get a reply. However, if there's a solution to this, I'd love to know about it!
