### ISSUE TITLE
Unable to start robotframework-lsp because: python could not be found on the PATH.

### ISSUE THREAD

**Issue by rthier** [robocorp/robotframework-lsp#560]
I'm using the latest version of VS Code plugin (v0.38.1) and with this version appears the following error when try to start the language server:

```
Unable to start robotframework-lsp because: python could not be found on the PATH
```

I was looking for some difference in the latest version and I found this commit:
https://github.com/robocorp/robotframework-lsp/commit/fb2d9bc0611a288270bdd47a9863965e37ba1ad6#diff-0fefade1994682e75a371a5e87217db562299ade61d20c91b09e427110ceb17e

For some reason the integration between this extension and `vscode-python` extension doesn't work well for me, I don't know if this issue happens because I'm using [asdf-vm](https://asdf-vm.com/) to manage my python versions.

The following line set `executable` with the full path of the python executable. (e.g. `/Users/MyUser/.asdf/shims/python3.10`)
```js
executable = await (0, pythonExtIntegration_1.getPythonExtensionExecutable)()
```

The function `findExecutableInPath(executable)` wait for an executable and doesn't for the full path.

WORKAROUND: just remove the code from the mentioned commit.

**Comment by fabioz** [comment]
I think I see the issue: the executable is probably an array and not just the python executable (and this isn't handled as it should). I'll take a look at it.

**Comment by rthier** [comment]
Thanks for the fast support @fabioz !

**Comment by fabioz** [comment]
Can you just double-check for me if the fix does indeed work for you?

You can get a .vsix with the fix in https://github.com/robocorp/robotframework-lsp/actions/runs/1778003197 (if it doesn't work, please reopen providing the contents of `OUTPUT > Robot Framework`).

See: https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix if you need help to install from a .vsix.

**Comment by andreagubellini** [comment]
I'm having the same issue.. are you planning to release the fix?

**Comment by fabioz** [comment]
Yes, I plan on releasing it tomorrow -- in the meanwhile, it be nice if someone can confirm that the fix did work: https://github.com/robocorp/robotframework-lsp/issues/560#issuecomment-1026761469 ;)

**Comment by fabioz** [comment]
https://github.com/robocorp/robotframework-lsp/actions/runs/1778003197 (under artifacts)

**Comment by andreagubellini** [comment]
thanks I'll try the fix and let you know

**Comment by andreagubellini** [comment]
@fabioz I confirm: the fix works fine.
