### ISSUE TITLE
When debugging, cannot locate tests inside a suite that contains a prefix in its name

### ISSUE THREAD

**Issue by drgarbi** [robocorp/robotframework-lsp#561]
Since version 0.38.0, test execution filtering has switched from specifying the path and only the top level suite, to filtering the entire suite from `--suite` option.

Before (v 0.37.0):
`/usr/bin/env /tmp/rf-ls-run/run_env_00_fh6q0bkg.sh -u /home/twuser/.vscode-server/extensions/robocorp.robotframework-lsp-0.37.0/src/robotframework_debug_adapter/run_robot__main__.py --port 37259 --debug --suite Verification_Routing_Rules /home/twuser/xgspon-robot/Tests/CLI_Tests/03__Configuration/Device_Configuration `

Now (v0.38.0+:
`/usr/bin/env /tmp/rf-ls-run/run_env_00_txkmns68.sh -u /home/twuser/.vscode-server/extensions/robocorp.robotframework-lsp-0.38.1/src/robotframework_debug_adapter/run_robot__main__.py --port 36271 --debug --suite Tests.CLI_Tests.03__Configuration.Device_Configuration.Verification_Routing_Rules /home/twuser/xgspon-robot/Tests`

When executing with the new filtering method, the following message is printed out to the user and no tests are executed:
`[ ERROR ] Suite 'Tests' contains no tests in suite 'Tests.CLI_Tests.03__Configuration.Device_Configuration.Verification_Routing_Rules'.`

In the Robot Framework user manual, [Test Suite Name And Documentation](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-suite-name-and-documentation) section, it states that names containing a prefix followed by double underscores does not take into account the prefix to form the suite's name. So, in our case, the --suite filter should be followed by `'Tests.CLI_Tests.Configuration.Device_Configuration.Verification_Routing_Rules'`.
When executing the tests manually using this filter, Robot Framework finds the test suite and executes normally.

Our directory tree is as following:
Tests/CLI_Tests
├── 03__Configuration
│   └── Device_Configuration
│       ├── Configuration_Performance_and_Stress.robot
│       ├── Default_Startup_Configuration_Management.robot
│       ├── __init__.robot
│       ├── Verification_General_CLI_Basic_Services.robot
│       └── Verification_Show_CLI_Commands.robot
└── __init__.robot

Our Robot Framework version is 4.1.3.

**Comment by fabioz** [comment]
Thanks for the report. I wasn't aware of that behavior (marking as high priority -- should make it into the next release).
