### ISSUE TITLE
Notify about `robot` namespace being shadowed

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#563]
If the user shadows the `robot` namespace with his own module the language server will complain that the version is not available (`N/A`) and will say that the version is too old when in reality the `robot` namespace is being shadowed by the user.

The language server should give a better error message in this case.

**Comment by kalyncoose** [comment]
Hi @fabioz, I had this robot namespace shadow issue and I resolved it after a frustrating time troubleshooting, so I wanted to document my resolution here.

**Environment**:
- Intel Macbook
- Python 3.9
- RobotFramework==4.1.3
- VS Code
- Robot Framework Language Server v0.40.1

**Error on first line in Robot file:**
```
*** Settings ***
```
```
Error calling "robot.get_version()".
If the module: <module 'robot' (namespace)>
is a module from your project, please rename it (as it is shadowing the Robot Framework `robot` package)
and restart the Robot Framework Language Server.robotframework
```

**Root-Cause Analysis:**
I was installing custom pip packages from my private GitLab, under my setup.py in those private packages I had included "robot" in the setup_requires which means it installed robot==2007711 on top of my existing robotframework==4.1.3. That is why I was getting the "Error calling robot.get_version()".

**Resolution Explanation**:
When you accidentally install `robot` on top of `robotframework` package, simply doing `pip uninstall robot` will not resolve the issue, as somehow the an extra __init__.py is left over or the files/directory is messed up. You must also uninstall robotframework and then ONLY reinstall robotframework. Then do `pip freeze` and ensure that `robot` is NOT there and that `robotframework` IS there. Then restart VS Code or the language server via Command Palette and now your language server should load fine (without anymore error calling robot.get_version()).

**Resolution Steps**
1. `pip uninstall robot` - this causes the robot namespace shadow problem
1. `pip uninstall robotframework` - this ensures no more extra __init__.py file is left over
1. `pip install robotframework`
1. `pip freeze` - check to ensure `robot` is not there, but `robotframework` is
1. Restart VS Code/language server
