### ISSUE TITLE
Investigate robot api usage

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#57]
Check `robot` imports in robotframework-lsp and check if there's a corresponding `robot.api` import we could use (and if not, check if it's possible to do it).

**Comment by fabioz** [comment]
I'm using `robot.api` when possible now. 

The use-cases where I couldn't use them are the following:

**Imports:**
`from robot.tidy import Tidy`

**Used as command line:**
`python -m robot.libdoc`

@pekkaklarck, do you think those are ok or should the access be different?

As a note, I did changes so that I'm not importing model classes (such as `robot.parsing.model.statements.Fixture`), but I do use the names of those classes as well as attributes (so, changes in the parsing model such as class or attributes removals/renames can potentially break the lsp usage).

Closing this as the `robotframework-lsp` usages have been fixed for 0.0.10.

**Comment by pekkaklarck** [comment]
`from robot.tidy import Tidy` and `python -m robot.libdoc` ought to both be safe.

Do you use class names directly or via `NodeVisitor` like [shown in the API docs](https://robot-framework.readthedocs.io/en/latest/autodoc/robot.parsing.html#inspecting-model)? Either way, class names or attributes won't be changed lightly and unless very seriously needed not at all in minor versions.

**Comment by fabioz** [comment]
I use class names directly (accessing `node.__class__.__name__` the same way that NodeVisitor does but without actually subclassing NodeVisitor, so, it should be the same thing but without having to create a new class to override a method -- it shouldn't break unless NodeVisitor also breaks).

**Comment by pekkaklarck** [comment]
Sounds safe then. Any particular reason you don't use NodeVisitor?

**Comment by pekkaklarck** [comment]
OK. I like visitors but understand this is personal preference. Anyway, in this case both usages ought to be fine and safe.
