### ISSUE TITLE
Add the ability to delete only one error from the debug code lens.

### ISSUE THREAD

**Issue by Serhiy1** [robocorp/robotframework-lsp#579]
**Is your feature request related to a problem? Please describe.**
Robot LS has a feature where errors are reported directly into a file via code lense.  This is great when working on single tests, but gets in the way when working with suites of tests. In my opinion, this is mainly because there is no ability to delete a single code lense  
entry. 

_the bin icon will delete all result entries from the entire project_
<img width="365" alt="image" src="https://user-images.githubusercontent.com/28574129/154690771-9777db4b-b859-45a9-884f-2ca380760463.png">

My ideal workflow when debugging multiple tests would be:
1. Run a suite or multiple suites of tests
2. Go to the first recorded failure
3. Read error and then clear error code lense to reduce visual noise.
4. Make edits and re-run the test 
5. Repeat Steps 3 and 4 until the test passes
6. Move onto next test and repeat the process 

**Describe the solution you'd like**
- Make the Bin Icon only delete the code lense for that specific test. 
- Possibly add a separate button for clearing the results for only a test suite
- Make clearing all results a separate button.

**Describe alternatives you've considered**
No real alternative here that's available.

**Comment by fabioz** [comment]
@Serhiy1 all that isn't really controlled by the extension, that's controlled by VSCode itself as a part of its `test explorer` feature.

This means that this must be tackled by VSCode itself (so, please report it at: https://github.com/microsoft/vscode).
