### ISSUE TITLE
Gherkin syntax highlighting for VS Code (I need help to implement this)

### ISSUE THREAD

**Issue by weltings** [robocorp/robotframework-lsp#581]
Hi, I would like to implement Gherkin/BDD highlighting on VS Code. But I am new to robotframework-lsp.

Can someone help me get started?

(there is also issue #353 requesting BDD highlighting for IntelliJ IDEA, but this one is for VS Code)

I tried to define a syntactic token in robotframework.tmLanguage.json:

>         "keyword_call": {
>             "end": "^(?!\\s*\\.\\.\\.)",
>             "begin": "^(?!(?: {2,}| ?\\t ?)+(?:(?=[$\\[@&%]|\\.)))(?: {2,}| ?\\t ?)+(?:Given|When|Then|And|But)?\\s?(.*?)(?= {2,}| ?\\t ?| ?$)",
>             "beginCaptures": {
>                 "1": {
>                     "name": "bddprefix.keyword.call.robot"
>                 },
>                 "2": {
>                     "name": "meta.support.function.robot"
>                 }                
>             },

But it gets overwritten by the semantic token "keywordNameCall". Now I'm trying to define a new semantic token, but I cannot find the code parts that I need to adjust.

I'm guessing I need to change at least the following:
1. Add entry to TOKEN_TYPES in semantic_tokens.py
2. Add entry to robotframework_ls.impl.robot_constants in robot_constants.py
3. Add entry to RF_TOKEN_TYPE_TO_TOKEN_TYPE_INDEX in semantic_tokens.py
4. Add entry to semanticTokenScopes in package.json

But maybe I also need to adjust the logic that assigns the semantic tokens and returns them to the IDE when the IDE calls the language server?

Microsoft mentions that a Language Server Protocol implementation can register a semantic token provider:
https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide

> const provider: vscode.DocumentSemanticTokensProvider = {
>   provideDocumentSemanticTokens(
>     document: vscode.TextDocument
>   ): vscode.ProviderResult<vscode.SemanticTokens> {
>     // analyze the document and return semantic tokens

However I cannot find any function in the whole project where Robot Framework LSP registeres its semantic token provider.

Can anyone tell me if I am on the right track?

**Comment by fabioz** [comment]
You're in the right track :)

I suggest you create a test in `robotframework_ls_tests.test_semantic_highlighting` (there are many available there you can use as a reference) and then iterate based on getting the expected result (then you can run things easily in a debugger as well).

After doing the base test, implement what's needed in `semantic_tokens.py` to return the proper tokens and as the last step the association needs to be done to an existing token.

For that you need to edit `codegen_package.py` (which must be run to regenerate `package.json` and add the color to `semanticTokenScopes` - `scopes`.

Hint: You can use the command: `Developer: Generate color theme from current settings` to know the existing tokens you can use as the values for the association.

Then, the last steps would be editing:

- `robotframework-interactive\vscode-interpreter-webview\src\monacoConf.ts` (to add the color association to the interactive console).
- `robocorp.robot.intellij.RobotFrameworkSyntaxHighlightingFactory` (to add the color to Intellij).

-- note: I can do the last steps if you're not familiar with that env...

**Comment by fabioz** [comment]
Sidenotes: 
- Implementing it in the tmlanguage.json is entirely optional (as the color will be overridden anyways and dealing with that grammar is a hassle in general).
- Doing this will also fix https://github.com/robocorp/robotframework-lsp/issues/353 automatically ;)
- Feel free to ask more if you need additional hints -- and thanks for tackling this ;)

**Comment by weltings** [comment]
Well, a good hint is always appreciated.

When trying to setup the unit testing I run into this:
ImportError: Error importing plugin "robotframework_ls_tests.monitor_fixtures": No module named 'robotframework_ls'

I got the same error for the PyTest module, and was able to resolve it by installing it with " pip.exe install pytest" from inside the virtual environment. But I can't do that with the robotframework_ls, since it is not a python package (and I'm developing it). 

I see that in the main package, when modules try to import robotframework_ls, an ImportError is caught by exception handling in __init__.py. And then something gets translated to the robotframework_ls folder. However this is not setup for tests. ANy hints or advice are welcome.

**Comment by weltings** [comment]
![image](https://user-images.githubusercontent.com/33200263/154850664-5bdc31c5-4ecc-411e-8d71-b71372be2d5b.png)

If anyone ever experienced similar issues when importing robocorp_ls_core for unit testing, let me know.

**Comment by fabioz** [comment]
If you follow the steps to create the environment from: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/develop.md (and use the python from the virtual environment created) it should work.

**Comment by fabioz** [comment]
i.e.: it should add the paths needed in the PYTHONPATH by creating some `.pth` files with the `echo` commands there...

**Comment by weltings** [comment]
It's working now, thanks

**Comment by weltings** [comment]
Okay, so I am one step further. Now I'm looking at the following in semantic_tokens.py:
- semantic_tokens_full_from_ast
- tokenize_token

If I understand correctly, this function goes through all tokens in a Robot Framework resource or robot file, and then assign some scope to them like "KEYWORD" that later resolves into a scope like "keywordNameCall"

However when my source.robot file contains a keyword like this:
- Given Some BDD description of system behaviour

Then in the debugger I will get a token type KEYWORD that contains everything. 
So I need to split this single token up into 2 different tokens:
1. BDD prefix token containing "Given" 
2. KEYWORD token containing "Some BDD description of system behaviour"

I'm guessing I have to adjust something in ast_utils.py, perhaps the following function:
- find_token

Any hints on where I need to look?

**Comment by fabioz** [comment]
Yes, you need to create 2 tokens from that single one. This is already done for when a `.` is found, now you need to handle the prefixes. 

The actual source for this is: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/src/robotframework_ls/impl/semantic_tokens.py#L139 (check for the prefix and create the proper tokens as needed).

**Comment by weltings** [comment]
OK, 
I have created a unit test suite for the gherkin semantic highlighting
Inserted a function that can handle Gherkin language
At the moment Gherkin language components reuse the semantic tokens for "control"
This might not be semantically correct, however it looks good and I do not expect people to mix Keyword driven and BDD style paradigms during test development very often.
Tested it manually in the VS Code Extension Development Host

What now?

I see this:
![image](https://user-images.githubusercontent.com/33200263/155036205-fb4e58e7-bd7a-413a-a21d-2b58b4af6ab0.png)

Is this something I should follow?

**Comment by fabioz** [comment]
Not really (those are the steps for doing a release).

What you want to do now is create a pull request in github so that your changes may be incorporated in the code.

See: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request for how to do that.

**Comment by weltings** [comment]
OK, 

1. Created a branch called gherkin_highlighting
2. Forked the project
3. And created a pull request

**Comment by fabioz** [comment]
Done in: https://github.com/robocorp/robotframework-lsp/commit/e165c0326b7bc539007414157ad3e52ce508490a

**Comment by GLMeece** [comment]
I know this issue is closed, but I was wondering if there's a way to specify the Gherkin keywords for VS Code's styling? For example, I'd like to make them italic, such that the steps look something like this:

_Given_ admin user is logged in
_When_ user creates new customer
_And_ send email is selected
_Then_ verify email received

For other syntax formatting, I've used a form like this in `settings.json`:

```jsonc
{
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": [
          "comment",
          "entity.other.attribute-name", //HTML Attributes
          "entity.name.type.class", //class names
          "keyword", //import, export, return…
          "constant", //String, Number, Boolean…, this, super
          "storage.modifier", //static keyword
          "storage.type.class.js", //class keyword
          "meta.function-call.arguments.python"
        ],
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "scope": [
          //following will be excluded from italics (VSCode has some defaults for italics)
          "invalid",
          "keyword.operator",
          "constant.numeric.css",
          "keyword.other.unit.px.css",
          "constant.numeric.decimal.js",
          "constant.numeric.json"
        ],
        "settings": {
          "fontStyle": ""
        }
      }
    ]
  }
}
```

So, is there a token I can use that will **only** address Gherkin keywords? I'm definitely a newb at this.

**Comment by fabioz** [comment]
@GLMeece can you report this as a separate issue?

The problem is that for simplicity the Gherkin tokens reuse the same tokens for other things, so, the fix would be actually using a different token for it so that you can customize it.
