### ISSUE TITLE
Unresolved library imports using ${EXECDIR} in the path

### ISSUE THREAD

**Issue by hcortepi** [robocorp/robotframework-lsp#582]
**Describe the bug**
When importing files in Settings, the paths should be recognizable when using  `${EXECDIR}` instead of the usual ../../ system, given this latter one is not the best practice to import files since it makes the code way more confusing for when the files we want to import are stored inside 4 different folders for instance.

The test cases actually run when using the `${EXECDIR}` in the path, but when looking at the code it just looks like I have a bunch of errors, which isn't the case.

**Expected behavior**
The libraries/resources should be recognized with the `${EXECDIR}` specified in the path.

**Screenshots**
<img width="559" alt="image" src="https://user-images.githubusercontent.com/78511917/155032564-e9ee3b45-4544-4c2e-900b-7f9e3cf25982.png">

**Versions:**
 - OS: macOS
 - Robot Framework Version: 4.1
 - Robot Framework Language Server Version: 0.40.1
 - Client Version: PyCharm 2020.1.2

**Comment by fabioz** [comment]
In this case you need to specify the value of the `EXECDIR` variable using the `robot.variables` setting.

See: https://github.com/robocorp/robotframework-lsp/issues/263
