### ISSUE TITLE
Keywords with embedded Arguments and Gherkin syntax.

### ISSUE THREAD

**Issue by Snooz82** [robocorp/robotframework-lsp#59]
At the moment LSP analyses which keywords can be found.
This leads now to the issues that Keywords with embedded Arguments are errors. Also the prefixes `given, when, then, and, but` are not ignored and also leads to not finding elements.

See
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#embedding-arguments-into-keyword-name

and
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#embedding-arguments-into-keyword-names

**Comment by Snooz82** [comment]
It feels like, that the search for keywords is not done with robot code, but own one. Couldn't this lead to the situation, that there are changes in the syntax and lsp didn't get them?

**Comment by fabioz** [comment]
Still missing handling of the prefixes.

**Comment by fabioz** [comment]
This is now fixed.
