### ISSUE TITLE
Virtual env python interpreter not found by default for robotframework-lsp plugin in PyCharm

### ISSUE THREAD

**Issue by podfran** [robocorp/robotframework-lsp#596]
**Describe the bug**
When opening a new project in PyCharm the default is to search for the interpreter in the PATH, when it is very common to use a virtual env (PyCharm asks about this automatically). One needs to set the path to the python executable for each new project.

**To Reproduce**
1. Have a project with a .robot file with some valid code in it
2. Create a python virtual environment with robotframework installed
3. Make sure the Language Server Python setting is empty for global and project
4. Reopen the project
5. Open a .robot file

**Expected behavior**
Syntax highlighting working correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/28577180/156774487-94cd3b04-dde8-43f2-976a-b210bc8fab9a.png)

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 3.2.1
 - Robot Framework Language Server Version: [e.g. 0.2.3]
 - Client Version: PyCharm 2021.2.4

**Logs**
[robotframework_ls.lsp.10640.log](https://github.com/robocorp/robotframework-lsp/files/8186483/robotframework_ls.lsp.10640.log)
[robotframework_ls.remote_fs_observer.15200.log](https://github.com/robocorp/robotframework-lsp/files/8186484/robotframework_ls.remote_fs_observer.15200.log)
[intellij-rf-ls-2022-03-04-10640.log](https://github.com/robocorp/robotframework-lsp/files/8186490/intellij-rf-ls-2022-03-04-10640.log)

**Comment by podfran** [comment]
Still does not seem to work in 0.46.0...

**Comment by leetsin** [comment]
-----------------%<-----------------
Error in "import robot".
It seems that Robot Framework is not installed in /usr/bin/python.
Please install it in your environment and restart the Robot Framework Language Server
or set: "robot.language-server.python" or "robot.python.executable"
to point to a python installation that has Robot Framework installed.
Hint: with pip it can be installed with:
/usr/bin/python -m pip install robotframework
-----------------%<-----------------

OS: RHEL 8.7 Developer
Robot Framework Version: 6.0.2
Robot Framework Language Server: 1.7.3 installed from PyCharm UI.
PyCharm (Community Edition): 2022.3.1 was installed via flatpak from flathub.
Python: 3.10.6 in virtualenv

Our Issue:
The error message asks to set variables applicable for VS Code.

Our Questions : 
1. What is the corresponding setting(s) in PyCharm?
2. In which file do we enter the setting(s)?

**Comment by fabioz** [comment]
It should be in `File > Settings`.

The naming is derived (so, `robot.language-server-python` becomes `Language Server Python` (it should be easy to make the transform from any setting).

![image](https://user-images.githubusercontent.com/117621/212648652-0b77b593-26d4-412f-a232-925485657e8b.png)

**Comment by fabioz** [comment]
p.s.: Make sure you set the `Language Server Python` to the one that has `Robot Framework` installed.

**Comment by leetsin** [comment]
@fabioz 
Working.
Thanks.

**Comment by ennosof** [comment]
@fabioz Working also thanks :)
