### ISSUE TITLE
NONE for Test Setup / Teardown causes "Undefined keyword" error

### ISSUE THREAD

**Issue by MrBIN89** [robocorp/robotframework-lsp#597]
**Describe the bug**
Special `NONE` value (to disable test case setup or teardown) is highlighted red, complains `Undefined keyword: NONE`
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-setup-and-teardown:
`It is also possible to use value NONE to indicate that a test has no setup/teardown.`

**To Reproduce**
1. Type the code below in VSCode editor
```
*** Settings ***
Test Setup    NONE
Test Template    NONE
Test Timeout    NONE

*** Test Cases ***
My Test Case
    [Setup]    NONE
    [Template]    NONE
    [Tags]     NONE
    [Timeout]    NONE
    Should Be True    ${TRUE}
*** Keywords ***
```

**Expected behavior**
NONE is known and defined value for settings, such as Test Setup, Test Teardown, [Setup], [Teardown], Test Template, [Template], etc.
**Screenshots**
![изображение](https://user-images.githubusercontent.com/47885244/156874510-79c3854d-bc12-41fc-a79e-02932192239d.png)

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 4.1.3
 - Robot Framework Language Server Version: 0.41.0
 - Client Version: VSCode 1.65.0

**Comment by fabioz** [comment]
Thanks for the report. Marking as high-priority.

**Comment by fabioz** [comment]
This is now fixed. 

As a note, it's available in a pre-release if you want to check it (see: https://code.visualstudio.com/updates/v1_63#_pre-release-extensions on how to use pre-releases).
