### ISSUE TITLE
[Feature Request] Format file uniformly Based on New Line or Commented Line

### ISSUE THREAD

**Issue by Deep-Adhikary** [robocorp/robotframework-lsp#60]
Keyword 1           arg1
Big Keyword        arg1       arg2

Other Keyword Sample       Check
Small Keyword                      Check

Small Keyword    check

**Comment by Snooz82** [comment]
Format is based on Robot Framework's tool Tidy.
If you request a feature for the formatting, you should put the request to https://github.com/robotframework/robotframework/issues

**Comment by Deep-Adhikary** [comment]
Hi @Snooz82 
I was looking for the formatting structure  implemented in VS ode extension named ‘Robot Framework Formatter’

**Comment by Snooz82** [comment]
The "Robot Framework Language Server" plugin has nothing to do with the plugin you mentioned. And because it also has implemented the feature of "format document" it may interfere with this plugin.

The format function of Language Server just calls Tidy, which is a feature of Robot Framework Core.

**Comment by Deep-Adhikary** [comment]
Thanks @Snooz82 
This extension looks promising. I am waiting for full version to be released. Hope this will also have debugging feature. Some functionality yet to be implemented int it.

**Comment by fabioz** [comment]
Closing as this is really related to the actual Tidy formatter (so, formatting improvements should be done to that tool, not actually in the language server).
