### ISSUE TITLE
Intellij LSP: If the file type for *.robot was already set, plugin will not start

### ISSUE THREAD

**Issue by bhirsz** [robocorp/robotframework-lsp#605]
I have noticed in numerous cases that long time users of PyCharm couldn't get LSP for RF working. Only now I see the reason. If you worked with Robot Framework files and selected something else for file type for ``*.robot`` and ``*.resource`` file types it will be set forever and Pycharm will not invoke your plugin. In typical case people set it to *.txt automatically.

To change that you need to go to File -> Settings -> Editor -> File Types and ensure you have following configuration:
![image](https://user-images.githubusercontent.com/8532066/158775873-1df97d25-9f09-4193-9331-a8de1c71a247.png)

It could be worth adding this information to FAQ.

**Comment by fabioz** [comment]
I agree it's worth adding this to the faq.

**Comment by fabioz** [comment]
Closing this. The plugin itself (since `1.1.0`) will try to force the conversion if it's not done when it starts now.
