### ISSUE TITLE
Add possibility to set debug runnig settings and possibility to hide these line from code

### ISSUE THREAD

**Issue by MininAS** [robocorp/robotframework-lsp#606]
Sorry if I something missed but i couldn't find this options:

1. It would be nice to have possibility to hide debug lines. It is  confuses when writing a lot of code. Maybe it can some shotkey combination  "hide/show".
![image](https://user-images.githubusercontent.com/48047242/158958247-5f199db6-3c5b-420c-8919-e6b80261363a.png)

3. Would nice to have possibility to set own script for Run/Debug actions.

**Comment by fabioz** [comment]
Closing as this is already planned (with high priority) in https://github.com/robocorp/robotframework-lsp/issues/539 (it only mentions `Run/Debug` but the `Load Interactive Console` will be done as a part of it too).

As a note, it's possible to customize what that run does following the instructions at: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-configure-the-launch-from-a-code-lensshortcut

**Comment by fabioz** [comment]
As a note, this is now available in a pre-release (0.42.2).

See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/changelog.md for all that's changed in the pre-release.
