### ISSUE TITLE
`\` is not properly handled when passed as library arguments.

### ISSUE THREAD

**Issue by jkRobotic** [robocorp/robotframework-lsp#608]
**Describe the bug**
Use keyword generation by passed arguments to Library.
Keyword completion breaks if the Library argument links to an external file, e.g. txt:
![image](https://user-images.githubusercontent.com/87384643/159133481-76d8fb1d-c3a4-4162-86d9-f89e14edb00e.png)

**To Reproduce**
Steps to setup the environment:
1. Set robotframework configuration:
![image](https://user-images.githubusercontent.com/87384643/159133542-5618d962-6118-4dd4-8950-7bfac5267bd4.png)
2. Unzip `TestLib.zip` into your python environment and install it with command: `pip install -e <path/to/TestLib>`
3. Unzip `testRepo.zip` somewhere on your drive

Steps to make a positive test in PyCharm (or simple python console):
1. Load library TestLib with command: `from test_lib import test_lib`
2. Instantiate it with 'mapping' parameter `b = test_lib("path/to/functions2.txt")`
3. Check if `b.foo()` returns the passed argument
**Note: you can load the library also with classname `TestLib` like on the picture in python, but in VSCode only `test_lib` will work**
![image](https://user-images.githubusercontent.com/87384643/159134551-32b84aa8-4bf4-47eb-bef0-babba6ea4133.png)

Steps to reproduce in VSCode:
1. Load `testRepo` folder into VSCode
2. Change the path in `Library` call to your 'path/to/functions2.txt'
3. The library load fails due to error below:
![image](https://user-images.githubusercontent.com/87384643/159133865-c4d4b818-ad1a-45da-ab4d-f9d4d3489997.png)

**Expected behavior**
The keywords are generated properly and code completion will list them, like when the Library called without arguments:
**Note: the default path to functions.txt must be adapted in `TestLib/test_lib/base.py`!**
![image](https://user-images.githubusercontent.com/87384643/159134783-1ae7fd65-affc-40e0-ab83-8fab03969675.png)
![image](https://user-images.githubusercontent.com/87384643/159133918-cbe9fa51-5cc3-4cd3-bd57-2c75894fb539.png)

**Important:**
The keyword completion is broken, but the test run smoothly without errors:
![image](https://user-images.githubusercontent.com/87384643/159133954-6a1f806f-552e-450d-b6de-6935ef673fed.png)

**Versions:**
 - OS: Windows Server 2022
 - Robot Framework Version: 3.2.2
 - Robot Framework Language Server Version: 0.42.1 (Pre-Release)
 - Client Version: VSCode 1.65.2

**Attachments:**
TestLib written in python
testRepo with one suite and testcase inside. It contains the 2 exampel txt files also.
[TestLib.zip](https://github.com/robocorp/robotframework-lsp/files/8309873/TestLib.zip)
[testRepo.zip](https://github.com/robocorp/robotframework-lsp/files/8309874/testRepo.zip)

**Comment by fabioz** [comment]
As a note, the issue is that `\` isn't being properly handled in this case (it's not considering that `\` should escape the next char).

If you use `/` instead it should work.

**Comment by jkRobotic** [comment]
Hi, thank you for the quick fix!

Another issue also was in the system: the drive letter should be with lowercase...my fault, sorry.

In the meantime I found out that the problem was the '.' (dot) in the argument. If we remove the file extension (in the example above the '.txt') and of course from the original file also, the library will be loaded properly and the keywords will be generated.
![image](https://user-images.githubusercontent.com/87384643/159162084-ceb7c966-595d-4262-b145-bf019a25d32d.png)

If a '.' (dot) is presented in the argument, this error will happen during libdoc call:
```Resource file 'test_lib::d:/testRepo/functions2.txt' does not exist.```

Can you make a short check about this? Or miss I something again?

Thank you in advance!

**Comment by fabioz** [comment]
> If a '.' (dot) is presented in the argument, this error will happen during libdoc call: `Resource file 'test_lib::d:/testRepo/functions2.txt' does not exist.`
> 
> Can you make a short check about this? Or miss I something again?
> 
> Thank you in advance!

I'm not sure about this... can you provide all the info which is shown to you in `OUTPUT > Robot Framework` when that happens?

**Comment by jkRobotic** [comment]
Hi,

attached the logfile from the output.

1. test_lib didn't generated -> underlined with red line
2. hover on test_lib -> output shows the errors in the attachment.

If you need more logs, let me know how to get deeper.
[robotLog.zip](https://github.com/robocorp/robotframework-lsp/files/8311233/robotLog.zip)

**Comment by fabioz** [comment]
I just checked here... in this case the error message given by the `robot.libdoc` library is misleading.

In reality it tried to import `test_lib` and it didn't work and then afterwards it tries to import it as a resource and gives just a message for the second case.

So, what you need to do in this case is make sure that the directory which contains the `test_lib` folder needs to be in the pythonpath.


i.e.:  `<in_pythonpath>/test_lib/__init__.py`

If you set `robot.pythonpath` to include the related directory (`<in_pythonpath>`) it should work (but after adding it to the settings you need to use the action `Robot Framework: Clear caches and restart Robot Framework Language Server`).

**Comment by jkRobotic** [comment]
Thank you, I will try it!
