### ISSUE TITLE
No Other Robot Framework Plugins Working When Enable

### ISSUE THREAD

**Issue by Deep-Adhikary** [robocorp/robotframework-lsp#61]
When enabled, no other extension like Robot Framework Formatter is working. Unable to add brake point to run debugger. Request to enable these features until this framework is completely ready.

**Comment by fabioz** [comment]
Well, I don't think there's much to do here...

For the formatter, it seems you can choose which one by configuring the default formatter in VSCode. I haven't tested it, but I think it should work. See: https://github.com/microsoft/vscode/issues/41882#issuecomment-481038259 (the formatter used by `robotframework-lsp` is the one provided by the `robot.tidy` package, so, improvements should be done in it -- note: if wanted it should be possible to include a different formatter).

For the debugger, `robotframework-lsp` can't really fix that... it's up to the debugger to say that it can add breakpoints when the language is the one contributed by this plugin (i.e.: `robotframework`) -- by inspectingt its `package.json` it seems that it targets the language when it's `robot`. Note that there are plans to add debugging support in `robotframework-lsp` in the near future (but yes, it's not there yet).
