### ISSUE TITLE
False positive error "Unexpected argument" if  number of arguments in keyword is changed

### ISSUE THREAD

**Issue by JaPyR** [robocorp/robotframework-lsp#617]
**Describe the bug**
Seems like there is regression between 0.41.0 and 0.42.0 (also checked pre-release version 0.42.3). If understand correctly once information about keyword (keyword from another file) is loaded changes in number of arguments isn't propagated.

**To Reproduce**
https://user-images.githubusercontent.com/7773301/159745365-206209a9-816d-4488-a25e-1485b5c12e22.mp4

**Screenshots**
![image](https://user-images.githubusercontent.com/7773301/159744421-b80b2b0f-191f-4c48-9d0d-7f5f176745d4.png)

**Versions:**
 - OS: Win 10
 - Robot Framework Language Server Version: 0.42.0
 - VSCode 1.65.2

**Comment by fabioz** [comment]
Thanks for the report. This seems to be like an issue in the cache invalidation which was added in that version.

To workaround it you should be able to use the command:

`Robot Framework: Clear caches and restart Robot Framework Language Server`.

This is a high-priority issue, so, it should be fixed for the next release (I'll probably tackle it next week).

**Comment by fabioz** [comment]
There's a new release out (`0.43.0`) with a fix.

Can you check if it fixed your issue?

**Comment by JaPyR** [comment]
Not sure whether should create separate issue or it's related to what you are doing right now, but in 0.43.0 and 0.43.2 I've noticed regression compared to 0.42.0

For the code below i get "Undefined variable":
```python
# vars.py
__all__ = ["VALUES"]

VALUES = {}
VALUES["foo"] = 1
VALUES["bar"] = 2
```

```robotframework
*** Settings ***
Variables    vars.py

*** Test Cases ***
Demo
    Log    ${BAR}
```

![image](https://user-images.githubusercontent.com/7773301/160833514-37ea4ea8-0c8b-4070-9974-93661b9683a6.png)

**Comment by fabioz** [comment]
Please report that as a separate issue.

**Comment by JaPyR** [comment]
_Deleted my previous comment._ 

Sorry, I've made wrong example. For now I am not able to reproduce it.
