### ISSUE TITLE
restart the PyCharm,  loading this plugins ,then alert blow tips

### ISSUE THREAD

**Issue by wangAccount** [robocorp/robotframework-lsp#618]
Please provide information on the Python executable and arguments to be able to start the Robot Framework Language Server.

**Comment by fabioz** [comment]
This means that the plugin wasn't able to find the Python executable to start the language server.

You need to change the settings to specify the `Language Server Python` in the settings.

i.e.: 
![image](https://user-images.githubusercontent.com/117621/159902408-503c76e2-aecb-4f57-b55e-d07bb8fafa39.png)

**Comment by fabioz** [comment]
As a note, there's already a request to use the one already configured in PyCharm (in https://github.com/robocorp/robotframework-lsp/issues/370), and another to find venv automatically (https://github.com/robocorp/robotframework-lsp/issues/596) but those are still not done.

So, closing issue as there's nothing new to track here.

**Comment by wangAccount** [comment]
thanks you so much
