### ISSUE TITLE
Since update 0.43.3 searching for __init__.robot in every folder in my workspace

### ISSUE THREAD

**Issue by axi92** [robocorp/robotframework-lsp#626]
**Describe the bug**
Since the update yesterday I am missing the "Run, Run Debug" options inline.
And in the extention logs there always this message for every folder that I access:
```
server-api: 2022-03-30 10:03:40 UTC pid: 4027 - ThreadPoolExecutor-0_0 - INFO - robocorp_ls_core.workspace
Unable to load contents from: file:///home/user/repo/system-life-cycle/TestSuites/Tests/Komponenten_B-Lifecycle/__init__.robot

server-api: 2022-03-30 10:03:40 UTC pid: 4027 - ThreadPoolExecutor-0_0 - INFO - robocorp_ls_core.workspace
Unable to load contents from: file:///home/user/repo/system-life-cycle/TestSuites/Tests/__init__.robot

server-api: 2022-03-30 10:03:40 UTC pid: 4027 - ThreadPoolExecutor-0_0 - INFO - robocorp_ls_core.workspace
Unable to load contents from: file:///home/user/repo/system-life-cycle/TestSuites/__init__.robot

server-api: 2022-03-30 10:03:40 UTC pid: 4027 - ThreadPoolExecutor-0_0 - INFO - robocorp_ls_core.workspace
Unable to load contents from: file:///home/user/repo/system-life-cycle/__init__.robot

server-api: 2022-03-30 10:05:03 UTC pid: 4027 - ThreadPoolExecutor-0_0 - INFO - robocorp_ls_core.workspace
Unable to load contents from: file:///home/user/repo/system-life-cycle/Keywords/Testteam/__init__.robot

server-api: 2022-03-30 10:05:03 UTC pid: 4027 - ThreadPoolExecutor-0_0 - INFO - robocorp_ls_core.workspace
Unable to load contents from: file:///home/user/repo/system-life-cycle/Keywords/__init__.robot

server-api: 2022-03-30 10:05:03 UTC pid: 4027 - ThreadPoolExecutor-0_0 - INFO - robocorp_ls_core.workspace
Unable to load contents from: file:///home/user/repo/system-life-cycle/__init__.robot
```

**To Reproduce**
1. Open test or keywords file
2. See in "Output" Tab the Robotframework log

**Expected behavior**
No errors in log

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1394837/160783963-2ebc9a8c-84b6-4257-bfd6-c0b2421e4504.png)

**Versions:**
 - OS: Ubuntu 18.04
 - Robot Framework Version: 4.1.3
 - Robot Framework Language Server Version: 0.43.3
 - Client Version: Vscode remote

**Logs**
https://gist.github.com/axi92/06dc8be05ffabe48ea7c3df300846d88

**Comment by axi92** [comment]
For now I reverted to 0.42.0 where everything is still working.

**Comment by fabioz** [comment]
The Run/Debug options are now opt-in (given that you can run/debug from the run item in the gutter).

You can re-enable them with the setting:
`"robot.codeLens.enable": true`

As for the logging, that can be ignored. I'll change the logging from `info` to `debug` in that message so that it doesn't appear by default (but it doesn't really mean anything is wrong)..
