### ISSUE TITLE
Undefined variable error shown for variable with another variable within its name

### ISSUE THREAD

**Issue by VilleSalonen** [robocorp/robotframework-lsp#631]
**Describe the bug**
We are creating variables dynamically with names like ${SOME_VARIABLE_${i}}. These are reported by LSP as being undefined even though they work fine when run with Robot.

**To Reproduce**

    *** Test Cases ***
    Some Test Case
        [Setup]    Initialize Variables
        Log    ${SOME_VARIABLE_0}
        Log    ${SOME_VARIABLE_1}
        Log    ${SOME_VARIABLE_2}

    *** Keywords ***
    Initialize Variables
        FOR    ${index}    IN RANGE    3
            Set Test Variable    ${SOME_VARIABLE_${index}}    Value ${index}
        END

**Expected behavior**
I either expect that these would be properly detected as being valid variables OR being omitted from the analysis of undefined variables.

**Screenshots**
![image](https://user-images.githubusercontent.com/1070813/161049560-213f10b7-7593-46e8-a883-320263266ea3.png)

**Versions:**
 - OS: Windows 11
 - Robot Framework Version: 5.0
 - Robot Framework Language Server Version: 0.43.2
 - Client Version: 1.66

**Logs**
Logs can be recreated by running the sample code above.

**Comment by fabioz** [comment]
This should be fixed in the `0.43.5` pre-release (please test it -- if everything is ok a new stable release should be done -- hopefully tomorrow).

**Comment by VilleSalonen** [comment]
Thank you @fabioz. I will test this tomorrow at work.

**Comment by VilleSalonen** [comment]
This worked great!
