### ISSUE TITLE
Undefined variable lint error occurs when default value is provided for Environment Variables

### ISSUE THREAD

**Issue by blakewaud** [robocorp/robotframework-lsp#633]
**Describe the bug**
When a default value for an environment variable like %{MYVAR=defaultvalue}, RFW LSP thinks the variable name is “MYVAR=defaultvalue” instead of “MYVAR”, resulting in a lint error “Undefined environment variable: MYVAR=defaultvalue”

**Expected behavior**
No linting error occurs.

**Comment by fabioz** [comment]
This should be fixed in the `0.43.5` pre-release (please test it -- if everything is ok a new stable release should be done -- hopefully tomorrow).
