### ISSUE TITLE
Undefined variable error for variables imported by Import Variables

### ISSUE THREAD

**Issue by MrBIN89** [robocorp/robotframework-lsp#639]
**Describe the bug**
```
*** Settings ***
Force Tags    vscode
*** Variables ***

*** Test Cases ***
Imported Variables Should Be Defined Properly
    Import Variables    ${CURDIR}${/}variables.py
    Log To Console    ${PYTHON_VARIABLE}
```
**variables.py**:
```
def get_variables():
    return {"PYTHON_VARIABLE": 'value'}
```

**Expected behavior**
No any errors for PYTHON_VARIABLE since it is defined in variables.py file

**Screenshots**
![изображение](https://user-images.githubusercontent.com/47885244/161760284-ad2a2554-4e01-438f-8664-b418facbb83e.png)

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 4.1.3
 - Robot Framework Language Server Version: v0.43.2
 - Client Version: VSCode 1.66

**Comment by MrBIN89** [comment]
Please note, that in my case I can't define variable like described above.
Due to in my project the `get_variables` requires additional arguments that have an effect on variables values. So the workaround described above isn't usefull for my case

**Comment by fabioz** [comment]
I'm reopening this as I think that the case with `get_variables` and analyzing the returned dict may still be handled through heuristics.

**Comment by fabioz** [comment]
This should be fixed in the `0.43.5` pre-release (please test it -- if everything is ok a new stable release should be done -- hopefully tomorrow).

**Comment by MrBIN89** [comment]
Updated the RF Language Server to 0.47.2, it is reproduced still. I created new issue that duplicates it due to can't reopen this one again - https://github.com/robocorp/robotframework-lsp/issues/676

**Comment by fabioz** [comment]
Sorry, it seems I missed the part related to the `Import Variables` -- there was an issue handling the dynamic part of 

```
def get_variables():
    return {"PYTHON_VARIABLE": 'value'}
```

which I ended up fixing and thought it closed the issue. Let's leave this one closed and deal with the `Import Variables` in that new ticket then.
