### ISSUE TITLE
Support for Library Import with 'WITH NAME' syntax

### ISSUE THREAD

**Issue by Deep-Adhikary** [robocorp/robotframework-lsp#64]
It is necessary to Import a Library 'WITH NAME'  Syntax.
e.g.  Need two different instances for same library

Library&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DataReader&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      WITH NAME&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   Rreader1
Library&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      DataReader &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     WITH NAME&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   Rreader2

*** Keywords***
Sample Keyword
       &nbsp;&nbsp;&nbsp;Rreader1.read &nbsp;&nbsp;&nbsp;   File1
       &nbsp;&nbsp;&nbsp;Rreader2.read &nbsp;&nbsp;&nbsp;   File2

Presently it is not supported
![image](https://user-images.githubusercontent.com/13049680/81718456-61cdb600-9499-11ea-8d95-eef9d5eff02d.png)

**Comment by fabioz** [comment]
I changed the title to reflect that from the description, support is needed to deal with that construct in code analysis/code completion/find definition (syntax highlighting would be something different).
