### ISSUE TITLE
Don't report undefined references to any variable set as a global variable anywhere on the workspace.

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#641]
This needs a global index to collect any place which uses a `Set Global/Test/Suite Variable` keyword.

**Comment by scottpopa1** [comment]
I am also experiencing this issue.

**Comment by weltings** [comment]
Me too. I'm executing tests on 6 different environments. Environment dependent variables (e.g. URL, DB, MQ, REST etc.) are set as Global variables during test setup. This issue causes alot of false flags.

I can make a feeble attempt to fix this but I have no idea where to start.

**Comment by fabioz** [comment]
This should now be working. Please test if it does work for you in the latest pre-release (`0.47.5').
