### ISSUE TITLE
Test Status (Pass / Fail) not displayed on Test Explorer UI (in RF 3)

### ISSUE THREAD

**Issue by saurabh-c-rai** [robocorp/robotframework-lsp#644]
**Describe the bug**
We can use Test Explorer UI to run a particular robot test. However, after the test execution is completed, the result whether the test has passed or failed is not displayed on Test Explorer UI.  

**To Reproduce**
1. Open a robot file containing  at least  one test case.
2. Choose to run the test from the Test Explorer UI.
3. Wait for the test to complete and observe the colour of that particular test on the UI. 

**Expected behavior**
1. On the Test Explorer UI, the colour of the circle node near the test name changes to red in case the test passes or green in case the test fails.
2. The status of the test (i.e. the colour) should be preserved until we choose the clear test result option or vscode is restarted.
3. The count of the passed test should be updated.

**Screenshots**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/47693029/162255487-7803a05e-1893-4cb5-abb1-0f04e4b8a771.png">

**Versions:**
 - OS: [e.g. Mac OS Monterey]
 - Robot Framework Version: [3.2]
 - Robot Framework Language Server Version: [latest version]
 - Client Version: [VSCode Latest Version]

**Comment by fabioz** [comment]
As a note, this is related to RF 3 (RF 4 works properly for this).

**Comment by fabioz** [comment]
This is now fixed in the `0.44.1` pre-release -- feel free to grab the pre-release and check if it works for you ;)

**Comment by saurabh-c-rai** [comment]
Verified in the pre-release version. Working as expected.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/47693029/163115094-9b3f018d-cdc8-45b0-bcf5-c1d412476cae.png">
