### ISSUE TITLE
Backslash interferes with color highlighting

### ISSUE THREAD

**Issue by axi92** [robocorp/robotframework-lsp#647]
**Describe the bug**
When I use a backslash the color highlighting is not working.

**To Reproduce**
Use this Keyword:
```
SettingsFile
    [Arguments]    ${rc}=False    ${skipSignatureCheck}=True    ${no-repo-connection}=False
    [Documentation]    Echa parameter can be True/False/None
    ${settings_path}=    Set Variable    ${ROOT_DIR}/settings.properties
    OperatingSystem.Create File    ${settings_path}
    OperatingSystem.Append To File    ${settings_path}    verboseLogging = yes\n
    BuiltIn.Log    testmessage
    [Teardown]    OperatingSystem.Remove File    ${settings_path}
```
![grafik](https://user-images.githubusercontent.com/1394837/162969091-d3031c00-9904-404a-b812-5ea31e32b5a0.png)

**Expected behavior**
Without the backslash it is working:
```
SettingsFile
    [Arguments]    ${rc}=False    ${skipSignatureCheck}=True    ${no-repo-connection}=False
    [Documentation]    Echa parameter can be True/False/None
    ${settings_path}=    Set Variable    ${ROOT_DIR}/settings.properties
    OperatingSystem.Create File    ${settings_path}
    OperatingSystem.Append To File    ${settings_path}    verboseLogging = yes
    BuiltIn.Log    testmessage
    [Teardown]    OperatingSystem.Remove File    ${settings_path}
```
![grafik](https://user-images.githubusercontent.com/1394837/162969142-6d839619-6551-4caf-b21a-4d5dfdf195bc.png)

**Screenshots**
See above

**Versions:**
 - OS: Ubuntu 18.04
 - Robot Framework Version: [e.g. 3.2]
 - Robot Framework Language Server Version: v0.44.0
 - Client Version: VSCode Version: 1.66.1
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:51:26.173Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.13.0-39-generic snap

**Comment by fabioz** [comment]
This is now fixed in the `0.44.1` pre-release -- feel free to grab the pre-release and check if it works for you ;)
