### ISSUE TITLE
PyCharm 2022.1 (pre-release available).

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#652]

**Comment by cloutierjo** [comment]
Is this going to be released soon?

**Comment by fabioz** [comment]
Yes (probably tomorrow).

As a note, you can get a pre-release at:

https://github.com/robocorp/robotframework-lsp/actions/runs/2185433445

following the steps from:

https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-install-a-build-from-github-on-intellij

**Comment by cloutierjo** [comment]
Thanks

**Comment by fabioz** [comment]
Leaving open/pinned until the official release is done.

**Comment by fabioz** [comment]
An official release is now available so I'm closing this issue.
