### ISSUE TITLE
Intellij from current PyCharm 2022.1 not supported

### ISSUE THREAD

**Issue by DirkRichter** [robocorp/robotframework-lsp#655]
Plugin 'Robot Framework Language Server' (version '0.45.2') is not compatible with the current version of the PyCharm IDE. Plugin requires build 213.* or older but the current PyCharm build is #PY-221.5080.212.

To Reproduce
Open PyCharm 2022.1

Versions:
-    OS: Windows 10
-    Robot Framework Version: all
-    Robot Framework Language Server Version: 0.45.2
-    Client Version: PyCharm 2022.1

**Comment by fabioz** [comment]
This is already fixed. See: https://github.com/robocorp/robotframework-lsp/issues/652 for how to install a pre-release.

**Comment by DirkRichter** [comment]
Thanks. Sorry
