### ISSUE TITLE
Plugin is not compatible with the latest version of PyCharm 2022.1

### ISSUE THREAD

**Issue by ionutpetrache** [robocorp/robotframework-lsp#656]
**Describe the bug**
Plugin is not compatible with the latest version of PyCharm

**To Reproduce**
1. Install / update pycharm to latest version: Build #PC-221.5080.212,
2. Plugin is not working anymore or not visible in the list of plugins to be installed

**Expected behavior**
It should be able to use the robot framework language server plugin with the latest version of pycharm

**Screenshots**

**Versions:**
 - OS: Windows 10
 - Robot Framework Language Server Version: 0.45.2
 - Client Version:  PyCharm 2022.1 - Build #PC-221.5080.212

**Logs**

**Comment by fabioz** [comment]
This is already fixed. See: https://github.com/robocorp/robotframework-lsp/issues/652 for how to install a pre-release.

**Comment by ionutpetrache** [comment]
@fabioz thanks for the info!
