### ISSUE TITLE
Loop variables are not recognized in RF 3

### ISSUE THREAD

**Issue by saurabh-c-rai** [robocorp/robotframework-lsp#661]
**Describe the bug**
Loop variables are not recognized by the extensions inside the loop and a undefined variable message is displayed

**To Reproduce**
1. Run the below sample test case.
`Sample Keyword TC2
    &{dict_var}=    Create Dictionary    key1=value1    key2=value2
    FOR    ${key}    ${value}    IN    &{dict_var}
        Log To Console    Key is ${key}
        Log To Console    Value is ${value}

    END

    @{list_var}=    Create List    list_item1    list_item2    list_item3
    FOR    ${element}    IN    @{list_var}
        Log To Console    List Elements are ${element}

    END`
**Expected behavior**
1. Loops variable should be recognized by the extension.
3. Undefined variable message should not be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/47693029/164643381-9110c755-20d2-4bdd-9a07-a2de61e4bf4a.png)

**Versions:**
 - OS: [MacOS Monterey]
 - Robot Framework Version: [RF 3.2]
 - Robot Framework Language Server Version: [Latest Version]
 - Client Version: [VSCode Latest version]

**Comment by fabioz** [comment]
You're right. As a note, this only happens in RF 3.

I'll make sure this is fixed for the next release.

Code:

```
*** Test Cases ***
Check variables
    &{dict_var}=    Create dictionary    key1=value1    key2=value2
    FOR    ${key}    ${value}    IN     &{dict_var}
        Log to console    Key is ${key}
        Log to console    Value is ${value}
    END
```
