### ISSUE TITLE
Add "Robot-Lint Environment Variables" Report issues in undefined environment variables

### ISSUE THREAD

**Issue by IlfirinPL** [robocorp/robotframework-lsp#663]
For project that  use environment variables and using direct read  %{VAR}  instead of Get Environment Variable
is rising error "Undefined environment variable"

I would like to have option that disable check of variables that start with %{} aka environment variable

**Comment by fabioz** [comment]
That really needs to be implemented (should be straightforward though).

Now, out of curiosity, can you elaborate a bit on your case? (i.e.: why don't you have those environment variables set in your environment?)

**Comment by IlfirinPL** [comment]
@fabioz  For task that are execute via pipeline in Jenkins/Gitlab, and your local environment don't have values and they are only set during execution ex. via (launch.json)

**Comment by fabioz** [comment]
Humm, as a note, one thing which could be interesting here is having a variable with a default value (this way code analysis wouldn't trigger it and you wouldn't need to specify per launch).

i.e.: Something as: `%{GITLAB=false}`

Also, if you don't need to specify per-launch (which is usually the case in these situations), you could specify it to the language server using the `robot.python.env` setting (that way it'd be available both for the launch as well as during the analysis).

i.e.: Something as:

```
  "robot.python.env": {
    "my_root": "${workspaceFolder}"
    "GITLAB": "false"
  }
```

**Comment by IlfirinPL** [comment]
I don't use  `robot.python.env` because, setup its static.  I need different values.
Also in some cases lack of environment variable is also information 

The best solution for me would be that  VS would read launch.json and notice that env variable are declared

I use mainly launch.json because of functionality Input variables

https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

example  launch.json
```
{
    "configurations": [
        {
            "type": "robotframework-lsp",
            "name": "Robot Framework: Launch template",
            "request": "launch",
            "env": {
                "URL": "${input:url}",
            },
        },
    ],
    "inputs": [
        {
            "id": "url",
            "type": "pickString",
            "description": "Select url",
            "options": [
                "url-1",
                "url-2",
                "url-3",
            ],
        }
    ]
}
```
