### ISSUE TITLE
[Arguments]     ${first}    ${second}=${first}

### ISSUE THREAD

**Issue by MininAS** [robocorp/robotframework-lsp#664]
If a argument default value is set a previous argument in the same keyword then extension doesn't display it like defined
![image](https://user-images.githubusercontent.com/48047242/165260956-fa9baa43-9db3-428e-9847-3cb7498c0df9.png)

Also there is strange that if add just resource name the argument becomes defined.
![image](https://user-images.githubusercontent.com/48047242/165261482-29d06e36-962b-4d63-93a0-2a265d2e5dbd.png)

**Comment by fabioz** [comment]
This is fixed in master.

A pre-release (`0.46.2`) is already available with the fix too.
