### ISSUE TITLE
Suite of test Cases execute instead of Single Test cases that is selected.

### ISSUE THREAD

**Issue by bradbaker123** [robocorp/robotframework-lsp#667]
** commentary **
I am a VSCode RF newbie...
This issue didn't occur at first, only after I was working with VSCode and RoboFramework to fine tune settings, etc.

 I use to be able to click run just above a test case and only that test case would run.  Now I get the entire suite of test cases to run when I am trying only to get 1.  I have been trying to understand the settings, I have tried uninstalling, I have uninstalled all the extensions and re-installed.  Any help to get me back to where I just can run 1 test case is appreciated.  I know I can run it from the command line but I am hoping to have the ease of running it with a simple click.  Let me know if there is something else I can provide.

**Describe the bug**
When I click Run above 1 test case, I should only get that test case to run but the testing starts with the first test case in the .robot file and continues through the suite.

**To Reproduce**  (see video attached)
1. Start VS Code and wait for the environment to complete in the lower right.  
2.  Select a .Robot file with test Cases in it.
3. Select run from above the second test in the file.

**Expected behavior**
Only the 1 test case should run.

Actual Behavior
as I watch the results in Terminal, It starts at the top of the .Robot file executing test cases and continues with the test cases in the file.

**Comment by blakewaud** [comment]
This might be a bug, I am not sure, but you are able to do a workaround by adding the command line option `--test <test name>` to the shell command in your `robot.yaml` where `<test name>` is the single test case you are trying to run (encapsulated in quote marks if the test case name has spaces). You can then run the robot task via the Robocorp Code extension and it will only run the defined test.

More documentation on that feature here: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#selecting-test-cases

**Comment by fabioz** [comment]
A question: if you use `cmd` instead of `powershell`, does it work?

If not, can you provide some more info?

To collect that info, please do the following:

1. Set the following environment variables (this can be set on the system and then restart VSCode so that it gets those -- you can customize the log location to a different place if you'd like):
    - `ROBOTFRAMEWORK_DAP_LOG_FILENAME=c:/temp/robot_dap.log`
    - `ROBOTFRAMEWORK_DAP_LOG_LEVEL=3`

2. Make the run.

3. Collect the following data and attach it to this issue:

- Full command line which is printed to the terminal when it starts.
- When the command line is printed, it also shows a `.bat` (a `run_env_XXXX.bat`), please provide that too.
- The logs generated (note that it may actually produce multiple `robot_dap<pid>.log` files, please attach all).
Note: those files may have confidential info, so, please take a look and scrub things you don't want to share...

**Comment by bradbaker123** [comment]
### I was able to run a single test case from the Command line.  

C:\source\QAAutomation\WebAutomation\Quest\Tests>robot -d ../results -t "Q4 - US_ApplicantLog_001_Change Filters" ./UATRegression/ApplicantLog.robot
==============================================================================
ApplicantLog :: Applicant Log in Quest - These scripts cover the UAT regres...
==============================================================================
Q4 - US_ApplicantLog_001_Change Filters
DevTools listening on ws://127.0.0.1:55711/devtools/browser/6d1e3940-4235-4072-a201-c0c9aeea2a16
..[43760:49000:0502/070650.864:ERROR:device_event_log_impl.cc(214)] [07:06:50.854] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[43760:49000:0502/070650.864:ERROR:device_event_log_impl.cc(214)] [07:06:50.855] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[43760:49000:0502/070650.864:ERROR:device_event_log_impl.cc(214)] [07:06:50.855] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)

DevTools listening on ws://127.0.0.1:55737/devtools/browser/c763a793-b9b7-469a-aa69-bbd1aefb9e77
Q4 - US_ApplicantLog_001_Change Filters                               | FAIL |
' 0 > 0' should be true.
------------------------------------------------------------------------------
ApplicantLog :: Applicant Log in Quest - These scripts cover the U... | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
Output:  C:\source\QAAutomation\WebAutomation\Quest\results\output.xml
Log:     C:\source\QAAutomation\WebAutomation\Quest\results\log.html
Report:  C:\source\QAAutomation\WebAutomation\Quest\results\report.html

C:\source\QAAutomation\WebAutomation\Quest\Tests>


+++++++++++++++++++++++++++++++++++++++++++++++++
Here is the additional items requested.    Full command line when it starts.
+++++++++++++++++++++++++++++++++++++++++++++++++
PS C:\source\QAAutomation>  & 'C:\Users\BRADLE~1\AppData\Local\Temp\rf-ls-run\run_env_00_86zwyhyt.bat' '-u' 'c:\Users\BradleyBaker\.vscode\extensions\robocorp.robotframework-lsp-0.46.0\src\robotframework_debug_adapter\run_robot__main__.py' '--port' '55955' '--no-debug' '--pythonpath' '' '--prerunmodifier=robotframework_debug_adapter.prerun_modifiers.FilteringTestsSuiteVisitor' 'c:\source\QAAutomation\WebAutomation\Quest\Tests\UATRegression\Company.robot'
==============================================================================
[run_env_00_86zwyhyt.bat.txt](https://github.com/robocorp/robotframework-lsp/files/8602739/run_env_00_86zwyhyt.bat.txt)
[robot_dap.dap.46528.log](https://github.com/robocorp/robotframework-lsp/files/8602793/robot_dap.dap.46528.log)
[robot_dap.robot.50180.log](https://github.com/robocorp/robotframework-lsp/files/8602798/robot_dap.robot.50180.log)

**Comment by fabioz** [comment]
A question, if you set an environment variable such as:

`ROBOTFRAMEWORK_LS_LAUNCH_ENV_SCRIPT=0`

And try to do a run, does it work?

**Comment by bradbaker123** [comment]
It exhibits the same behavior.

**Comment by fabioz** [comment]
I just did a pre-release (`v0.46.4`). Can you get that version and check if it works for you?

If it doesn't, please provide new logs (following the instructions from https://github.com/robocorp/robotframework-lsp/issues/667#issuecomment-1112172558).

**Comment by fabioz** [comment]
I think that the problem is that there was an empty `--pythonpath` entry (not sure why that happened in your case...).

**Comment by bradbaker123** [comment]
You solved the Issue.  Thank you.  I had problems as I was trying to adjust settings.  My libraries were not being found and I was manipulating Pythonpath ... it must have been in that ... that I caused the issue.   Thanks again.

**Comment by bradbaker123** [comment]
Problem Solved!!!
