### ISSUE TITLE
`AS` keyword in new `TRY/EXCEPT` feature not syntax highlighted

### ISSUE THREAD

**Issue by blakewaud** [robocorp/robotframework-lsp#673]
When defining a variable to catch the error message in the `EXCEPT` clause, the `AS` is not highlighted the same as the `EXCEPT`:

![image](https://user-images.githubusercontent.com/93772257/167477588-a7384d5d-f50a-42eb-befa-7bedcc7bdc30.png)

**Comment by blakewaud** [comment]
This is on v0.46.6

**Comment by fabioz** [comment]
@blakewaud are you using any other Robot Framework extension by any chance?

I can't reproduce the issue and the coloring is all messed up (not just the `AS`, the variables are also strange), so, my guess is that you have another extension which is messing things up...

**Comment by blakewaud** [comment]
@fabioz I don't have any other extensions that impact my theme (currently using `Dark+`) or syntax highlighting of robot files... but I tried to reload the window again, and this time it highlighted it correctly, so I guess it was just misbehaving.
