### ISSUE TITLE
Support `Import Library` keyword

### ISSUE THREAD

**Issue by Reddriver** [robocorp/robotframework-lsp#675]
I have a script with dynamic import of Dialogs library and I call KW Pause Execution inside IF block. So, I would like to ignore error in Problems tab: ,,Undefined keyword: Pause Execution" in Visual Studio Code (Robot Framework Language Server). Is there a way to ignore one line with error?

We use dialogs lib on local station for pause test on failure (classic run, not in debug mode VS). Dialogs lib can't be import on openshift, that is the reason for this code. I don't know .libspec, but I'll try study or we will stop using dialogs (we run in debug mode more often)

I imagined there is something like Keyword That Is Longer Than Allowed Line Length  ${arg}  # robotidy: off in robotidy, just ignore one line.

```
*** Keywords ***
Teardown KW
    [Documentation]  teardown
    IF  not ${OPENSHIFT}
        Run Keyword If Test Failed  Pause Execution  Test skončil s chybou:\n${TEST_MESSAGE}
    END

*** Test Cases ***
Test
    ${isOpenshift}  Set Variable If  "%{KUBERNETES_PORT=}"  True  False
    Set Global Variable  ${OPENSHIFT}
    IF  ${OPENSHIFT}
        Import Library  Dialogs
    END
```

**Comment by fabioz** [comment]
This should now be working. Please test if it does work for you in the latest pre-release (`0.47.5').

**Comment by Reddriver** [comment]
@fabioz I tested this enhancement on v0.47.6 and it worked, thank you.
