### ISSUE TITLE
Support customizing spacing betwen keyword and arguments when auto-completing Keyword with arguments.

### ISSUE THREAD

**Issue by fredrikstahre** [robocorp/robotframework-lsp#683]
When auto-completing a keyword the spacing between the keyword and the parameter is set to 4 spaces. It would be good to be able to configure if the user wants to use a tab instead.

**Comment by fabioz** [comment]
Note: it should be possible to use a tab or customize number of spaces.

**Comment by Snooz82** [comment]
There is already a setting in LSP plugin to use four spaces instead of tab.

is that not takes for argument completion?

**Comment by fabioz** [comment]
@Snooz82, no, the issue here is when applying a code-completion which automatically adds arguments the spacing is not customizable.

-- i.e.: on `Should be equal   a   b` the number of spaces/tabs between `Should be equal` and `a` and `a` to `b` should be customizable (or maybe even `|`).

**Comment by Snooz82** [comment]
Ok. But do you use the same option for that?

**Comment by Snooz82** [comment]
Or take the setting from the vscode file settings for indenting ?

**Comment by fabioz** [comment]
That's a good point... I think it should probably be a new setting, I have to think a bit but probably this new setting would override the text of the `4spacesTab` setting when pressing tab too (`4spacesTab` is probably too specific, so, possibly it should be deprecated for a new setting where the user defines the delimiter).

Maybe the setting should be something as:

`robot.editor.useCustomSeparator: <true|false>`
`robot.editor.separator: <separator text>`

Then the separator could be even something as `" | "` or '"\t"` (for those that use such an approach).

The default would mimic the current `4spacesTab`.

i.e.:

```
"robot.editor.useCustomSeparator": true
"robot.editor.separator": "    "
```

What do you think @Snooz82?

**Comment by fabioz** [comment]
I started to implement this, but decided to only tackle the issue of customizing the text for the case where the arguments are added automatically by the language server and not tackling how tab is handled as the common use case is for the user to enter 4 spaces when tabs is used and the `robot.editor.4spacesTab` does cover that well enough.

If the user wants to tackle how tab is handled there are other possibilities such as:

- Create a global snippet and bind `tab` to it.
- Set `robot.editor.4spacesTab` to false and use the default VSCode editor tab handling (https://stackoverflow.com/questions/34174207/how-to-change-indentation-in-visual-studio-code).

The end result is that just a new setting will be added:

`"robot.completions.keywords.argumentsSeparator"` 

which will allow users to select the separator between keyword arguments (when it's automatically applied).

as that should be enough for users to customize it as needed.

To use tab it'd be something as:

`"robot.completions.keywords.argumentsSeparator": "\t"`
