### ISSUE TITLE
Treat `For each input work item` like other `run` type keyword

### ISSUE THREAD

**Issue by blakewaud** [robocorp/robotframework-lsp#684]
The keyword `For each input work item` out of the `RPA.Robocorp.WorkItems` library should use syntax highlighting similarly to `Run keyword` where the keyword to be ran is recognized as a keyword call. As this is a Robocorp-specific keyword, if we do not want to add that support directly into LSP, can we get some way to define such run keywords in the LSP config?

**Comment by fabioz** [comment]
Should be straightforward to add (and I think it should be done at the `Robot Framework Language Server` -- right now keywords are hard-coded there... ideally this should be in the libspec, but until then just hard-coding it there is straightforward).
