### ISSUE TITLE
Latest pre-release version not working for RF3.2

### ISSUE THREAD

**Issue by saurabh-c-rai** [robocorp/robotframework-lsp#685]
**Describe the bug**
Getting error `Error collecting Robocop errors: No module named 'robot.api.parsing'` when opening any robot file after upgrading to the latest pre-release version of VSCode Extenson

**To Reproduce**
1. Ensure the Robotframework language server for VSCode is on the latest pre-release version (currently 0.47.6)
2.Open any RF3.2 project.
3. Observe the error in the Settings section as displayed in the screenshot below.
 
**Expected behavior**
No error in parsing the robot file.

**Screenshots**
![image](https://user-images.githubusercontent.com/47693029/169888736-2a9e6cf5-20db-4740-95c5-4090bfbbe46a.png)

**Versions:**
 - OS: [e.g. MacOS Monterey]
 - Robot Framework Version: [3.2]
 - Robot Framework Language Server Version: [0.47.6]
 - Client Version: [VSCode Latest Version]

**Logs**

[log.txt](https://github.com/robocorp/robotframework-lsp/files/8757482/log.txt)

**Comment by fabioz** [comment]
Thanks for the report. This was fixed a few hours ago in https://github.com/robocorp/robotframework-lsp/commit/5240c202f74e508d4bd68d3fb004d0560e05f120 ;)

I'll do a new pre-release in a few minutes (just need to include one more thing...).

**Comment by fabioz** [comment]
Ok, just did the pre-release (it may still take a few more minutes to appear at the VSCode marketplace).

A `.vsix` may be found at: https://github.com/robocorp/robotframework-lsp/actions/runs/2373562140
