### ISSUE TITLE
run keywords, not recognizing the keywords within

### ISSUE THREAD

**Issue by Sam-Eldin** [robocorp/robotframework-lsp#686]
**Is your feature request related to a problem? Please describe.**
When using 'run keyword' I don't see the keywords colored as if the plugin didn't recognize them as Keywords
(I can jump to their implementation/definition though, so that's cool. :) )
  
**Describe the solution you'd like**
For the plugin to able to tell that they are also Keywords inside one big Keyword

**Describe alternatives you've considered**
I didn't 

![image](https://user-images.githubusercontent.com/49291807/169901397-445d09ba-2f66-42f8-824d-4f6f828cab01.png)

**Comment by fabioz** [comment]
The issue seems to be recursively identifying a `run keyword` inside a `run keyword` (in this case a `run keywords` inside a `wait until keyword succeeds` inside a `run keyword if`).

**Comment by Sam-Eldin** [comment]
Update me when the issue is resolved so I can close it.
Thanks!!

**Comment by fabioz** [comment]
I've just published a pre-release with a fix (0.47.9), so, you can get it and check if it works for you...
