### ISSUE TITLE
[Feature Request] Python Like Intellisense for Robot Framework For Loops, ELSE IF

### ISSUE THREAD

**Issue by Deep-Adhikary** [robocorp/robotframework-lsp#69]
It Would be  helpful if place holder like intellisense is given for Robot Framework For Loops & ELSE IF  l
![image](https://user-images.githubusercontent.com/13049680/81898135-b70ee200-95d5-11ea-8458-7c6877af2093.png)
![image](https://user-images.githubusercontent.com/13049680/81898207-d9086480-95d5-11ea-90a1-b292afb76fe2.png)

**Comment by Snooz82** [comment]
This is a nice idea!

At the moment i would think that these `code snippets` would be easy and super helpful.

i think these could be the code snippets:

FOR/IN RANGE
 ```
   FOR    ${i}    IN RANGE    ${START}    ${END}    ${STEPS}
        Log    ${i}
    END
```

FOR/IN
```
    FOR    ${element}    IN    @{LIST}
        Log    ${element}
    END
```

FOR/IN ENUMERATE
```
    FOR    ${index}    ${element}    IN ENUMERATE    @{LIST}
        Log    ${index}: ${element}
    END
```

FOR/IN ZIP
 ```
   FOR    ${number}    ${name}    IN ZIP    ${NUMBER_LIST}    ${NAME_LIST}
        Log    ${number}: ${name}
    END  
```

When IF/ELSE IF/ELSE will be introduced to robot in RF 4 this could then be added as well.

**Comment by Snooz82** [comment]
@fabioz i just found out that these snippets are part of the VSCode Plugin.

i will prepare a PR for this later this day. So if you want to release, you may want to wait and include this PR. ;-)

**Comment by Snooz82** [comment]
Preview:

![image](https://user-images.githubusercontent.com/41592183/82220895-8bfef800-991f-11ea-9d86-edff168aa0d3.png)
![image](https://user-images.githubusercontent.com/41592183/82220919-93be9c80-991f-11ea-8c1f-c1d2082336c0.png)

**Comment by fabioz** [comment]
@Snooz82 yes, that'd work for VSCode, but it'd be nice to have them for other clients too (which doesn't really work if it's done that way).

I'm doing a reasonably big refactoring right now (with the idea of making it possible to do another extension using the same codebase), but as soon as I finish this I'll implement that (it should be straightforward to do).

**Comment by Snooz82** [comment]
@fabioz I just figured out 15 min ago and have it running already. I had to leave now but it is a quick win and we can delete it once the other way is implemented...

**Comment by fabioz** [comment]
This is fixed in https://github.com/robocorp/robotframework-lsp/commit/2a171a0b1ed8eba10e35dcd812c32d02016c85e2.
