### ISSUE TITLE
Variable files imported as modules are not resolved

### ISSUE THREAD

**Issue by mlschmidt366** [robocorp/robotframework-lsp#699]
**Describe the bug**
Since Robot Framework 5.0, variable files can be imported as modules, as described in the [release notes](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-5.0.rst#variable-files-can-be-imported-as-modules). This new syntax does not seem to be recognized by the Language Server. The error 'Unresolved variable import' is shown instead.

**To Reproduce**
If a variable file is imported like
`Variables    module/subfolder/varfile.py`,
then changing the line to use the new 'import as module' syntax will reproduce the error:
`Variables    module.subfolder.varfile`.

**Expected behavior**
Both ways of defining the import should work. The import should be resolved correctly and variables that are defined in the imported file should hence not be marked as 'undefined variables'.
The new syntax is explained in more detail in the Robot Framework User Guide, [section 2.8.2 Variable Files -> Taking variable files into use](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-files).

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 5.0
 - Robot Framework Language Server Version: 0.48

**Comment by fabioz** [comment]
Note: I've just published a pre-release (`0.48.3`) with the fix. If you're able to, please grab that version and test it...
