### ISSUE TITLE
Robot Framework Language Server 0.49.0 is not compatible with PyCharm 2022.2 Build #PY-222.3345.131, built on July 27, 2022

### ISSUE THREAD

**Issue by DirkRichter** [robocorp/robotframework-lsp#718]
**Describe the bug**
Robot Framework Language Server 0.49.0 is not compatible with PyCharm 2022.2 Build #PY-222.3345.131, built on July 27, 2022

**To Reproduce**
1. Install PyCharm v. 2022.2 Build #PY-222.3345.131
2. Install RobotFramework LS Plugin v 0.49.0

**Expected behavior**
RobotFramework LS Plugin is working.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/20930315/182786630-f2c5a2d4-b943-47e4-b238-b057d064f36d.png)

**Versions:**
 - OS: Win11
 - Robot Framework Version: 5
 - Robot Framework Language Server Version: 0.49.0
 - Client Version: PyCharm v. 2022.2 Build #PY-222.3345.131

**Comment by manojatlas** [comment]
Facing same issue. any solution for this?

**Comment by fabioz** [comment]
It's fixed in the repo, but it still requires a new release (which I'll do tomorrow).

**Comment by fabioz** [comment]
Ok, the release is now done.

It may take some time to appear in the marketplace, but in the meanwhile it's possible to get it at:

https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server/versions/stable/206705
