### ISSUE TITLE
Findout the unused(not used anywhere) keywords in a robot suite file

### ISSUE THREAD

**Issue by kumneeruaks** [robocorp/robotframework-lsp#722]
**There should be a way to identify the unused keywords in robot suite file**
To reduce the coding lines which are not used and to reduce the PR comments :-)

**Comment by fabioz** [comment]
Ok, I've done the first take on this and did a pre-release (1.0.3) -- note that it may take some minutes to appear in the marketplace.

It was implemented to be run during code-analysis.

It's opt-in, so, one must set the setting:

"robot.lint.unusedKeyword": true

so that this analysis is done.

**Comment by emakaay** [comment]
Nice :+1:

**Comment by MAPJe71** [comment]
How to disable message for specific keywords?
