### ISSUE TITLE
Reporting error when multiple keywords with the same name are found cause keywords from libraries that depend on `Builtin.Set Library Search Order` to be detected as errors.

### ISSUE THREAD

**Issue by burrk** [robocorp/robotframework-lsp#724]
Enhancement https://github.com/robocorp/robotframework-lsp/issues/432 causes code which depends on `Builtin.Set Library Search Order` (http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Set%20Library%20Search%20Order) for pseudo-OOP polymorphism to be detected as errors (most of our robot code turns red).

In addition setting `"robot.lint.keywordResolvesToMultipleKeywords": false` to turn this feature off, **causes LSP to miss other problems** in the same code.

This is from a conversation with @fabioz on the RobotFramework's Slack channel: https://robotframework.slack.com/archives/C01AWSNKC2H/p1659529202045659?thread_ts=1659365333.316959&cid=C01AWSNKC2H

Set Library Search Order is especially important for RF Page Object frameworks:
- The RobotFramework-PageObectLibrary uses it to move the current page`s code to the front of the keyword search order.  Code: https://github.com/boakley/robotframework-pageobjectlibrary/blob/0ecc01a001196bce4f60528628b5f0b243928e43/PageObjectLibrary/keywords.py#L56
- Salesforce's CumulusCI's Robot Framework Page Object code uses it similarly: https://github.com/SFDO-Tooling/CumulusCI/blob/cd3be712e3e2fa06a8bd0e6b70e94924a2764a51/cumulusci/robotframework/pageobjects/PageObjects.py#L345 (same author)
- In the past, I used it in a simple RF script based page object framework:  (Every page library had a unique `Verify Page Loaded` function, as well as other functions with identical names, like `Submit`)
```robotframework
On Page
    [Arguments]    ${page}
    [Documentation]  Changes library search order so page object's name does not have to appended to each keyword
    ...    
    ...    It *also verifies the page has been loaded*.  This all makes the code easier to read. For example:
    ...    
    ...    Instead of:
    ...    | LogonPage.Verify Page Loaded  |             |
    ...    | LogonPage.Set User Name Field | ${username} |
    ...    | LogonPage.Set Password Field  | ${password} |
    ...    | LogonPage.Submit              |             |
    ...    
    ...    Use:
    ...    | On Page | LogonPage           |             |
    ...    |         | Set User Name Field | ${username} |
    ...    |         | Set Password Field  | ${password} |
    ...    |         | Submit              |             |
    ...    _(Empty first column is just for readability)_
    ...
    ...    See also 
    ...    [http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Set%20Library%20Search%20Order|Set Library Search Order] 
    ...    and each page's ``Verify Page Loaded`` keywords
    ...    
    Set Library Search Order	${page}
    Verify Page Loaded
```
- I'm sure people use `Set Library Search Order` for other things as well :-)

**Comment by fabioz** [comment]
Humm, checking the example and reading through the source code of PageObject made me realize it's nearly impossible to know which is the library order used (because it's defined at runtime and it's not possible to know it statically -- I know I can't make sense of what'd be the expected keyword order just by looking at the code).

This is making it skip signature checks afterwards because previously what'd happen is that when there was a conflict it'd pick one at random and analyze it and now the analysis is skipped because choosing one at random is bound to have problems...

One question: in your use case, in the face of such conflicts, do the keywords usually have the same signature or would that vary?
If they're usually the same, one thing that could be done is that it'd make the signature analysis even if a conflict is found (if the signature is the same this would be possible, but if the signature is different each time then it'd be nearly impossible to get it right because the code structure which relies on using the `Set Library Search Order` at runtime makes it impossible to reason through that statically).

**Comment by burrk** [comment]
Hi Fabio,
I don't know how `Set Library Search Order` makes its choices.  It could be smart enough to match keywords with the same signature, like overloading does in other languages (C++, etc), or it might just match keyword names.  That would be a question for the RF people.

For us, we are just careful to (consciously) keep the required parameters the same - although we may occasionally cheat with some hidden default parameters...  I can't remember if other languages would let us get away with that.  

It may be better to check with the CumulusCI project, since they probably have more people who have been using this longer than my small team.  As I mentioned, there must also be other uses for `Set Library Search Order` than to implement Page Objects.

It would be really nice to have you analyze the overloaded keywords, but at a minimum it would be great for LSP to still analyze the code and ignore the overloaded functions, rather than to have to turn the analysis off all together.  (Leaving all our code red isn't really an option)

Thank-you!

**Comment by burrk** [comment]
Thanks @fabioz! How can I try this out?  ...I've not needed to follow a fix into a release before.

**Comment by fabioz** [comment]
@burrk I've just published a new pre-release (`1.0.6`) which you can use to test (it may still take a few minutes to appear).

Please let me know how testing went.

**Comment by burrk** [comment]
Hi @fabioz, It may be worse...

I upgraded to 1.0.6, and added `"robot.lint.keywordResolvesToMultipleKeywords": false` to my settings file and (almost) all the errors disappeared - everywhere.   When I linted my test folder (nice feature :-)  **it only found one error in one file** - and our code is no-where near that good. That error should appear multiple times (we use a decorator to make parameters optional in a way LSP doesn't understand)

I restarted VSCode a couple of times and waited - just to make sure I wasn't jumping to conclusions

I also looked in the "Robot Framework" OUTPUT Terminal, and all I saw was timeout thread dumps for taking too much time.

**Comment by burrk** [comment]
@fabioz   A few more restarts and lint requests it did start to find more errors - not as many as I expected - but I don't remember what all the errors were before you added this feature. I'm pretty sure there should be more - at least some yellow ones, right now there are a few red ones dealing with unexpected or missing parameters (as I expected)
