### ISSUE TITLE
Pycharm LSP Support: Variable displays in autosuggestion list. But when click on Enter it does not Insert

### ISSUE THREAD

**Issue by srinivasskc** [robocorp/robotframework-lsp#73]
Detailed description of the bug or suggestion
----------------------------------------------
I am using Pycharm 
![image](https://user-images.githubusercontent.com/26836928/82399817-98946500-9a73-11ea-8881-de9beaffdbbc.png)

Have Installed LSP Support Plugin.
![image](https://user-images.githubusercontent.com/26836928/82399947-d5f8f280-9a73-11ea-8dc5-cb24b0888c37.png)

I have created a variable name ${title} and when trying to fetch it via Auto Suggestions, It displays in autosuggestion list. But when press Enter Key to Insert, the Variable does not insert.

Extension logs (attach as a file)
----------------------------------------------
[Logs.zip](https://github.com/robocorp/robotframework-lsp/files/4654391/Logs.zip)

Minimal example (if possible)
----------------------------------------------
Attached the screenshots for reference:

![image](https://user-images.githubusercontent.com/26836928/82399859-a9dd7180-9a73-11ea-9921-f4fb345d08c1.png)

![image](https://user-images.githubusercontent.com/26836928/82399901-be216e80-9a73-11ea-8ea2-6494642e03c9.png)

**Comment by fabioz** [comment]
I'm closing this issue here since there's nothing to be done in the language server (it's an issue in the language server client -- I've reported it at: https://github.com/gtache/intellij-lsp/issues/148).
