### ISSUE TITLE
`.resource` files don't work in pycharm plugin

### ISSUE THREAD

**Issue by DetachHead** [robocorp/robotframework-lsp#736]
**Describe the bug**
the pycharm plugin doesn't register `.resource` files as robot files

**To Reproduce**
1. Open file with `.resource` extension

**Expected behavior**
syntax highlighting

**Screenshots**
![image](https://user-images.githubusercontent.com/57028336/186302589-885e8a6f-1bb6-461f-9528-3464c55e8a10.png)

**Versions:**
 - OS: windows 10
 - Robot Framework Version: 5.0.1
 - Robot Framework Language Server Version: 1.0
 - Client Version: pycharm 2022.2.1

**Comment by fabioz** [comment]
It does register both `robot` and `resource` files (see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-intellij/src/main/resources/META-INF/plugin.xml#L27), and on a clean install things should work as intended.

Unfortunately, Intellij itself is kind of buggy in the area and if you had another extension which had that association and you removed it or if you changed something you need to redo the file association manually.

For a workaround see: https://github.com/robocorp/robotframework-lsp/issues/605
