### ISSUE TITLE
[Intellij] $Prompt$ macro not replaced when launching

### ISSUE THREAD

**Issue by DetachHead** [robocorp/robotframework-lsp#737]
**Describe the bug**
when adding a macro such as `$Prompt$` in a run config, it doesn't work

**To Reproduce**
1. create a new run config
2. click the `+` button on the right of the "Arguments" field to add a macro, eg. `$Prompt$`

**Expected behavior**
prompt appears when you click run

**Screenshots**
![image](https://user-images.githubusercontent.com/57028336/186303303-bbafaf79-d9d7-461c-af06-86ca40b4e89e.png)

**Versions:**
 - OS: windows 10
 - Robot Framework Version: 5.0.1
 - Robot Framework Language Server Version: 1.0
 - Client Version: pycharm 2022.2.1

**Comment by fabioz** [comment]
This is now available in the latest release (`1.1.0`).

**Comment by fabioz** [comment]
Note: it may take some time for it to appear in the marketplace, but you can already get it at: https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server/versions/stable/213916
