### ISSUE TITLE
How to pass configs via CLI ? 

### ISSUE THREAD

**Issue by albilu** [robocorp/robotframework-lsp#741]
Hello,
NB: This is more a question than a bug. Sorry if this is not the proper way to ask for question.

So i am using this LSP with not VSCode but another editor (Netbeans). 

I can pass a process started by  
`python ...robotframework-ls/src/robotframework_ls)/__main__.py` to my editor and most features works well exept the VScode specific ones

I understood configs described here https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/config.md 
 are passed to the Server via settings.json in VSCode

My question: is there a way to pass those configs via  CLI as i am not using VSCode?

Thanks

**Comment by fabioz** [comment]
> My question: is there a way to pass those configs via CLI as i am not using VSCode?

Those settings need to be passed using language server messages (most specifically https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeConfiguration)

So, those are expected to be sent from your own client as the way that each client implements this can be specific -- VSCode has multiple setting.json files for workspace/user and those are bundled and sent to the language server but there's nothing preventing specific clients from providing a different UI for that -- given that this is client specific, you need to consult with your own client implementation (Netbeans) to see how it passes such configurations to the language server.

**Comment by albilu** [comment]
Very clear. Thanks.
