### ISSUE TITLE
List of available keywords

### ISSUE THREAD

**Issue by ButterBetzi** [robocorp/robotframework-lsp#748]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A window (or similar) where all the availible keywords of the in the project available Libraries are listed.
There it could be scrolled through and maybe even searched for a needed keyword if you don't know how it's exactly called.

**Describe alternatives you've considered**
Only tried the RED IDE before switching to VS Code with this extension and this is the only feature I'm missing right now.

**Comment by fabioz** [comment]
In VSCode you can get this with `Ctrl+T` (if I understood correctly what you mean).

Also, note that while you're typing the code-completion proposals will actually provide proposals for all the keywords (even those that aren't in the context -- and it'll create the appropriate import if it's not in the scope).

**Comment by fabioz** [comment]
p.s.: feel free to reopen if that's not it.

**Comment by ButterBetzi** [comment]
holy smokes you are fast at answering :D
Thanks a lot, I didn't know that this functionality exists!
