### ISSUE TITLE
Robot Flow Visualizer Not Working On Test Cases With Setup and Teardowns

### ISSUE THREAD

**Issue by saurabh-c-rai** [robocorp/robotframework-lsp#756]
Type: <b>Bug</b>

Steps To Reproduce :-
1. Open a robot file containing test cases.
2. Select an Test Case having Setup section.
3. Select Robot Framework: Open Robot Flow Explorer.

Expected Results :-
1. All the keywords present inside the Test Case should be displayed in Flow Explorer.

Actual Results :-
1. The Keywords under [Setup] and [Teardown] section are marked as unknown.

Extension version: 1.1.3
VS Code version: Code 1.71.1 (Universal) (e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb, 2022-09-08T19:41:32.136Z)
OS version: Darwin x64 21.1.0
RF Version : 3.2

E.g.
Robot Code : -
<img width="835" alt="image" src="https://user-images.githubusercontent.com/47693029/190221438-981a14be-bc69-4792-a9b7-0cc6d24e0017.png">

Flow Explorer Output: -
<img width="470" alt="image" src="https://user-images.githubusercontent.com/47693029/190221680-aa7b989d-2678-4c09-b8ac-c82cd912a80a.png">

**Comment by fabioz** [comment]
This is now done.
