### ISSUE TITLE
vscode launch.json - cannot use listener

### ISSUE THREAD

**Issue by NikitaOstr** [robocorp/robotframework-lsp#759]
**Describe the bug**
I'm not sure if this is a bug but I cannot run defined configuration in launch.json with listener, error occurred. Perhaps misconfiguration.

**To Reproduce**
1. in launch.json under args section put listener as one of list value
2. run this configuration and got error:
[ ERROR ] option --listener d:/robot/external-tools/ccc not recognized

The same plugin in PyCharm works fine when defining the configurations

This is my json:
{
            "type": "robotframework-lsp",
            "name": "name",
            "request": "launch",
            "cwd": "D:/Robot/test-cases",
            "target": "D:/Robot/test-cases/aaa/bbb.robot",
            "terminal": "integrated",
            "args": ["--listener D:/Robot/external-tools/ccc","-v ENV:DevMds"]
}

**Versions:**
 - Windows 10
 - Robot Framework Version: 4.1.3
 - Robot Framework Language Server Version: 1.1.3
 - Client Version: VSCode 1.71.2

**Comment by fabioz** [comment]
The problem is that you're passing the listener with its args as a single argument when it should be 2 arguments.

i.e.: `"--listener D:/Robot/external-tools/ccc"` > `"--listener", "D:/Robot/external-tools/ccc"`

Likewise the `-v` also has the same problem (it should be `"-v", "ENV:DevMds"`).
