### ISSUE TITLE
Request: Hover delay setting in VS Code Extension

### ISSUE THREAD

**Issue by kalyncoose** [robocorp/robotframework-lsp#762]
**Is your feature request related to a problem? Please describe.**
Too often when I am coding in Robot with the VS Code extension, you move your cursor around and definition pop-up boxes keep appearing very fast and sometimes block your view of lines of code while typing. This can be frustrating since it is an amazing feature but I do not want to disable it just for this minor inconvenience.

**Describe the solution you'd like**
A new extension setting added to the VS Code plugin to adjust the time delay (in milliseconds) to the existing hover definition functionality so that users can adjust to their preference. I am unfamiliar with the VS Code extension API but I looked through this repository and found [hover.py](https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/src/robotframework_ls/impl/hover.py) although it is not apparent where a time delay can be added (maybe it is using VS Code's default hover delay?).

**Describe alternatives you've considered**
Disabling the hover definition functionality or plugin entirely will mitigate the issue while coding but is not a permanent solution.

**Comment by fabioz** [comment]
I believe that what you want is attainable by changing the `editor.hover.delay` setting.

If this doesn't fix your issue, please let me know to reopen the issue.

**Comment by kalyncoose** [comment]
Thanks @fabioz! That's perfect, exactly what I needed. I can't believe I was way overthinking it... long day at work haha
