### ISSUE TITLE
Peek Error Showing An Empty string Window

### ISSUE THREAD

**Issue by saurabh-c-rai** [robocorp/robotframework-lsp#774]
Type: <b>Bug</b>

In earlier versions, if the test fails the failure reason used to be logged  next to the Test Case Name on the Editor and we could also see the test run data for current as well as previous runs using the Peek Error option.
Now when a test case fails, an empty window opens with an error message. PFB the screenshot for the same.
![image](https://user-images.githubusercontent.com/47693029/194128864-6d8ae399-1a5a-49fc-9e3c-b3eb0533e3c0.png)

**Steps To Reproduce**
1. Run the below sample test.
2. Observe that the test fails and the window mentioned in the above snapshot opens.
3. Right click on the failure cross sign and select 'Peek Error' option.

**Expected Results**
- After test fails, error message / logs should be logged on the same window on the same line
- Peek Error option should display the test results of current as well as previous test runs.

<img width="250" alt="image" src="https://user-images.githubusercontent.com/47693029/194130030-7a9b7df2-63e1-4bd3-ac6c-b052193f54e0.png">

**Sample Code**
<img width="712" alt="image" src="https://user-images.githubusercontent.com/47693029/194130245-b4f44c83-5ef6-4a8d-bae6-7382059879fb.png">

Extension version: 1.2.0
VS Code version: Code 1.71.2 (Universal) (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin x64 21.1.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-514.el7.x86_64
RF Version : 3.2

**Comment by fabioz** [comment]
Thank you for the report (I've been able to reproduce this).

The problem is that on RobotFramework 3 we don't really have the source available (and thus it cannot attach the failure message to the actual location where the error happened -- and it's why it's showing `<string>` there).

I'll take a look at how to support RF 3 in this case...

**Comment by fabioz** [comment]
I've just fixed this.

Also, I'm pushing a pre-release (`1.2.1`) with the fix... Can you get it and see if it works properly for you (if all goes well I'll publish a stable bugfix version tomorrow).

**Comment by saurabh-c-rai** [comment]
Thanks for the quick fix @fabioz. This is now working as expected.
Verified in RF3.2
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/47693029/194285633-00ac6273-5ef4-4ed4-92f1-fe50944dfee2.png">
