### ISSUE TITLE
Unable to start tests from folder level

### ISSUE THREAD

**Issue by Veronit** [robocorp/robotframework-lsp#776]
**Describe the bug**
Right click on folder and selecting Robot Framework -> Run/Debug Tests/Tasks Suite doesn't do anything.
This works on plugin version 1.1.3, but not on more recent versions.

**To Reproduce**
1. Create a folder
2. Create at least one test file to the folder
3. Create at least one test in test files
4. Right click on folder and select Robot Framework -> Run/Debug Tests/Tasks Suite
-> Nothing happens

**Expected behavior**
Tests are executed

**Versions:**
 - Windows 10
 - Robot Framework Version: 5.0.1
 - Robot Framework Language Server Version: 1.3.0
 - Client Version: VSCode 1.71.1

**Comment by fabioz** [comment]
I'm sorry about that... I'll provide a fix shortly.

**Comment by fabioz** [comment]
I've just fixed this and a pre-release (`1.3.2`) will be available with the fix in a few minutes (if you could test the pre-release and let me know if it works for you that'd be nice...).

**Comment by Veronit** [comment]
Works on 1.3.2. Thank you very much! 👍
