### ISSUE TITLE
Error in Robocorp with vscode - Unable to activate Robocorp Code extension

### ISSUE THREAD

**Issue by alaeddineabouda** [robocorp/robotframework-lsp#780]
Hello,
I used to work with the 1.3 version of Robot Framework Language Server and the 0.38.0 version of Robocorp Code. I'm facing the follwing issue : 

- "Unable to activate Robocorp Code extension. Please see: Output > Robocorp Code for more details..”
- “"Robot Framework Language Server" conflicts with the following extension(s): "Robot Code" - please uninstall the conflicting extension(s).”
Would you mind providing me any advice to fix it ?
I have checked the documentation for sur language-server configuration but it dosen't work.
My environnent :
OS : Windows 10 x64
Pyhton version : 3.10.7
RF Version : 5.0.1
VsCode Verson : 1.69.1 (64bits)
Thanks by advance

**Comment by fabioz** [comment]
Have you tried uninstalling `Robot Code`?

i.e.: if you want to use `Robocorp Code` you should use `Robot Framework Language Server` as the extension to manage `Robot Framework` (the `Robot Code` extension isn't compatible with `Robocorp Code`).

**Comment by fabioz** [comment]
Closing as no additional info was given.
