### ISSUE TITLE
Custom Libraries Having Any Parameterized Parent Class Are Not Recognized

### ISSUE THREAD

**Issue by saurabh-c-rai** [robocorp/robotframework-lsp#789]
Type: <b>Bug</b>

Steps To Reproduce:-
1. Create a custom library named custom_class.py having two classes
- MyParentClass that needs atleast one parameter in its init method
- custom_class that inherits MyParentClass and also has init with one parameter that is passed to parent class object.
2. Create a robot file and import the custom_class library in the settings section and provide one variable as agrument.
3. Observe that the unresolved library error is displayed.

Expected Result:-
The library should be recognized since the variable required to form object of that library is already provided.

Actual Result:-
Unresolved Library error is displayed. 
<code>
Unresolved library: ../Custom/custom_class.py.
Error generating libspec:
It was not possible to statically resolve the following variables:
Follow-up error:
Test Library 'custom_class' expected 2 arguments, got 1.
Consider using default arguments in the ../Custom/custom_class.py constructor and
calling the "Robot Framework: Clear caches and restart" action or
adding "../Custom/custom_class.py" to the "robot.libraries.libdoc.needsArgs"
setting to pass the typed arguments when generating the libspec.robotframework
Checking for quick fixes...
</code>

PFB one sample project

> custom_class.py

<img width="707" alt="image" src="https://user-images.githubusercontent.com/47693029/197355058-e3454984-30ee-455b-a4ed-aa2db98cb0a0.png">

> MyRobot.robot
<img width="973" alt="image" src="https://user-images.githubusercontent.com/47693029/197355135-a0c66719-cfb1-477d-9d46-74d3f3b1dbaf.png">

Extension version: 1.3.5
VS Code version: Code 1.72.2 (Universal) (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:30.254Z)
OS version: Darwin x64 21.1.0
Modes:
Sandboxed: No
RF Version : 3.2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 4e1a7f74-58fc-4b9a-bed4-13f7d0786d16|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by fabioz** [comment]
@saurabh-c-rai please take a look at the `robot.libraries.libdoc.needsArgs` setting.

You may also want to read the related FAQ: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved.

I'm closing this issue since it should be possible to fix this configuring the language server with `robot.libraries.libdoc.needsArgs`, but if you still can't get it to work, please let me know.

**Comment by saurabh-c-rai** [comment]
Hi @fabioz ,
The steps provided doesn't work if the custom class is actually inheriting the required variables from the parent class.

Adding the library name to the setting <code>robot.libraries.libdoc.needsArgs</code> doesn't work.
Adding the required parameters while importing the custom library doesn't work.

The only option that does work is providing some default value to the __init__ method.
Can you please have a look again?

Thanks.

**Comment by fabioz** [comment]
If the subclass needs 2 arguments, besides setting `robot.libraries.libdoc.needsArgs` you also need to add the 2 arguments in:

i.e.: something as:

```
*** Settings ***
Library  custom_class.py    arg1    arg2
```
