### ISSUE TITLE
Base path for searching resources and libs

### ISSUE THREAD

**Issue by jonasdresch** [robocorp/robotframework-lsp#79]
There is a way to define a base path where resources and libs are located, to avoid entering the relative path?

e.g

**from:**

Resource          ../../../../testlibs/keywords/General.robot

**to:**

Resource          keywords/General.robot

These paths would be the same as the ones passed to robot in the --pythonpath option.

**Comment by avaissi** [comment]
An update for this:
It seems that the python libraries are respecting the PYTHONPATH set into env {}-configuration, but .robot or .resource files do not.
E.g.
If I define keywords in both:
/resources/keywords.robot
/resources/MyLib.py

Import them to my /tasks/worker.robot:
Library  MyLib
Resource  keywords.robot

Then keywords are found from MyLib, but not keywords.robot

**Comment by fabioz** [comment]
This is now fixed in https://github.com/robocorp/robotframework-lsp/commit/adeb801a4b4aba0daca902e1152ca3835019b051.

In the master version, the setting: `robot.pythonpath` can be used to set the base paths (note that when running it will automatically add it to the command line too).
