### ISSUE TITLE
Add an option to automaticaly insert the resource name before the keyword 

### ISSUE THREAD

**Issue by emerisier** [robocorp/robotframework-lsp#794]
As we had on RED IDE

![image](https://user-images.githubusercontent.com/75469846/200083644-e1c717b6-867b-40a3-a609-41dceb589f84.png)

**Comment by fabioz** [comment]
This is now already available in the 1.5.1 pre-release (through the `robot.completions.keywords.prefixImportName` configuration).

**Comment by emerisier** [comment]
Thank you for everything, we have started using it, at the moment we have not reported any problems.
