### ISSUE TITLE
Python file go to file feature

### ISSUE THREAD

**Issue by abeora** [robocorp/robotframework-lsp#795]
![issue](https://user-images.githubusercontent.com/110004513/200091535-4d7b26d0-c9b9-4dbd-b3c8-940108524542.jpg)

**Comment by fabioz** [comment]
Hello, I'm not sure I follow your issue. Can you elaborate a bit? What's the structure you have? Can you provide a sample project with the issue?

**Comment by fabioz** [comment]
Closing as no additional info was given and I don't really know what's wanted from this request...
