### ISSUE TITLE
Suggested robotframework-ls launch config misses mandatory guideline

### ISSUE THREAD

**Issue by eduvfalc** [robocorp/robotframework-lsp#798]
In the [robotframework-ls FAQ page](https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md) there's no explicit mention that the `launch.json` configuration should be named `Robot Framework: Launch Template`. I think that it would be interesting to say that the `name` attribute should not be changed, otherwise the configuration will not be applied as expected.

**Comment by fabioz** [comment]
Humm, actually, the FAQ does mention that:

https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-configure-the-launch-from-a-code-lensshortcut

I accept PRs to improve the wording though if you think it could be explained better...
