### ISSUE TITLE
VS Code "Test explorer" does not discover all robot files

### ISSUE THREAD

**Issue by DanielPenning** [robocorp/robotframework-lsp#817]
**Describe the bug**
VS Code has a "test explorer" that lists robot fiiles. It is very convenient to run all tests at once.
The bug is not all ".robot" files are found/listed. 
What rules govern the discovery? Can I manually add certain (sub) directories for discovery?

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 4.1
 - Robot Framework Language Server Version: v1.5.0
 - Client Version: VS Code 1.73.1

**Comment by fabioz** [comment]
Hi @DanielPenning thank you for the report.

It should actually find all the `.robot` files in the workspace (if it's not finding it to you this probably means that there's some bug in the code).

Is this something you can reproduce reliably? Can you provide some steps on how to reproduce that?

**Comment by fabioz** [comment]
@DanielPenning are you still interested in trying to track this?

**Comment by DanielPenning** [comment]
@fabioz Yes. I will try to reproduce within a minimal example (probably only after new years)

**Comment by DanielPenning** [comment]
I am not able to reliable reproduce it. I therefore guess the bug can be closed for now. If I stumble upon it again, I will open a new request.
