### ISSUE TITLE
Auto add `...`

### ISSUE THREAD

**Issue by Zoupers** [robocorp/robotframework-lsp#822]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

There are many times i want to write a multiline statement since there are many arguments or the argument itself is too long, so I am
wondered if we can add an onEnterRule for the rf-ls.

**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

in the middle of sentence, we press enter, and we auto insert ... in the next line with appropriate indention.
I spent some time on it, and work it out. But my re expression is far from a good one.

![image](https://user-images.githubusercontent.com/29817738/204430710-ea046b87-06f9-46c4-931e-2d26655db043.png)

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

Maybe we can add it from the server side? but maybe it's too complicated...

**Comment by fabioz** [comment]
I guess it's really hard to know when you want to add the `...` automatically.

Maybe we could have create a custom action that'd break and add the `...` which is bound to something as `Ctrl+Enter` (so, you'd have full control on whether you want it or not).

What do you think?

**Comment by Zoupers** [comment]
That's cool! But we might also add a simple rule(or might provide a way for user to define themselves, we just define a default), and let the user dicide whether to use or not? 

And the shortcut is always online. How about that?

**Comment by fabioz** [comment]
I think that doing it with `onEnterRules` may be hard as just a regexp is very limited in the way it can do the analysis.

I think that the rule should be that it adds a '...' when a new line is added inside a keyword call (or if at the end of some keyword call or documentation where there's '...' already).

After investigating a bit I think that using the onTypeFormatting (i.e.: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_onTypeFormatting) or maybe vscode.workspace.onDidChangeTextDocument(handleChange could be an option as we can then use use the parser to extract better information...

**Comment by Serhiy1** [comment]
This feature request feels like it should behave similarly to how most IDEs deal with multi-line comments. (using python as an example ) If a new line is pressed right at the end, `#` is not automatically inserted. If there are characters after the newline location, `#` is automatically added.

**Comment by fabioz** [comment]
I've implemented this and did a pre-release (`Robot Framework Language Server 1.7.4').

It'd be nice to have more testing on that pre-release to know whether it works as expected ;)
