### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by por84** [robocorp/robotframework-lsp#823]
**Describe the bug**
Following the setup from here:
https://robocorp.com/docs/developer-tools/other-editors/pycharm
and I get to:
`rcc environment new conda.yaml`

But i get the following error:

![image](https://user-images.githubusercontent.com/40896176/205111062-2bc9b1a8-e32c-4e17-af05-1ecda3857b6b.png)

**To Reproduce**
Go to step: `rcc environment new conda.yaml`
in this setup page:
https://robocorp.com/docs/developer-tools/other-editors/pycharm

**Expected behavior**
Expected to see what is in the screenshot on the instructions page:

![image](https://user-images.githubusercontent.com/40896176/205111593-e37e01bf-f6eb-4540-8075-713eb1e4e793.png)

**Screenshots**
Screenshots added above

**Versions:**
 - OS: Ubuntu 20.04
 - Robot Framework Version: 3.1.2
 - Robot Framework Language Server Version: 1.5 (latest only installed today
 - Client Version: PyCharm 2022.3

**Comment by fabioz** [comment]
Sorry for the delay in getting back to you.

The `rcc environment` command was really removed.

I believe that the command you want in the latest versions of `rcc` is:

`rcc holotree variables`

Please take a look at https://robocorp.com/docs/rcc/overview for more information and usage.
