### ISSUE TITLE
how to set these all path

### ISSUE THREAD

**Issue by venkateshkankapurkar** [robocorp/robotframework-lsp#832]
**Describe the bug**

**To Reproduce**
1. Open file with contents '....'
2. See code analysis errors '....'

**Expected behavior**

**Screenshots**

**Versions:**
 - OS: [e.g. Windows 10]
 - Robot Framework Version: [e.g. 3.2]
 - Robot Framework Language Server Version: [e.g. 0.2.3]
 - Client Version: [e.g.: VSCode 1.46 or PyCharm 2020.1.2]

**Comment by fabioz** [comment]
You seem to have opened another issue already, so, I'm closing this one.
