### ISSUE TITLE
Error when downloading  Robot Framework Language Server/ Robocorp Code

### ISSUE THREAD

**Issue by vdavis345** [robocorp/robotframework-lsp#842]
**Describe the bug**
After installing the robocorp extensions into VSCode, I enable windows longpaths manually and once I come back to VSCode it still shoots out the error below.

I'm using a remote desktop connection as an admin

**To Reproduce**
1. download Robot Freamkework Language Server/Robocorp Code

**Expected behavior**
Should download with no problem.

**Screenshots**

**Versions:**
 -  Windows 10
 - Robocorp Code Version: [v0.41.0]
 - Robot Framework Version: [6.0.1]
 - Robot Framework Language Server Version: [v1.7.0]
 - Client Version: [e.g.: VSCode 1.74 and PyCharm 2022.3]

Full error: 
Activating Robocorp Code extension.
Waiting for Robocorp Code (python) language server to finish activating...
Executing: c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\bin\rcc.exe configure longpaths
Error executing: c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\bin\rcc.exe configure longpaths
Error code: undefined
Error: error
Stderr: The full path of C:\Users\davisvin\AppData\Local\robocorp\stump\verylongpath1\verylongpath2\verylongpath3\verylongpath4\verylongpath5\verylongpath6\verylongpath7\verylongpath8\verylongpath9\verylongpath10\verylongpath11\verylongpath12\verylongpath13\verylongpath14\verylongpath15\verylongpath16\verylongpath17\verylongpath18\verylongpath19\verylongpath20\verylongpath21\verylongpath22\verylongpath23\verylongpath24 is too long.
WARNING!  Long path support failed. Reason: exit status 1.
WARNING!  See https://robocorp.com/docs/product-manuals/robocorp-lab/troubleshooting#windows-has-to-have-long-filenames-support-on for more details.
Long paths do not work!

There was some error with rcc configure longpaths.
Windows long paths support NOT enabled.
RCC stdout:
<not collected>
RCC stderr:
<not collected>
ROBOCORP_HOME: C:\Users\davisvin\AppData\Local\robocorp
Error executing: c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\bin\rcc.exe feedback metric -t vscode -n vscode.code.error -v RCC_CONFIGURE_LONGPATHS
Error code: undefined
Error: error
Stderr: Tracking is disabled. Quitting.

Executing: c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\bin\rcc.exe configure longpaths
Error executing: c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\bin\rcc.exe configure longpaths
Error code: undefined
Error: error
Stderr: The full path of C:\Users\davisvin\AppData\Local\robocorp\stump\verylongpath1\verylongpath2\verylongpath3\verylongpath4\verylongpath5\verylongpath6\verylongpath7\verylongpath8\verylongpath9\verylongpath10\verylongpath11\verylongpath12\verylongpath13\verylongpath14\verylongpath15\verylongpath16\verylongpath17\verylongpath18\verylongpath19\verylongpath20\verylongpath21\verylongpath22\verylongpath23\verylongpath24 is too long.
WARNING!  Long path support failed. Reason: exit status 1.
WARNING!  See https://robocorp.com/docs/product-manuals/robocorp-lab/troubleshooting#windows-has-to-have-long-filenames-support-on for more details.
Long paths do not work!

There was some error with rcc configure longpaths.
Windows long paths support NOT enabled.
RCC stdout:
<not collected>
RCC stderr:
<not collected>
Extension will not be activated because Windows long paths support not enabled.
Robocorp Code extension disabled. Reason: Unable to get python to launch language server.
Unable to activate Robocorp Code extension because python executable from RCC environment was not provided.
 -- Most common reason is that the environment couldn't be created due to network connectivity issues.
 -- Please fix the error and restart VSCode.
Error getting Python
    Unable to get language server python info.
    Error: Unable to get language server python info.
    	at c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\vscode-client\out\extension.js:92:23
    	at Generator.next (<anonymous>)
    	at fulfilled (c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\vscode-client\out\extension.js:23:58)
    	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[Error - 8:49:01 AM] Starting client failed
Error: Unable to get language server python info.
	at c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\vscode-client\out\extension.js:92:23
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\vscode-client\out\extension.js:23:58)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
Error initializing Robocorp code.
    Unable to get language server python info.
    Error: Unable to get language server python info.
    	at c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\vscode-client\out\extension.js:92:23
    	at Generator.next (<anonymous>)
    	at fulfilled (c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\vscode-client\out\extension.js:23:58)
    	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
Robocorp Code initialization finished. Took: 413.8s
Error executing: c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\bin\rcc.exe feedback metric -t vscode -n vscode.code.error -v INIT_NO_LONGPATH_SUPPORT
Error code: undefined
Error: error
Stderr: Tracking is disabled. Quitting.

Error executing: c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\bin\rcc.exe feedback metric -t vscode -n vscode.code.error -v ERROR_INITIALIZING_ROBOCORP_CODE_LANG_SERVER
Error code: undefined
Error: error
Stderr: Tracking is disabled. Quitting.

Error executing: c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\bin\rcc.exe feedback metric -t vscode -n vscode.code.error -v INIT_PYTHON_ERR
Error code: undefined
Error: error
Stderr: Tracking is disabled. Quitting.

Error executing: c:\Users\davisvin\.vscode\extensions\robocorp.robocorp-code-0.41.0\bin\rcc.exe feedback metric -t vscode -n vscode.code.error -v INIT_NO_PYTHON_LANGUAGE_SERVER
Error code: undefined
Error: error
Stderr: Tracking is disabled. Quitting.

**Comment by fabioz** [comment]
The issue here is that long paths need to be enabled on Windows for Robocorp Code to start.

There are instructions on how to do it at: https://robocorp.com/docs/troubleshooting/windows-long-path

The next version (probably 0.42.0) will provide a way to proceed even without enabling long paths support in windows (although it's not, recommended, but, if users don't have administrative rights to change the long paths flag Robocorp Code can't really be used in 0.41.0, so, 0.42.0 will make it more flexible -- albeit users risk not being able to create or use some environment if it crosses the long path threshold).
