### ISSUE TITLE
Provide better error message if user tries to launch without workspace folder open

### ISSUE THREAD

**Issue by Carmen-Rietdijk-Valori** [robocorp/robotframework-lsp#845]
**Describe the bug**
Dear community,

I am new to this site and to Robot Framework. I have built a stack for test automation using the Robot Framework Language Server on Visual Studio Code.

Everything seems to be set up properly, I can run a very simple test through the console. However, when I use the code lens button ‘run’ to run the same test I receive the error message ‘Unable to obtain test item from: ’. This also happens for the other code lens buttons: Debug, Run Suite, Debug Suite.

I can not find what this error means anywhere, and therefore I have no idea how to fix it. 

I posted this issue two weeks ago at https://forum.robocorp.com/t/rf-ls-on-vsc-code-lens-error-unable-to-obtain-test-item-from/2204, hoping someone in the community had faced this error before. This did not seem to be the case, and someone replied suggesting I'd post the issue here.

Thanks for any suggestions and help!
Carmen

**To Reproduce**
1. Set up RF LS in VSC
2. . Write a simple test script
3. Run the test script from the console
4. Run the test script from the Code Lens

**Expected behavior**
Step 4 & 5: the code is run, the test is performed

**Actual behavior**
Step 4: the code is run, the test is performed
Step 5: an error is shown ‘Unable to obtain test item from: ’

**Screenshots**
Using the Code Lens Run button (gives error)
![image](https://user-images.githubusercontent.com/120089916/208123077-4fe60d26-6641-41d5-b278-de4defd54da6.png)
Using PS via the console (no error)
![image](https://user-images.githubusercontent.com/120089916/208123174-e36fc0a3-3d75-469b-9ee1-69d4b8b926a8.png)

**Versions:**
 - OS: Windows 10 Pro
 - Robot Framework Version: 5.0.1
 - Robot Framework Language Server Version: 1.7.3
 - Client Version: VSCode 1.74.1

**Logs**
I tried to create logs for the error, but no logs are created because the error prevents anything from happening.

**Comment by fabioz** [comment]
Thanks for the screenshot, it's helpful.

The problem is that the language server right now does not support doing a launch unless it's from a file in the workspace.

i.e.: if you open the folder which contains those `.robot` files, it should work.

I guess we could support launches even if not folder is opened (renaming issue accordingly).

**Comment by Carmen-Rietdijk-Valori** [comment]
Hi Fabioz,

Thank you for your feedback & updating the issue. 
I tried your solution and you are right, opening the folder in VSC fixes the issue. Thank you so much!

Have a great week,
Carmen
