### ISSUE TITLE
Detect and warn of 'WebView2 not found' before launching Inspector.

### ISSUE THREAD

**Issue by kariharju** [robocorp/robotframework-lsp#850]
**Is your feature request related to a problem? Please describe.**
Currently if users start to create locators via and they do not have WebView2 installed the launched inspector ends-up in a blank window. A warning pointing to: https://robocorp.com/docs/faq/webview would help them directly

**Describe the solution you'd like**
Show a docs link to guide to user to setup WebView2 in case they do not have it before allowing the inspector to trigger.

The tricky part is to find a reliable detection method. There are several registry based solutions proposed in the stack pverflows of the world like:
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Microsoft EdgeWebView > "DisplayName"="Microsoft Edge WebView2 Runtime"`
..but I have not found any official way.

**Comment by fabioz** [comment]
Done in: https://github.com/robocorp/robotframework-lsp/commit/b642c87854d246605b202e0f3c3df0772a718ae5
