### ISSUE TITLE
Missing autocompletion for `BREAK`, `CONTINUE` and `RETURN` statements

### ISSUE THREAD

**Issue by JaPyR** [robocorp/robotframework-lsp#856]
**Describe the bug**
It seems that autocompletion does not suggest `BREAK`, `CONTINUE` and `RETURN` statements whilst syntax highlight is working for them.

https://user-images.githubusercontent.com/7773301/210795943-369e852a-b145-4965-9f86-9bbb277b37c9.png
https://user-images.githubusercontent.com/7773301/210795972-094fb02b-1368-4bbd-8fa9-5e8a66da7d0f.png
https://user-images.githubusercontent.com/7773301/210795991-91a384f2-3ccf-4326-87af-d18a65279b93.png

**Versions:**
 - OS: Windows 11
 - Robot Framework Version: 5.0.1
 - Robot Framework Language Server Version: 1.7.3
 - Client Version: VSCode 1.74.2

**Comment by fabioz** [comment]
Good catch... I'll add those shortly.
