### ISSUE TITLE
Support unicode characters properly

### ISSUE THREAD

**Issue by DetachHead** [robocorp/robotframework-lsp#862]
**Describe the bug**
some emojis are rendered incorrectly as `��`, and seem to cause the syntax highlighting and `formatOnSave` functionality to break

**To Reproduce**
1. enable the following settings in `.vscode/settings.json`:
    ```json
    {
      "robot.codeFormatter": "robotidy",
      "editor.formatOnSave": true
    }
    ```
2. create a `.robot` file with the following code
    ```robot
    *** Test Cases ***
    Unicode
        [Documentation]    creates variables with unicode strings
        ${mystring} =    Convert To String    Foo 😀 🦘
        @{mylist} =    Create List    😀    😃
        ${mydict} =    Create Dictionary    grin=😀    kangaroo=🦘    egg=🥚
    ```
3. `ctrl+s` and observe the incorrect formatting changes (look at the last line):
    ```robot
    *** Test Cases ***
    Unicode
        [Documentation]    creates variables with unicode strings
        ${mystring} =    Convert To String    Foo 😀 🦘
        @{mylist} =    Create List    😀    😃
        ${mydict} =    Create Dictionary    grin=😀    kangaroo=🦘    egg
    =🥚
    ```
**Expected behavior**
correct syntax highlighting and no formatting changes

**Screenshots**
incorrect syntax highlighting (look at `egg=🥚`) and broken `��` characters:
![image](https://user-images.githubusercontent.com/57028336/213092644-d5d87346-53e5-4d6d-80c5-d5d3ed312659.png)

note: this only seems to be an issue in robot files, they are displayed correctly in other filetypes:
![image](https://user-images.githubusercontent.com/57028336/213095016-a8a42467-e63d-4641-b713-965c5b229c71.png)

**Versions:**
 - OS: windows 10
 - Robot Framework Version: 6.0.2
 - Robot Framework Language Server Version: 1.7.3
 - Client Version: vscode 1.74.3

**Comment by fabioz** [comment]
I did an initial investigation on what's needed to support this.

Internally VSCode has an approach where positions are specified by code-units where a code-unit is based by what fits in a `utf-16` char, so, what needs to be done is that when receiving information from vscode or passing information to it the positions need to be updated based on that.
