### ISSUE TITLE
Unresolved library, error generating libspec, ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by Dmitrii-Repin** [robocorp/robotframework-lsp#891]
**Describe the bug**
When I try to use your module in the PyCharm it shows an error for one of my custom libraries complaining that the module named 'tkinter' is not found. But I don't use tkinter module anywhere, of course it cannot find it.
`Unresolved library: MyCustomLibrary. Error generating libspec: Importing test library 'MyCustomLibrary' failed: ModuleNotFoundError: No module named 'tkinter' Consider adding the needed paths to the "robot.pythonpath" setting and calling the "Robot Framework: Clear caches and restart" action.`
This library is a static Robot Framework library that don't need initialization on import, not taking any arguments and contains a bunch of methods that used as keywords. We are using it for a few years already and Robot Framework never had any troubles with importing it.

**To Reproduce**
Not sure what steps I can list there, as I cannot share the library in question and have no idea what part of it cause the issue.
Steps that work for me:
1. Open .robot file that has MyCustomLibrary imported
2. Wait for indexing to end

**Expected behavior**
The custom library is imported without errors, and the plugin recognizes the keywords from it

**Screenshots**

**Versions:**
 - OS: Windows 11
 - Robot Framework Version: 3.2
 - Robot Framework Language Server Version: 1.9.0
 - Client Version: PyCharm 2022.3.2 (Community Edition)

**Logs**
[idea.log](https://github.com/robocorp/robotframework-lsp/files/10767279/idea.log)
[.intellij-rf-ls-2023-02-17-21588.log](https://github.com/robocorp/robotframework-lsp/files/10767286/intellij-rf-ls-2023-02-17-21588.log)

**Comment by chemstar** [comment]
you should check if your python has tkinter module installed. just rerun python setup and check the optional features.

**Comment by Dmitrii-Repin** [comment]
My python does not have it installed, as I don't need that module. If it is a hard requirement for the plugin it should be mentioned somewhere, as far as I know it is not something that is installed by default when someone install python.

**Comment by Dmitrii-Repin** [comment]
> My python does not have it installed, as I don't need that module. If it is a hard requirement for the plugin it should be mentioned somewhere, as far as I know it is not something that is installed by default when someone install python.

I was wrong. Tkinter module is included into python standard packages and I do have it installed. I checked python I have installed as main python of my Windows, I checked python I can get from PyCharm "Terminal" and python from PyCharm "Python Console". Both terminal and python console use the same one that set as my project intepreter and in both of them I was able to run `import tkinter` without any issues. I still cannot figure out why Robot Framework Language Server plugin don't have access to it. But as I am not a plugin developer I am struggling with debugging it. Any thoughts on what I can try and what I can check?

**Comment by Dmitrii-Repin** [comment]
And it happens that the wrong version of python without tkinter was used by the plugin. I manage to find it by going all python executables in my PC and try to import tkinter in all of them. After I found the one that was missing the import and change it to the more complete one, the error goes away.
