### ISSUE TITLE
Issue with geckodriver version

### ISSUE THREAD

**Issue by azasa** [robocorp/robotframework-lsp#895]
Type: <b>Bug</b>

I'm using different drivers to open a webpage.
When using the firefox one geckodriver.exe latest version delivered 8 february 2023 I'm receiving the following error:
FAIL INSIDE] OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher

BUT 

Using the very same driver outside the robotframework inside VS Code, for example from a terminal : >robot <file>.robot
it works and open the webpage as expected.

So I suppose this is an internal VS Code issue as per the fact that I have o report the PATH with \\ instead of a single one and I have to put the webdriver name.exe at the end of the path instead of the single PATH and the name of the browser like robot wants

Extension version: 1.9.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (15.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by fabioz** [comment]
It's possible that the environment variables are different, but this is something you have to control yourself (the language server gets the variables based on how you launch it and the variables you configure).

So, there's nothing much which can be done at the language server to fix this.

This is a configuration error, so, you need to configure the env as needed for things to work (you can do this in custom launches using the `env` or by configuring `robot.python.executable` along with `robot.python.env`).

Sometimes launching VSCode from the terminal helps as it'll then start with the environment variables you have configured in the terminal...
