### ISSUE TITLE
Configure Robotidy with ignore_git_dir option

### ISSUE THREAD

**Issue by bhirsz** [robocorp/robotframework-lsp#910]
One of our users has asked us to implement ``--ignore_git_dir`` option in the Robotidy. It does change the way we are looking for the configuration file - basically Robotidy searches for ``pyproject.toml`` file in common parent directory of all sources, and it's going up to parent directories until it reaches beginning of path or finds ``.git`` directory.

For example if you have C:/project/repo_x/nested/file.robot and tell Robotidy to format ``file.robot`` it will go up until it reaches ``repo_x`` (since it contains ``.git`` directory like any other git repo).

Some users have different setup - for example multiple repo in one, sub-repo etc and prefer Robotidy to keep searching for config file even if ``.git`` dir is found. That's why I will be adding ``--ignore_git_dir`` option in the 4.1 release. But since this option need to be supplied to Robotidy before reading the configuration file (so it can find it), it needs to be passed from cli or api. 

That's why I need a way to pass parameter from lsp configuration (from your file?) to Robotidy, ie we can do it there: https://github.com/robocorp/robotframework-lsp/blob/973ab1b2fc40ebaa7dcc90018f90eaa249b5c29c/robocorp-python-ls-core/src/robocorp_ls_core/robotidy_wrapper.py (transform_model accept kwargs that can be used to set configuration).

I am willing to create the PR, I just need to figure out how you're parsing the configuration in meantime. There will be no problem will backward compatiblity (we're passing this option as kwarg, so older Robotidy that doesn't support this option will simply ignore it).

**Comment by fabioz** [comment]
This is now in master (and in a few minutes in a `1.10.2` pre-release).
