### ISSUE TITLE
not working with v 2023.1

### ISSUE THREAD

**Issue by LVNDLORD** [robocorp/robotframework-lsp#912]
Ok, the release is now done.

It may take some time to appear in the marketplace. In the meanwhile it's possible to get it at:

https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server/versions/stable/206705

_Originally posted by @fabioz in https://github.com/robocorp/robotframework-lsp/issues/718#issuecomment-1209717894_

**Comment by Zeckie** [comment]
Just to clarify, version 1.9.0 ( the latest version currently available at https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server/versions) gives this warning: and refuses to install on PyCharm 2023.1:

> Not compatible with the version of your running IDE (PyCharm 2023.1)

![error from installing plugin](https://user-images.githubusercontent.com/49095968/231050512-03bc8e6b-43a0-47cd-869d-6a8ebae7a8df.png)

**Comment by NikosKoul** [comment]
Plugin 'Robot Framework Language Server' (version '1.10.0') is not compatible with the current version of the IDE, because it requires build 230.* or older but the current build is PC-231.8109.197

**Comment by Zeckie** [comment]
Version 1.10.1 is now available, and supports PyCharm up to 2023.1.2 (rc) - https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server/versions

**Comment by fabioz** [comment]
Yeap, closing as this should be working with the latest version now.
