### ISSUE TITLE
Language Server Unable to Load Libraries

### ISSUE THREAD

**Issue by restagner** [robocorp/robotframework-lsp#913]
**Describe the bug**
The language server is unable to load libraries like

- SeleniumLibrary
- RequestsLibrary, and
- an internal project library

The error reported is 
```
Unresolved library: SeleniumLibrary.  Error generating libspec: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError
```

However, the language server accurately loads built-in libraries like

- OperatingSystem

**To Reproduce**
1.  from terminal, execute `poetry shell` to activate the virtual environment
2. use either the `nvim` (NeoVim) or `lvim` (LunarVim) command to open the editor
3. from within the editor, navigate to the file containing the SeleniumLibrary statement

**Expected behavior**
The `Library` statement should not show an error.  For example, 

```
Library             SeleniumLibrary
```

**Versions:**
 - OS: MacOS 10.15.7 (Catalina)
 - Robot Framework Version:  5.0.1
 - Robot Framework Language Server Version: [e.g. 0.2.3]
 - Client Version: NeoVim or LunarVim

**Logs**
[lsp.log](https://github.com/robocorp/robotframework-lsp/files/11250227/lsp.log)

**Comment by fabioz** [comment]
@restagner I see many errors related to libraries not found in the logs. This probably means you're using the wrong interpreter (one which doesn't have Selenium installed).

If you replace `\\n` to `\n` in the error messages the error message I get is below... do you actually have selenium installed at: `/Users/stagr005/.local/share/nvim/mason/packages/robotframework-lsp/venv/bin/python`? If you run that command line manually (see the `CalledProcessError` below for the command line), does it work?

```
Error creating libspec: SeleniumLibrary.
Return code: 252
Output:
Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  /Users/stagr005/workspace/esd-acceptance-tests
  /Users/stagr005/.pyenv/versions/3.11.1/lib/python311.zip
  /Users/stagr005/.pyenv/versions/3.11.1/lib/python3.11
  /Users/stagr005/.pyenv/versions/3.11.1/lib/python3.11/lib-dynload
  /Users/stagr005/.local/share/nvim/mason/packages/robotframework-lsp/venv/lib/python3.11/site-packages

Try --help for usage information.


Traceback (most recent call last):
  File \"/Users/stagr005/.local/share/nvim/mason/packages/robotframework-lsp/venv/lib/python3.11/site-packages/robotframework_ls/impl/libspec_manager.py\", line 1053, in _cached_create_libspec
    self._subprocess_check_output(
  File \"/Users/stagr005/.local/share/nvim/mason/packages/robotframework-lsp/venv/lib/python3.11/site-packages/robotframework_ls/impl/libspec_manager.py\", line 935, in _subprocess_check_output
    return subprocess.check_output(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/Users/stagr005/.pyenv/versions/3.11.1/lib/python3.11/subprocess.py\", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/Users/stagr005/.pyenv/versions/3.11.1/lib/python3.11/subprocess.py\", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/stagr005/.local/share/nvim/mason/packages/robotframework-lsp/venv/bin/python', '-m', 'robot.libdoc', '--format', 'XML', '--specdocformat', 'RAW', 'SeleniumLibrary', '/Users/stagr005/.robotframework-ls/specs/v2/5812b2c2_6.0.2/user/SeleniumLibrary.libspec']' returned non-zero exit status 252.
```

**Comment by restagner** [comment]
@fabioz ,

[poetry](https://python-poetry.org/) maintains it's virtual environment under `/Users/stagr005/Library/Caches/pypoetry/virtualenvs/ucapesd-vy0uFhxc-py3.11`

And, within this environment, I see that Selenium is installed.
```
$ ls /Users/stagr005/Library/Caches/pypoetry/virtualenvs/ucapesd-vy0uFhxc-py3.11/lib/python3.11/site-packages/selenium*
/Users/stagr005/Library/Caches/pypoetry/virtualenvs/ucapesd-vy0uFhxc-py3.11/lib/python3.11/site-packages/selenium:
__init__.py	__pycache__	common		py.typed	types.py	webdriver

/Users/stagr005/Library/Caches/pypoetry/virtualenvs/ucapesd-vy0uFhxc-py3.11/lib/python3.11/site-packages/selenium-4.8.3.dist-info:
INSTALLER	METADATA	RECORD		REQUESTED	WHEEL
```

Yet, when I look at the PYTHONPATH, it's empty
```
(ucapesd-py3.11) bash-5.0$ echo $PYTHONPATH

```

I should note, that opening this project in PyCharm works just fine.  It's just not working when I use `NeoVim`, which is what I'd like it to do

Any further suggestion on how to get NeoVim to recognize the site-packages under poetry?

**Comment by restagner** [comment]
@fabioz ,

Just wanted to follow-up with you on this.  Any further thoughts on my `NeoVim` issue?

**Comment by restagner** [comment]
@fabioz 

I ran the command you suggested, and here is what's returned

```
$ /Users/stagr005/.local/share/nvim/mason/packages/robotframework-lsp/venv/bin/python -m robot.libdoc --format XML --specdocformat RAW SeleniumLibrary /Users/stagr005/.robotframework-ls/specs/v2/5812b2c2_6.0.2/user/SeleniumLibrary.libspec
Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  /Users/stagr005
  /Users/stagr005/.pyenv/versions/3.11.1/lib/python311.zip
  /Users/stagr005/.pyenv/versions/3.11.1/lib/python3.11
  /Users/stagr005/.pyenv/versions/3.11.1/lib/python3.11/lib-dynload
  /Users/stagr005/.local/share/nvim/mason/packages/robotframework-lsp/venv/lib/python3.11/site-packages
```

**Comment by fabioz** [comment]
OK, so, it seems expected that it'll fail. 

Where is the python which has `selenium` actually installed? You should instruct nvim to use that same python to launch the language server...

Is this the same interpreter you get if you run:  `poetry run python -c "import sys;print(sys.executable)"`?

**Comment by restagner** [comment]
When I run `poetry run python -c "import sys;print(sys.executable)"`

I see

```
$ poetry run python -c "import sys;print(sys.executable)"
/Users/stagr005/Library/Caches/pypoetry/virtualenvs/ucapesd-vy0uFhxc-py3.11/bin/python
```

which is where that project's virtual environment exists.  If I list the contents of the site-packages under that virtual environment I see Selenium

How do I setup the language sever to use this location for the project's site-packages?  That's the missing piece I need to resolve (I guess)

```
 $ ls /Users/stagr005/Library/Caches/pypoetry/virtualenvs/ucapesd-vy0uFhxc-py3.11/lib/python3.11/site-packages/selenium*
/Users/stagr005/Library/Caches/pypoetry/virtualenvs/ucapesd-vy0uFhxc-py3.11/lib/python3.11/site-packages/selenium:
total 16
-rw-r--r--   1 stagr005  SWNA\Domain Users   811 Mar 30 07:39 __init__.py
drwxr-xr-x   4 stagr005  SWNA\Domain Users   128 Mar 30 07:39 __pycache__/
drwxr-xr-x   5 stagr005  SWNA\Domain Users   160 Mar 30 07:39 common/
-rw-r--r--   1 stagr005  SWNA\Domain Users     0 Mar 30 07:39 py.typed
-rw-r--r--   1 stagr005  SWNA\Domain Users  1010 Mar 30 07:39 types.py
drwxr-xr-x  15 stagr005  SWNA\Domain Users   480 Mar 30 07:39 webdriver/

/Users/stagr005/Library/Caches/pypoetry/virtualenvs/ucapesd-vy0uFhxc-py3.11/lib/python3.11/site-packages/selenium-4.8.3.dist-info:
total 144
-rw-r--r--  1 stagr005  SWNA\Domain Users      4 Mar 30 07:39 INSTALLER
-rw-r--r--  1 stagr005  SWNA\Domain Users   7160 Mar 30 07:39 METADATA
-rw-r--r--  1 stagr005  SWNA\Domain Users  54696 Mar 30 07:39 RECORD
-rw-r--r--  1 stagr005  SWNA\Domain Users      0 Mar 30 07:39 REQUESTED
-rw-r--r--  1 stagr005  SWNA\Domain Users     91 Mar 30 07:39 WHEEL
```

**Comment by fabioz** [comment]
Well, it's nvim which launches the language server (and I don't really know how it does the actual launching as that's client specific, so, you should take a look into the nvim language server integration to know how to customize it).

**Comment by fabioz** [comment]
i.e.: the language server must be launched with the interpreter at: `/Users/stagr005/Library/Caches/pypoetry/virtualenvs/ucapesd-vy0uFhxc-py3.11/bin/python`

**Comment by restagner** [comment]
ok. thanks. I'm guessing there's probably some way of configuring the language server within nvim

**Comment by restagner** [comment]
@fabioz ,

I realize this issue is closed, but I wanted to follow up with you and say _thanks_.  You're suggestion on how the language server must be launched helped.  Here is what I ended up doing for `LunarVim`

```lua
-- Robot Framework LSP OVERRIDE
local virtualenv = os.getenv("VIRTUAL_ENV")
local opts
if virtualenv then
    opts = {
        settings = {
            robot = {
                python = {
                    executable = virtualenv .. "/bin/python"
                }
            }
        }
    }
end
require("lvim.lsp.manager").setup("robotframework_ls", opts)
```

which worked, as expected!!!
