### ISSUE TITLE
fsnotify consuming 100% of CPU on Visual Studio Code

### ISSUE THREAD

**Issue by oriolarcas** [robocorp/robotframework-lsp#915]
A Python process of the language server starts consuming 100% of CPU on several cores.

**To Reproduce**
1. Enable the plugin in Visual Studio Code.
2. Open a Robot file.

<img width="300" alt="Screenshot 2023-04-19 at 15 12 45" src="https://user-images.githubusercontent.com/5081071/233087250-faf7f25f-5922-4669-b4b8-c72418bcbc4f.png">

**Expected behavior**
The language server parses the file and may consume some CPU for a while, but then it reaches a point where it is mostly idle.

**Versions:**
 - OS: macOS Ventura 13.2.1
 - Robot Framework Version: 6.0.1
 - Robot Framework Language Server Version: 1.10.0
 - Client Version: VSCode 1.77.3

**Logs**
I took some profiles of the Python processes during 30 seconds using [py-spy](https://github.com/benfred/py-spy). The profile sampling was made well after the process was started. The call trace clearly shows that most of the CPU is dedicated to fsnotify:

![profile](https://user-images.githubusercontent.com/5081071/233064375-b43c52ab-2162-40ac-9cca-70daecdf7676.svg)
![profile2](https://user-images.githubusercontent.com/5081071/233064381-e1b0e5df-5934-4bbd-8e5f-e44302185bb0.svg)

The command lines of the Python processes are:

```
/Users/username/.vscode/extensions/robocorp.robotframework-lsp-1.10.0/src/robotframework_ls/vendored/robocorp_ls_core/remote_fs_observer__main__.py -v
/Users/username/.vscode/extensions/robocorp.robotframework-lsp-1.10.0/src/robotframework_ls/server_api/server__main__.py -v --index-workspace --collect-tests --remote-fs-observer-port=55471
```

When inspecting the open files, it looks like it is scanning the whole hard drive. These are some of the open files as reported by Activity Monitor for the Python processes:

```
/System
/System/Volumes
/System/Volumes/Data
/Volumes
/Applications
/Applications/Microsoft Outlook.app
/Applications/Microsoft Outlook.app/Contents
/Applications/Microsoft Outlook.app/Contents/Frameworks
/Applications/Microsoft Outlook.app/Contents/Frameworks/XPG.framework
/Users
/Users/username
/Users/username/Library
/Users/username/Library/Containers
/Users/username/Library/Containers/com.apple.iWork.Keynote
/Users/username/Library/Containers/com.apple.iWork.Keynote
/Users/username/Music
/System
/System/Volumes
/System/Volumes/Data
/usr
/usr/local
/us/local/Cellar/gdk-pixbuf/2.42.10
/us/local/Cellar/gdk-pixbuf/2.42.10/share
/us/local/Cellar/gdk-pixbuf/2.42.10/share/locale
```

I noticed the "remote-fs-observer" bit. In case it helps, I have two partitions in my disk: the main macOS volume, and another volume mounted as a directory. The Robot files are in the second volume, the files that it is scanning are in the first one.

Let me know further debugging is needed.

**Comment by oriolarcas** [comment]
Looks very similar to #350.

**Comment by LagHyde** [comment]
On Friday, my machine got the latest update for Visual Studio Code and afterwards I was facing a similar performance issue (high cpu usage all the time, not able to navigate to keywords). I needed to turn off the language server plugin to be able to do any work at all. Updating RobotFramework Version from 6.0.1 to 6.0.2 resolved the issue for me.

**Comment by oriolarcas** [comment]
Thanks for the feedback @LagHyde. I updated RobotFramework to 6.0.2 but I am having the same issue: Robot starts scanning the whole macOS disk.

**Comment by oriolarcas** [comment]
Found the issue: if I specify PYTHON paths in settings like

```json
    "robot.pythonpath": [
        "./",
        "./libs",
        "./protobuf"
    ]
```

Running tests works, but the initial "." is lost before it arrives to the filesystem watchdog, so it ends trying to scan "/", "/libs", "/protobuf"...

I fixed it with:

```json
    "robot.pythonpath": [
        "${workspaceFolder}/",
        "${workspaceFolder}/libs",
        "${workspaceFolder}/protobuf"
    ]
```
