### ISSUE TITLE
Not compatible with the version of your running IDE (PyCharm 2023.1)

### ISSUE THREAD

**Issue by VKrus** [robocorp/robotframework-lsp#917]
**Describe the bug**
Cannot install plugin on the latest version of pycharm

**To Reproduce**
Try to install plugin on latest version

**Screenshots**
![image](https://user-images.githubusercontent.com/78022375/234250284-ce633e53-0125-4414-bd34-1e33b2a058e4.png)

**Versions:**
 - OS: [e.g. Windows 10]
 - Robot Framework Version: [e.g. 3.2]
 - Robot Framework Language Server Version: 1.10.0
 - Client Version: PyCharm 2023.1

**Comment by jxt1009** [comment]
bump

**Comment by Zeckie** [comment]
Version 1.10.1 is now available, and supports up to 2023.1.2 (rc) - https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server/versions
