### ISSUE TITLE
robotidy runs without config file

### ISSUE THREAD

**Issue by DetachHead** [robocorp/robotframework-lsp#918]
**Describe the bug**
when the formatter is set to robotidy, the following error occurs in the robotframework output when saving a `.robot` file:
```
AttributeError: 'NoneType' object has no attribute 'open'
```

this seems to be caused by https://github.com/MarketSquare/robotframework-tidy/issues/526, but my project has its robotidy config defined in `pyproject.toml`, so this error should not occur

**To Reproduce**
1. configure robotidy in `pyproject.toml`, eg:
    ```toml
    [tool.robotidy]
    configure = ["AlignTemplatedTestCases:enabled=True"]
    ```
2. set default formatter to robotidy in `.vscode/settings.json`:
    ```json
    {
        "editor.formatOnSave": true,
        "robot.codeFormatter": "robotidy"
    }
    ```
4. make a change to a `.robot` file and save it
5. check "Robot Framework" in the "Output" tab on the terminal

**Expected behavior**
file is formatted

**Versions:**
 - OS: windows 10
 - Robot Framework Version: 6.0.2
 - Robot Framework Language Server Version: 1.10.0
 - Client Version: vscode 1.77.3

**Comment by bhirsz** [comment]
Does it still happen? After fixing and releasing https://github.com/MarketSquare/robotframework-tidy/issues/526 . I'm asking because it could be something that needs to be fixed on Robotidy side.

**Comment by DetachHead** [comment]
looks like it's working again now, thanks!
