### ISSUE TITLE
Add execution arguments when using test tab

### ISSUE THREAD

**Issue by BriceBoy** [robocorp/robotframework-lsp#919]
When I use the test tab to run tests, I'd like to be able to define some Robot Framework args. For example I use these args to specify the loglevel, the output directory, add the debug file... like so :
`--loglevel TRACE --outputdir results --debugFile debug`

The problem is that I didn't find any other solution than modifying source file **run_robot__main__.py** and add these arguments in robot_args array.

`robot_args = [
    "--listener=robotframework_debug_adapter.listeners.DebugListener",
    "--listener=robotframework_debug_adapter.listeners.DebugListenerV2",
    "--outputdir=tests/results",
    "--loglevel=TRACE",
    "--debugFile=debug",
] + robot_args`

I tried using **robot.language-server.args** settings but it didn"t work for me.

Is it possible to add a setting to do this, or did I just not find the good one ?

**Robot Framework Language Server v1.10.0**

**Comment by fabioz** [comment]
Please see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-configure-the-launch-from-a-code-lensshortcut for details on how to configure the test launch shortcut.

**Comment by BriceBoy** [comment]
I tried using ["--outputdir","results"] / ["--outputdir results"] / ["--outputdir=results"] but nothing seems to work :

`    "version": "0.2.0",
    "configurations": [
        {
            "type": "robotframework-lsp",
            "name": "Robot Framework: Launch .robot file",
            "request": "launch",
            "cwd": "^\"\\${workspaceFolder}\"",
            "target": "^\"\\${file}\"",
            "terminal": "integrated",
            "env": {},
            "args": ["--outputdir=results"]
        }`

**Comment by sidhoah8** [comment]
For anyone landing on this issue to use execution arguments, the solution from fabioz works, but you have to put the arguments in a separate file. For example, I added the following configuration to the existing configuration in my settings.json in my Workspace:
```
"launch": {
    "configurations": [
        {
            "type": "robotframework-lsp",
            "name": "Robot Framework: Launch Template",
            "request": "launch",
            "terminal": "integrated",
            "args": ["--argumentfile", "${workspaceFolder}/arguments.txt"]
        }
    ],
  }
```

The contents of arguments.txt looks like:
`--outputdir=Results`
