### ISSUE TITLE
Automatically Add Custom Listener to Robot File Execution

### ISSUE THREAD

**Issue by CasparQuast** [robocorp/robotframework-lsp#927]
## Problem and Alternative Solutions:
I am working on a VSCode extension that should automatically add my custom listener to robot file executions using the robotframework-lsp extension. While I've achieved this by manipulating system variables or modifying the robotframework-lsp files, I believe there could be a more convenient solution. If there is an existing solution for this problem that I might have overlooked, please let me know.

## Proposed Solution/Idea:
I propose a user-friendly solution that allows adding custom listeners automatically to the execution of robot files in the robotframework-lsp extension. This solution should include the ability to configure a settings file recognized by the extension, specifying the custom listener to be added.

**Comment by fabioz** [comment]
@CasparQuast there is already a solution: add the proper listeners arguments in the execution.

See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-configure-the-launch-from-a-code-lensshortcut for details on how to do that for shortcuts (such as code lenses, dropdowns or tests).
