### ISSUE TITLE
Support Robot Framework 6.1

### ISSUE THREAD

**Issue by blelem** [robocorp/robotframework-lsp#936]
**Describe the bug**
Many errors of the type `TypeError: Object of type PosixPath is not JSON serializable` when running a test from the test panel.
```
Traceback (most recent call last):
  File "/home/vscode/.vscode-server/extensions/robocorp.robotframework-lsp-1.10.1/src/robotframework_ls/vendored/robocorp_ls_core/debug_adapter_core/debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "/home/vscode/.vscode-server/extensions/robocorp.robotframework-lsp-1.10.1/src/robotframework_ls/vendored/robocorp_ls_core/debug_adapter_core/dap/dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable
```

**To Reproduce**
When running a test from the test panel:
![image](https://github.com/robocorp/robotframework-lsp/assets/2476938/56bbb8b7-044e-424b-9b0d-bd27d659432f)
I believe this is related to Robot Framework version, we recently updated from 6.0.2 to 6.1b1
After editing the `dap_base_schema.py`  to_json, forcing the conversion of PosixPath objects to string, everything works ok.

```
def to_json(self, update_ids_to_dap=False):
        dico = self.to_dict(update_ids_to_dap=update_ids_to_dap)
        if "body" in dico:
            if "source" in dico["body"]:
                dico["body"]["source"] = repr(dico["body"]["source"])
            if "testOrSuiteSource" in dico["body"]:
                dico["body"]["testOrSuiteSource"] = repr(dico["body"]["testOrSuiteSource"])
        try:
            dump =  json.dumps(dico)
        except:
            dump = ""
            print("OH NOES", dico)
        return json.dumps(dico)
```
That fix is obviously not the right way to fix it, but it seems the issue is limited to the json serialization.

**Versions:**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Robot Framework Version:  6.1b1
 - Robot Framework Language Server Version: robocorp.robotframework-lsp-1.10.2 and robocorp.robotframework-lsp-1.10.1
 - Client Version: VSCode 1.78.2

**Logs**
Add the logs obtained when reproducing the issue.
See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md for details on how to collect the logs.

**Comment by fabioz** [comment]
It's known that Robot Framework 6.1 is not supported (this being one of the issues).

Renaming ticket accordingly.

**Comment by blelem** [comment]
Thanks for the fast reply! Looking forward 6.1 support.
