### ISSUE TITLE
Launching server using command /home/.../bin failed.

### ISSUE THREAD

**Issue by daniilsolovey** [robocorp/robotframework-lsp#94]
Unable to run the extension in vs code. Error: "Launching server using command /home/.../bin failed."

**Comment by fabioz** [comment]
This should be fixed by https://github.com/robocorp/robotframework-lsp/commit/40e4a5c243d2ba3d516efc72977c28ff6c34f161 (there was an issue looking for `python` in the `PATH` in Linux).

**Comment by fabioz** [comment]
Note: as a workaround, please specify the python executable manually by using the `robot.python.executable`.
