### ISSUE TITLE
Not resolving ${EXECDIR} keyword

### ISSUE THREAD

**Issue by rishabh114** [robocorp/robotframework-lsp#961]
**Describe the bug**
Getting error keyword not resolve while using ${EXECDIR} keyword .  Not able to import resource file using ${EXECDIR} .

**To Reproduce**
1. Import any resource using ${EXECDIR} keyword

**Expected behavior**
${EXECDIR} keyword  should work correctly. 

**Screenshots**
Please find the screenshot in the attachment

**Versions:**
 - OS: Windows 11
 - Robot Framework Version: 6.1
 - Robot Framework Language Server Version: 1.11.0
 - Client Version:  PyCharm 2023.1.4
<img width="829" alt="exedir_error_robot" src="https://github.com/robocorp/robotframework-lsp/assets/73388343/6fdea290-af70-48da-b137-a21b08aea039">

**Comment by fabioz** [comment]
Using ${EXECDIR} maps to the current working directory when Robot Framework is executing, so, it's possible that it points to different places and having a default is a bit odd.

You can still define the ${EXECDIR} to point to a different place using the robot.variables setting.

i.e.: `{"EXECDIR": "c:/<path>"}`
