### ISSUE TITLE
"Error generating libspec" Unresolved Library error when importing Python library that needs arguments

### ISSUE THREAD

**Issue by LucianRadul** [robocorp/robotframework-lsp#964]
**Describe the bug**
The RF LS can't resolve the library when the library needs an argument. RF executes the test without any issues, but RF LS still reports an error even though it's not there. Evidently, since RF LS can't find the Python library then it also reports that the keyword doesn't exist which is false.
<img width="491" alt="Screenshot 2023-07-26 140612" src="https://github.com/robocorp/robotframework-lsp/assets/57638808/5ae317bc-c46a-4647-a045-304a3d19bde7">
![Screenshot 2023-07-26 171301](https://github.com/robocorp/robotframework-lsp/assets/57638808/6c977998-2f68-4310-8d44-4bc05d573352)

The suggested course of action is the following:
```
Unresolved library: ${CURDIR}/TestLibrary.py.
Error generating libspec:
Library 'TestLibrary' expected 1 argument, got 0.
Consider using default arguments in the ${CURDIR}/TestLibrary.py constructor and
calling the "Robot Framework: Clear caches and restart" action or
adding "${CURDIR}/TestLibrary.py" to the "robot.libraries.libdoc.needsArgs"
setting to pass the typed arguments when generating the libspec.
```
I added `${CURDIR}/TestLibrary.py` to `robot.libraries.libdoc.needsArgs` as suggested, but it doesn't solve the issue.

I found the same issue reported in a different Robot project [here ](https://github.com/tlolkema/RobotNotifications/issues/5)but it isn't answered.

I found a similar issue for RF LS [here](https://github.com/robocorp/robotframework-lsp/issues/602) and I ran the recommended command `python -m robot.libdoc <library_name> <library_name.libspec>` but it throws the same error:
![Screenshot 2023-07-26 170605](https://github.com/robocorp/robotframework-lsp/assets/57638808/1fc724ae-b582-4ca0-a19c-9214015f45d8)
The response of the aforementioned issue recommended to submit another issue to RobotFramework and it was solved [here](https://github.com/robotframework/robotframework/issues/4275), however as you can see in my case I can still find it.

**To Reproduce**
`tests.robot`:
```
*** Settings ***
Documentation     A test suite.
...               Keywords are imported from the resource file
Resource          keywords.resource
Default Tags      positive

*** Variables ***
${arg}    blalbla

*** Test Cases ***

Placeholder test case
    Given No Operation
    When No Operation
    Then Keyword Test
```

![Screenshot 2023-07-26 171726](https://github.com/robocorp/robotframework-lsp/assets/57638808/170ef1c8-81b3-4d4f-92d6-f4beecfdb7d4)

`keywords.resource` (this is where VS Code reports the issue):
```
*** Variables ***
${arg}

*** Settings ***
Documentation     This is a resource file, that contains variables and keywords.
...               Keywords defined here can be used where this Keywords.resource in loaded.
Library    ${CURDIR}/TestLibrary.py    ${arg}

*** Keywords ***

Keyword Test
    Keyword Pybinding
```

![Screenshot 2023-07-26 172027](https://github.com/robocorp/robotframework-lsp/assets/57638808/c2697319-932a-455f-aa28-030dc4cc29ad)

`TestLibrary.py`:
```
from robot.api.deco import library, keyword

@library
class TestLibrary:

    def __init__(self, arg) -> None:
        self.argument = arg
        pass
    
    @keyword
    def keyword_pybinding(self):
        pass

```
![Screenshot 2023-07-26 171742](https://github.com/robocorp/robotframework-lsp/assets/57638808/86197340-7c3f-4bb5-8e24-aafee5450047)

**Expected behavior**
RF LS shouldn't report an error because RF executes without any issue.

**Versions:**
 - OS: Windows 10 version 21H2 build 19044.3208
 - Robot Framework Version: 6.1 (Python 3.11.2 on win32)
 - Robot Framework Language Server Version: v1.11.0
 - Client Version: VSCode 1.80.1

**Comment by fabioz** [comment]
The error you have:

`Library 'TestLibrary' expected 1 argument, got 0.`

Means that arguments are required in the library.

Please read the related faq entry: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved
