### ISSUE TITLE
Issue on creating new robot - 

### ISSUE THREAD

**Issue by damodeburca** [robocorp/robotframework-lsp#979]
**Describe the bug**
I get an error message in VSCode when i try to create a new robot

**To Reproduce**
1. In VSCode select the Create Robot command from command palette selection box
2. Error appears in VSCode: Unable to list Robot templates: Error running: C:\Installs\ robot initialize -l --json --controller RobocorpCode

**Expected behavior**
New robot template should be created

**Screenshots**

**Versions:**
 - OS: Windows 10 build 19042.2130
 - Robot Framework Version: [e.g. 3.2] na
 - Robot Framework Language Server Version:v 1.11.0
 - Client Version: [e.g.: VSCode 1.82.2

**Logs**
Add the logs obtained when reproducing the issue.
See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md for details on how to collect the logs.

**Comment by fabioz** [comment]
This probably means that there was some network connectivity issue (as templates are gotten from the web).

Can you paste the output you have in `Views > OUTPUT > Robocorp Code (in the dropdown)`?

**Comment by damodeburca** [comment]
Thanks for your reply - yes you are right - access is denied - I am not
sure what is blocking this as I have managed to create the robot manually
on the CLI
Here is the output
Many thanks
Traceback (most recent call last):
  File
"c:\Installs\VSCode\Extensions\robocorp.robocorp-code-1.11.0-win32-x64\src\robocorp_code\rcc.py",
line 329, in _run_rcc
    boutput = check_output(args, timeout=timeout, **kwargs)
  File
"c:\ProgramData\robocorp\ht\1f44aca_b1f3c24_0f61b987\lib\subprocess.py",
line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File
"c:\ProgramData\robocorp\ht\1f44aca_b1f3c24_0f61b987\lib\subprocess.py",
line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File
"c:\ProgramData\robocorp\ht\1f44aca_b1f3c24_0f61b987\lib\subprocess.py",
line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File
"c:\ProgramData\robocorp\ht\1f44aca_b1f3c24_0f61b987\lib\subprocess.py",
line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied
robocorp code: 2023-09-19 15:13:25 UTC pid: 25224 - MainThread - EXCEPTION
- robocorp_code.rcc
Error running: C:\Installs\ robot initialize -l --json --controller
RobocorpCode

Traceback (most recent call last):
  File
"c:\Installs\VSCode\Extensions\robocorp.robocorp-code-1.11.0-win32-x64\src\robocorp_code\rcc.py",
line 329, in _run_rcc
    boutput = check_output(args, timeout=timeout, **kwargs)
  File
"c:\ProgramData\robocorp\ht\1f44aca_b1f3c24_0f61b987\lib\subprocess.py",
line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File
"c:\ProgramData\robocorp\ht\1f44aca_b1f3c24_0f61b987\lib\subprocess.py",
line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File
"c:\ProgramData\robocorp\ht\1f44aca_b1f3c24_0f61b987\lib\subprocess.py",
line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File
"c:\ProgramData\robocorp\ht\1f44aca_b1f3c24_0f61b987\lib\subprocess.py",
line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied
