### ISSUE TITLE
Robot Framework lsp runs library init code while developing in vscode

### ISSUE THREAD

**Issue by suiluj** [robocorp/robotframework-lsp#988]
**Is your feature request related to a problem? Please describe.**

I am developing my custom library class for robot framework tests. On initialization `__init__` my code checks for environment variables.

The problem is that while developing in vscode the robot framework lsp extensions show errors because it run the code.  
But the environment variables will only be set on "real" test executions. I do not want to get errors while developing but I like the code reference features of the plugin so I would like to use it.

In my vscode settings I already disabled linting for variables.

- https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md
- Disable the undefined variables lint

```json
{
    "robot.lint.variables": false
}
```

The problems is that library init seems to get excuted still.

**Describe the solution you'd like**

I would like to have a setting to stop init library code running of the extension.

**Describe alternatives you've considered**

An alternative idea would be to check for an environment variable which could get run by the extension while only linting the code. Then my code could check on the variable and stop running the real initialization code.

Is there a solution for this?

**Comment by fabioz** [comment]
Unfortunately this isn't possible at this point. This happens because the language server uses `Robot Framework` to create the `.libspec` information and right now it can only do that from runtime information (it can't do it by just statically analyzing the file).

So, this is a `won't fix` at this point (we could do the static analysis, maybe even relying on a python language server, but this is a really big task and there are no plans to tackle that at this point).

**Comment by suiluj** [comment]
@fabioz 

But could this runtime set an environment variable so my code could react and behave in a different way when it is run as part of the lsp only? (as I described above).

So the lsp could set an environment variable like this:

```
RUN_BY_ROBOT_FRAMEWORK_LSP=TRUE
```

In my library init method I just check if the environment variable is set and then skip the rest of my code.

**Comment by fabioz** [comment]
Given that the language server uses Robot Framework for that (i.e.: it runs `python -m robot.libdoc <library_name> <library_name.libspec>`), I guess this should probably be handled in `Robot Framework` itself (so, other players in the ecosystem would benefit from it).

**Comment by suiluj** [comment]
okay I am no expert on robot framework yet. Do you know where to start?

Perhaps also reopen this issue so the idea is not closed. I understand that the code has to be run but the main point of the issue is to avoid my problems on initialization of my library which depends on environment variables.

I understand that I could refactor the initializatin code into another method but I would like to run the check on library initialization nevertheless.

**Comment by fabioz** [comment]
If you'd like to add the environment variable to check, you should create an issue in the RF tracker (https://github.com/robotframework/robotframework/issues).

For the static analysis this is known and tracked elsewhere, so, no need to leave it open for that...

**Comment by suiluj** [comment]
ok
